SELECT distinct ORL.ORDER_RELEASE_GID,
sh.shipment_gid,
ORL.SOURCE_LOCATION_GID SOURCE_LOCATION_GID,
SOURCE.LOCATION_NAME SOURCE_LOCATION_NAME,
SOURCE.COUNTRY_CODE3_GID SOURCE_COUNTRY,
ORL.DEST_LOCATION_GID DEST_LOCATION_GID,
DEST.LOCATION_NAME DEST_LOCATION_NAME,
DEST.COUNTRY_CODE3_GID DEST_COUNTRY,
ORL.INCO_TERM_GID INCOTERM,
    nvl((SELECT 
		or_ref_3.ORDER_RELEASE_REFNUM_VALUE
	FROM 
		ORDER_RELEASE_REFNUM or_ref_3
	WHERE 
		orl.ORDER_RELEASE_GID = or_ref_3.ORDER_RELEASE_GID
		AND or_ref_3.ORDER_RELEASE_REFNUM_QUAL_GID = 'ULE.ULE_COST CENTER'),'n/a')	ULE_COST_CENTER,
    sh.TRANSPORT_MODE_GID TRANSPORT_MODE,
    trim((case when sh.TRANSPORT_MODE_GID = 'UL_OCEAN' THEN TO_CHAR(ALOC.TOTAL_ALLOC_COST,'999999999D99') END)) OCEAN_COSTS,
    trim((case when sh.TRANSPORT_MODE_GID <> 'UL_OCEAN' THEN TO_CHAR(ALOC.TOTAL_ALLOC_COST,'999999999D99') END)) INLAND_COSTS,
    ALOC.TOTAL_COST_CURRENCY_GID COST_CURRENCY ,
    TO_CHAR(sh.start_time,'DD/MM/YYYY HH24:MI:SS')  shipment_start_time,
    
    
    
    nvl((SELECT 
		or_ref_1.ORDER_RELEASE_REFNUM_VALUE
	FROM 
		ORDER_RELEASE_REFNUM or_ref_1
	WHERE 
		orl.ORDER_RELEASE_GID = or_ref_1.ORDER_RELEASE_GID
		AND or_ref_1.ORDER_RELEASE_REFNUM_QUAL_GID = 'ULE.ULE_MATERIAL_TYPE'),'n/a')		MATERIAL_TYPE_ORDER,
    
        nvl((SELECT 
		or_ref_1.ORDER_RELEASE_REFNUM_VALUE
	FROM 
		ORDER_RELEASE_REFNUM or_ref_1
	WHERE 
		orl.ORDER_RELEASE_GID = or_ref_1.ORDER_RELEASE_GID
		AND or_ref_1.ORDER_RELEASE_REFNUM_QUAL_GID = 'UGO.ULE_CARRIAGE_CONDITION'),'n/a')		ULE_CARRIAGE_CONDITION
    




FROM

ALLOCATION_ORDER_RELEASE_D AORD,
ALLOCATION ALOC,
SHIPMENT SH,
ORDER_RELEASE ORL,
LOCATION SOURCE,
LOCATION DEST



WHERE 
1=1
AND AORD.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
AND SOURCE.LOCATION_GID = ORL.SOURCE_LOCATION_GID
AND DEST.LOCATION_GID = ORL.DEST_LOCATION_GID
AND ALOC.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
AND ALOC.ORDER_RELEASE_GID = AORD.ORDER_RELEASE_GID
AND SH.SHIPMENT_GID = ALOC.SHIPMENT_GID
AND ORL.DOMAIN_NAME = 'UGO'
and TRUNC(ORL.INSERT_DATE) >= TO_DATE(:P_INSERT_START,:P_DATE_FORMAT) AND TRUNC(ORL.INSERT_DATE) <= TO_DATE(:P_INSERT_END,:P_DATE_FORMAT)
order by 1