SELECT DISTINCT SH.SHIPMENT_GID AS																														SH_ID,
		ORLS.ORDER_RELEASE_GID	AS																														OR_ID,
		(
		SELECT LISTAGG(SHR_REGION.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SH_REGION.SHIPMENT_GID)
		FROM SHIPMENT SH_REGION
				LEFT OUTER JOIN SHIPMENT_REFNUM SHR_REGION ON (SH_REGION.SHIPMENT_GID = SHR_REGION.SHIPMENT_GID 
				AND SHR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION')
		WHERE
				SH_REGION.SHIPMENT_GID = SH.SHIPMENT_GID
		) 	AS 																																			DISPATCHING_REGION,	
			
			
		ORLS.SOURCE_LOCATION_GID AS																														SOURCE_LOC_ID,
		LOC_SOURCE.CITY AS 																																SOURCE_CITY,
		LOC_SOURCE.COUNTRY_CODE3_GID																													SOURCE_COUNTRY,

		ORLS.DEST_LOCATION_GID	AS																														DEST_LOC_ID,
		LOC_DEST.CITY AS 																																DESTINATION_CITY,
		LOC_DEST.COUNTRY_CODE3_GID																														DESTINATION_COUNTRY,

		(SH.SERVPROV_GID) AS 																															SERVICE_PROVIDER,
		(SELECT LOC_TSP.LOCATION_NAME
		FROM SHIPMENT SH_SERVPROV
		LEFT OUTER JOIN LOCATION LOC_TSP ON (LOC_TSP.LOCATION_GID = SH_SERVPROV.SERVPROV_GID)
		WHERE
			SH_SERVPROV.SHIPMENT_GID = SH.SHIPMENT_GID
		)AS 																																			SERVICE_PROVIDER_NAME,

		ORLS.INSERT_USER AS 																															ORLS_INSERT_USER,

		(
		SELECT LISTAGG(ORLSR_PO.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY ORLSR_PO.ORDER_RELEASE_GID)
		FROM ORDER_RELEASE_REFNUM ORLSR_PO 
		
		WHERE ORLS.ORDER_RELEASE_GID = ORLSR_PO.ORDER_RELEASE_GID 
				AND ORLSR_PO.ORDER_RELEASE_REFNUM_QUAL_GID IN ('PO','ULE.ULE_PO_NUMBER','ULE.ULE_SAP_PO_NUMBER','CUST_PO')
		
		
		) AS 																																		OR_PO_NUM,
		(
		SELECT LISTAGG(ORLSR_DN_ULE.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY ORLSR_DN_ULE.ORDER_RELEASE_GID)
		FROM ORDER_RELEASE_REFNUM ORLSR_DN_ULE 
		
		WHERE ORLS.ORDER_RELEASE_GID = ORLSR_DN_ULE.ORDER_RELEASE_GID 
				AND ORLSR_DN_ULE.ORDER_RELEASE_REFNUM_QUAL_GID IN ('ULE.ULE_DN_NUMBER','UL_SAP_DN')
		
		
		) AS 																																		OR_DN_NUM,
		(SELECT LISTAGG(SHR_PO.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_PO.SHIPMENT_GID)
		FROM SHIPMENT_REFNUM SHR_PO 
		WHERE SHR_PO.SHIPMENT_GID = SH.SHIPMENT_GID AND SHR_PO.SHIPMENT_REFNUM_QUAL_GID = 'ULE.PO'
		) AS 																																		SH_PO,
		(SELECT LISTAGG(SHR_DN.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_DN.SHIPMENT_GID)
		FROM SHIPMENT_REFNUM SHR_DN
		WHERE SHR_DN.SHIPMENT_GID = SH.SHIPMENT_GID AND SHR_DN.SHIPMENT_REFNUM_QUAL_GID = 'ULE.DN'
		) AS 																																		SH_DN,
		(SELECT LISTAGG(SHR_PLATE.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_PLATE.SHIPMENT_GID)
		FROM SHIPMENT_REFNUM SHR_PLATE 
		WHERE SHR_PLATE.SHIPMENT_GID = SH.SHIPMENT_GID AND SHR_PLATE.SHIPMENT_REFNUM_QUAL_GID = 'ULE.TRUCK PLATE'
		
		) AS 																																		TRUCK_PLATE,
		(SELECT LISTAGG(SHR_TRAILER.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_TRAILER.SHIPMENT_GID)
		FROM SHIPMENT_REFNUM SHR_TRAILER 
		WHERE (SHR_TRAILER.SHIPMENT_GID = SH.SHIPMENT_GID AND SHR_TRAILER.SHIPMENT_REFNUM_QUAL_GID = 'TRAILER')
		
		) AS 																																		TRAILER_NUMBER,
		to_char(UTC.GET_LOCAL_DATE(orls.late_pickup_date,orls.source_location_gid),'YYYY-MM-DD') AS 												orls_start,
		to_char(UTC.GET_LOCAL_DATE(orls.late_delivery_date,orls.DEST_LOCATION_GID),'YYYY-MM-DD') AS 												orls_end
FROM

	SHIPMENT SH,
	ORDER_RELEASE ORLS,
	LOCATION LOC_SOURCE,
	LOCATION LOC_DEST,
	VIEW_SHIPMENT_ORDER_RELEASE VORLS

WHERE 1=1
	AND SH.DOMAIN_NAME IN ('ULE/PR','ULE')
	AND	SH.SHIPMENT_TYPE_GID IN ('TRANSPORT')

	AND ORLS.ORDER_RELEASE_GID = VORLS.ORDER_RELEASE_GID
	AND SH.SHIPMENT_GID = VORLS.SHIPMENT_GID

	
	
	
	AND	LOC_SOURCE.LOCATION_GID = ORLS.SOURCE_LOCATION_GID
	AND	LOC_DEST.LOCATION_GID = ORLS.DEST_LOCATION_GID
	
	AND NOT EXISTS(SELECT 1
	FROM SHIPMENT_REFNUM
	WHERE SHIPMENT_GID = SH.SHIPMENT_GID
	AND SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_SHIPMENT_STREAM'
	AND SHIPMENT_REFNUM_VALUE = 'SECONDARY')

	AND trunc(orls.late_delivery_date) BETWEEN nvl(trunc(TO_DATE(:P_END_TIME_FROM,:P_DATE_TIME_FORMAT)),trunc(orls.late_delivery_date)) 
	AND nvl(trunc(TO_DATE(:P_END_TIME_TO,:P_DATE_TIME_FORMAT)),trunc(orls.late_delivery_date))
	
	AND trunc(orls.late_pickup_date) BETWEEN nvl(trunc(TO_DATE(:P_START_TIME_FROM,:P_DATE_TIME_FORMAT)),trunc(orls.late_pickup_date)) 
	AND nvl(trunc(TO_DATE(:P_start_TIME_TO,:P_DATE_TIME_FORMAT)),trunc(orls.late_pickup_date))
	
	AND 1=
    CASE
        WHEN :P_END_TIME_FROM IS NOT NULL OR :P_START_TIME_FROM IS NOT NULL THEN 1
        ELSE 0
    END       
	and (SELECT SHS_STATUS_CANC.STATUS_VALUE_GID
				FROM SHIPMENT_STATUS SHS_STATUS_CANC
				WHERE SHS_STATUS_CANC.STATUS_TYPE_GID = 'ULE/PR.TRANSPORT CANCELLATION'
				and SHS_STATUS_CANC.SHIPMENT_GID = SH.SHIPMENT_GID
		) <> 'ULE/PR.CANCELLED'

	AND (LOC_SOURCE.COUNTRY_CODE3_GID = 'HUN' or LOC_DEST.COUNTRY_CODE3_GID = 'HUN')
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	
