WITH pivot_data AS (

(SELECT DISTINCT TEMP_1.SHIPMENT_END_DATE AS END_DATE,
		TEMP_1.ACCESSORIAL AS		ACC_NAME,
		SUM(TEMP_1.COST_EUR) AS SHIPMENT_COST_2

FROM
(
SELECT  TO_CHAR(SH.end_time,'MM')																													SHIPMENT_END_DATE,

		sh.SHIPMENT_GID 																																		SH_GID,


				
		SH_COST.COST_TYPE AS 																												COST_TYPE,
		SH_COST.ACCESSORIAL_CODE_GID                  																						ACCESSORIAL,
		CASE
				WHEN SH_COST.COST_GID = 'EUR' THEN SH_COST.COST
				ELSE NVL2(SH_COST.COST * EXCHRATES.EXCHANGE_RATE, 
				SH_COST.COST * EXCHRATES.EXCHANGE_RATE, 0)
				END AS  																													COST_EUR,
				SH_COST.SHIPMENT_COST_SEQNO


FROM

SHIPMENT SH,
SHIPMENT_COST SH_COST
LEFT OUTER JOIN CURRENCY_EXCHANGE_RATE EXCHRATES ON (TO_CHAR(SH_COST.INSERT_DATE, 'Q-YYYY') = TO_CHAR(EXCHRATES.EFFECTIVE_DATE, 'Q-YYYY') 
				AND SH_COST.COST_GID = EXCHRATES.FROM_CURRENCY_GID 
				AND EXCHRATES.EXCHANGE_RATE_GID = 'ULE.ULE_QTY_EXCHANGE' 
				AND EXCHRATES.TO_CURRENCY_GID = 'EUR')



WHERE

SH.SHIPMENT_GID = SH_COST.SHIPMENT_GID

AND (SELECT SH_TEMP.TRANSPORT_MODE_GID
		FROM SHIPMENT SH_TEMP
		WHERE SH_TEMP.SHIPMENT_GID = sh.SHIPMENT_GID
		
		)	NOT IN ('UL_OCEAN','UL_LCL')
AND SH_COST.COST_TYPE = 'A'
and SH_COST.ACCESSORIAL_CODE_GID is not null
AND SH_COST.ACCESSORIAL_CODE_GID NOT IN ('UGO.UGO_FCL_FREIGHT_COST_CORRECTION','UGO.FUEL_SURCHARGE_BULK_OCEAN_24','UGO.FUEL_SURCHARGE_INTERMODAL_BULK_OCEAN_25',
'UGO.FUEL_SURCHARGE_INTERMODAL_BULK_OCEAN_25','UGO.UGO_FUEL_SURCHARGE_DESTINATION','UGO.UGO_FUEL_SURCHARGE_CORRECTION','UGO.UGO_INLAND_DESTINATION',
'UGO.UGO_FTL_FREIGHT_COST_CORRECTION','UGO.UGO_FREIGHT_COST_BASIC_FTL','UGO.UGO_BAF','UGO.FUEL_SURCHARGE_ORIGIN','UGO.UGO_FUEL_SURCHARGE_ORIGIN')


and to_char(sh.end_time,'YYYY') = :P_YEAR
AND SH.DOMAIN_NAME = 'UGO' 
/* AND TO_CHAR(SH.end_time,'MM') = 10 */
)  TEMP_1
GROUP BY 
TEMP_1.SHIPMENT_END_DATE,
		TEMP_1.ACCESSORIAL
 ) 
	)
select * from pivot_data
		
		

PIVOT (SUM(SHIPMENT_COST_2) AS SUM_TOTAL FOR (END_DATE) IN ('01' AS "01", '02' AS "02", '03' AS "03",'04' AS "04",'05' AS "05"
,'06' AS "06",'07' AS "07",'08' AS "08",'09' AS "09",'10' AS "10",'11' AS "11",'12' AS "12"))

