select orls.order_release_gid
		
		
		
from order_release orls
/* where  orls.insert_date > sysdate -60 */
WHERE to_char(orls.insert_date,'YYYY') = '2016'


AND EXISTS(SELECT 1
	FROM order_release_refnum
	WHERE ORDER_RELEASE_GID = orls.ORDER_RELEASE_GID
	AND ORDER_RELEASE_REFNUM_QUAL_GID like '%FINAL_BILLING%')

AND NOT EXISTS
(SELECT 1
FROM VIEW_SHIPMENT_ORDER_RELEASE VORLS
,SHIPMENT_STATUS SS
WHERE
SS.SHIPMENT_GID = VORLS.SHIPMENT_GID
AND VORLS.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
AND SS.STATUS_TYPE_GID = 'ULE/PR.SHIPMENT_COST'
AND SS.STATUS_VALUE_GID = 'ULE/PR.SC_NO CHANGES ALLOWED'


)
