SELECT * FROM
(SELECT DISTINCT ORLS.SOURCE_LOCATION_GID AS																											SOURCE_LOC_ID,
		loc_source.location_name as																														Source_name,
		LOC_SOURCE.CITY AS 																																SOURCE_CITY,
		LOC_SOURCE.COUNTRY_CODE3_GID AS 																												SOURCE_country,
		ORLS.DEST_LOCATION_GID	AS																														DEST_LOC_ID,
		loc_dest.location_name as																														Dest_name,
		LOC_DEST.CITY AS 																																DESTINATION_CITY,
		LOC_DEST.COUNTRY_CODE3_GID AS 																													DEST_country,	
-- ss.stop_num,		
		-- (
		-- select listagg(orls_CAT.order_release_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orls_CAT.order_release_GID)
		-- from order_release_REFNUM orls_CAT
		
		-- where orls_CAT.order_release_GID = orls.order_release_GID 
		-- AND orls_CAT.order_release_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_CATEGORY'
		-- ) AS 																																			CATEGORY,
		(
		select listagg(orls_CAT.order_release_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orls_CAT.order_release_GID)
		from order_release_REFNUM orls_CAT
		
		where orls_CAT.order_release_GID = orls.order_release_GID 
		AND orls_CAT.order_release_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_TYPE'

		) AS 																																			MATERIAL,
		(select listagg(NVL(SR_REGION.SHIPMENT_REFNUM_VALUE,'N/A'),'/') within group (order by SR_REGION.shipment_gid) AS REGION
		from SHIPMENT_REFNUM SR_REGION 
		where SR_REGION.SHIPMENT_GID = sh.SHIPMENT_GID AND SR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION'
		)																																				REGION,
		sh.insert_user																																	SH_INSERT_USER,
		
		
		-- (select listagg(SHR_RA.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_RA.SHIPMENT_GID)																										
		-- from SHIPMENT_REFNUM SHR_RA 
		-- where (SHR_RA.SHIPMENT_GID = sh.SHIPMENT_GID AND SHR_RA.SHIPMENT_REFNUM_QUAL_GID='ULE/PR.ULE_OR_REL_ATR')
		-- ) as 																																			RELEASE_ATTR,
		ORLS.ORDER_RELEASE_xid	AS																														OR_ID,	
		SH.SHIPMENT_xid AS																																SH_ID,
		'"'||(
		select listagg(orlsr_po.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orlsr_po.ORDER_RELEASE_GID)
		from ORDER_RELEASE_REFNUM orlsr_po 
		
		where orls.ORDER_RELEASE_GID = orlsr_po.ORDER_RELEASE_GID 
				AND orlsr_po.ORDER_RELEASE_REFNUM_QUAL_GID IN
				('PO','ULE.ULE_PO_NUMBER','ULE.ULE_SAP_PO_NUMBER','CUST_PO','ULE.ULE_FINANCE_PO_NUMBER')
		)||'"' AS 																																		OR_PO_NUM,
		'"'||(
		select listagg(orlsr_DN_ULE.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orlsr_DN_ULE.ORDER_RELEASE_GID)
		from ORDER_RELEASE_REFNUM orlsr_DN_ULE 
		
		where orls.ORDER_RELEASE_GID = orlsr_DN_ULE.ORDER_RELEASE_GID 
				AND orlsr_DN_ULE.ORDER_RELEASE_REFNUM_QUAL_GID IN ('ULE.ULE_DN_NUMBER','UL_SAP_DN')
		
		
		)||'"' AS 																																		OR_DN_NUM,
		LTRIM(TO_CHAR(ORLS.TOTAL_SHIP_UNIT_COUNT,'999999999','NLS_NUMERIC_CHARACTERS = '', ''')) AS														NUM_OF_PALLETS,
		(
		select listagg(orlsr_EXP.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orlsr_EXP.ORDER_RELEASE_GID)
		from ORDER_RELEASE_REFNUM orlsr_EXP
		
		where orls.ORDER_RELEASE_GID = orlsr_EXP.ORDER_RELEASE_GID 
				AND orlsr_EXP.ORDER_RELEASE_REFNUM_QUAL_GID IN ('ULE.ULE_EXPRESS_BY_CUSTOMER')

		) AS 																																			EXPRESS,
		to_char(ORLS.insert_date,'YYYY-MM-DD HH24:MI:SS') AS 																							or_INSERT_date,
		TO_CHAR(UTC.GET_LOCAL_DATE(ORLS.early_pickup_date,orls.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS')														early_pickup_date,
		
		/* to_char(ORLS.late_delivery_date,'YYYY-MM-DD') AS 																								late_delivery_date, */
		TO_CHAR(UTC.GET_LOCAL_DATE(ORLS.late_delivery_date,orls.dest_location_gid),'YYYY-MM-DD HH24:MI:SS')														late_delivery_date,
		TO_CHAR(UTC.GET_LOCAL_DATE(sh.start_time,sh.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS')															SH_START_TIME,
		/* TO_char(sh.END_TIME,'YYYY-MM-DD')																									SH_END_TIME, */
		
		(select  listagg(to_char(UTC.GET_LOCAL_DATE(ss.planned_departure,sh.dest_location_gid),'YYYY-MM-DD HH24:MI:SS'),'|') within group
		(order by ss.shipment_gid)
		from shipment_stop ss
		where ss.shipment_gid = sh.shipment_gid
		and ss.location_gid = SH.dest_location_gid
		and ss.stop_type = 'D'
		
		) as																																			planned_departure,	
		
		(
		
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,ORLS.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID

				AND	LR_LOAD_T.LOCATION_GID = orls.source_location_gid
				/* and ss.STOP_TYPE = 'P' */

		) AS 																																			APP_PICKUP,
	
		
		(
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,ORLS.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID

				AND	LR_LOAD_T.LOCATION_GID = orls.dest_location_gid
				/* and ss.STOP_TYPE = 'D' */

		) AS 																																			APP_DESTINATION,
	
		(sh.servprov_gid) as 																															SERVICE_PROVIDER,
		loc_tsp.LOCATION_NAME as 																														SERVPROV_NAME,
		-- (
		-- select listagg(SH_STATUS.STATUS_VALUE_GID,'|') WITHIN GROUP (ORDER BY SH_STATUS.SHIPMENT_GID)
		-- from SHIPMENT_STATUS SH_STATUS
		
		-- where SH.SHIPMENT_GID = SH_STATUS.SHIPMENT_GID 
				-- AND SH_STATUS.STATUS_TYPE_GID IN ('ULE/PR.SECURE RESOURCES')
		-- ) AS 																																			SECURE_RESOURCES_STATUS,
		
	
		(SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ORLS.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID LIKE '%CP'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = 1
			   
			   and (SSH.REPORTING_GLUSER like 'SERVPROV.%' OR SSH.REPORTING_GLUSER like 'ULE.T%')
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID LIKE  '%CP' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = 1
			   and (SSH_TEMP.REPORTING_GLUSER like 'SERVPROV.%' OR SSH_TEMP.REPORTING_GLUSER like 'ULE.T%')
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   )) AS																																				ACTUAL_ARRIVAL_TSP_pick,
			   
			   
			 
		
		(SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ORLS.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID LIKE '%D1'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = sh.NUM_STOPS
			   and (SSH.REPORTING_GLUSER like 'SERVPROV.%' OR SSH.REPORTING_GLUSER like 'ULE.T%')
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID LIKE  '%D1' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = SH.NUM_STOPS
			   and (SSH_TEMP.REPORTING_GLUSER like 'SERVPROV.%' OR SSH_TEMP.REPORTING_GLUSER like 'ULE.T%')
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   )) AS																																	ACTUAL_ARRIVAL_TSP_last_stop,
		(SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ORLS.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID LIKE '%CP'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = 1
			   
			   
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID LIKE  '%CP' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = 1
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   )) AS																																				ACTUAL_ARRIVAL_pick,
			   (SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ORLS.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID LIKE '%D1'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = sh.NUM_STOPS
			  
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID LIKE  '%D1' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = sh.NUM_STOPS
			   
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   )) AS																																	ACTUAL_ARRIVAL_LAST_STOP,
			 (SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ORLS.source_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID = 'ULE/PR.0005'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = 1
			  
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID =  'ULE/PR.0005' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = 1
			   
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   ))  																																		REGISTRATION_IN_pick,
			   (SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ORLS.source_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID = 'ULE/PR.0008'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = 1
			  
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID =  'ULE/PR.0008' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = 1
			   
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   ))  																																		REGISTRATION_out_pick,
			   (SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ORLS.source_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID = 'ULE/PR.0005'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = SH.NUM_STOPS
			  
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID =  'ULE/PR.0005' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = SH.NUM_STOPS
			   
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   ))  																																		REGISTRATION_IN_last_stop,
			   (SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ORLS.source_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID = 'ULE/PR.0008'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = SH.NUM_STOPS
			  
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID =  'ULE/PR.0008' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = SH.NUM_STOPS
			   
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   ))  																																		REGISTRATION_out_last_stop,
		(SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ORLS.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID LIKE '%CP'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = 1
			   
			   and (SSH.REPORTING_GLUSER = 'ULE.INTEGRATION')
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID LIKE  '%CP' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = 1
			   and (SSH_TEMP.REPORTING_GLUSER = 'ULE.INTEGRATION')
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   )) AS																																				Goods_issued,
			   
			   
			 
		
		(SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ORLS.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID LIKE '%D1'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = sh.NUM_STOPS
			   and (SSH.REPORTING_GLUSER = 'ULE.INTEGRATION')
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID LIKE  '%D1' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = SH.NUM_STOPS
			   and (SSH_TEMP.REPORTING_GLUSER = 'ULE.INTEGRATION')
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   )) AS																																	Goods_Receipt
			   


FROM
	SHIPMENT_STOP SS,
	SHIPMENT SH,
	SHIPMENT_STOP_D SSD,
	S_SHIP_UNIT SSU,
	S_SHIP_UNIT_LINE SSUL,
	ORDER_RELEASE ORLS,
	LOCATION LOC_SOURCE,
	LOCATION LOC_DEST,
	location loc_tsp


WHERE 1=1
	AND SH.DOMAIN_NAME = 'ULE/PR'
	AND	SH.SHIPMENT_TYPE_GID = 'TRANSPORT'
	
	AND	SS.SHIPMENT_GID = SH.SHIPMENT_GID
	AND SSD.SHIPMENT_GID = SS.SHIPMENT_GID
	AND SSD.STOP_NUM = SS.STOP_NUM
	AND SSD.S_SHIP_UNIT_GID = SSU.S_SHIP_UNIT_GID
	AND SSU.S_SHIP_UNIT_GID = SSUL.S_SHIP_UNIT_GID
	AND SSUL.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
	
	
	AND	LOC_SOURCE.LOCATION_GID = ORLS.SOURCE_LOCATION_GID
	AND	LOC_DEST.LOCATION_GID = ORLS.DEST_LOCATION_GID
	
	AND	loc_tsp.location_gid = sh.servprov_gid
	
	

	AND (SELECT SHS_STATUS_CANC.STATUS_VALUE_GID
	FROM SHIPMENT SH_STATUS_CANC
	LEFT OUTER JOIN SHIPMENT_STATUS SHS_STATUS_CANC ON (SH_STATUS_CANC.SHIPMENT_GID = SHS_STATUS_CANC.SHIPMENT_GID 
	AND SHS_STATUS_CANC.STATUS_TYPE_GID = 'ULE/PR.TRANSPORT CANCELLATION')
	WHERE SH_STATUS_CANC.SHIPMENT_GID = SH.SHIPMENT_GID
	)='ULE/PR.NOT CANCELLED'
	
	--------------------------------------------------------------------
	-- AND	trunc(ORLS.INSERT_DATE) >= trunc(SYSDATE) - 34
	-- and trunc(sh.start_time) >= trunc(SYSDATE) - 34
	
	-- -- AND	ORLS.INSERT_DATE >= nvl(TO_DATE(:INSERT_DATE_FROM,:P_DATE_TIME_FORMAT),ORLS.INSERT_DATE)
	-- -- and sh.start_time between nvl(tO_DATE(:SH_START_FROM,:P_DATE_TIME_FORMAT),sh.start_time) and nvl(TO_DATE(:SH_START_TO,:P_DATE_TIME_FORMAT),sh.start_time) 
	
		-- -- AND ORLS.SOURCE_LOCATION_GID = nvl(:SOURCE_LOC,ORLS.SOURCE_LOCATION_GID)
		-- -- AND ORLS.DEST_LOCATION_GID = nvl(:DEST_LOC,ORLS.DEST_LOCATION_GID)
		
		
		/* AND	ORLS.INSERT_DATE >= TO_DATE(NVL(NULL, sysdate-34),'YYYY-MM-DD') */
		-- AND orls.order_release_GID = 'ULE.0180779701'
		------------------------------------------------------------------------------------------------
		AND NOT EXISTS
	(SELECT 1
	 FROM shipment_refnum sh_ref_1
	 WHERE sh_ref_1.Shipment_Refnum_Qual_Gid = 'ULE.ULE_2Y_UPLOAD'
		   AND sh_ref_1.Shipment_Refnum_Value = 'YES'
		   AND sh_ref_1.SHIPMENT_GID = SH.SHIPMENT_GID)
		   
		   
	AND NOT EXISTS
	(SELECT 1
	 FROM shipment_refnum sh_ref_1
	 WHERE sh_ref_1.Shipment_Refnum_Qual_Gid = 'ULE.ULE_SHIPMENT_STREAM'
		   AND sh_ref_1.Shipment_Refnum_Value = 'SECONDARY'
		   AND sh_ref_1.SHIPMENT_GID = SH.SHIPMENT_GID)
		   
		   
	-- -- and 
	-- -- (select NVL(SR_REGION.SHIPMENT_REFNUM_VALUE,'N/A') AS REGION
		-- -- from SHIPMENT_REFNUM SR_REGION 
		-- -- where SR_REGION.SHIPMENT_GID = sh.SHIPMENT_GID AND SR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION' and rownum = 1
		-- -- ) = decode(:P_REGION,'ALL',(select NVL(SR_REGION.SHIPMENT_REFNUM_VALUE,'N/A') AS REGION
		-- -- from SHIPMENT_REFNUM SR_REGION 
		-- -- where SR_REGION.SHIPMENT_GID = sh.SHIPMENT_GID AND SR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION' and rownum = 1
		-- -- ),:P_REGION)
		
	AND(
	INSTR(','||nvl(:P_APP_LOC,substr(sh.source_location_gid,5))||',', ','||substr(sh.source_location_gid,5)||',') > 0 or 
	INSTR(','||nvl(:P_APP_LOC,substr(sh.dest_location_gid,5))||',', ','||substr(sh.dest_location_gid,5)||',') > 0)


	and (
	(SELECT LOC_REF.LOCATION_REFNUM_VALUE
	FROM LOCATION_REFNUM LOC_REF
	WHERE LOC_REF.LOCATION_REFNUM_QUAL_GID = 'ULE.ULE_REPORTING_NAME'
	AND LOC_REF.LOCATION_GID = sh.source_location_gid
	) 
	
	= NVL(:P_LOC_NAME,(SELECT LOC_REF.LOCATION_REFNUM_VALUE
	FROM LOCATION_REFNUM LOC_REF
	WHERE LOC_REF.LOCATION_REFNUM_QUAL_GID = 'ULE.ULE_REPORTING_NAME'
	AND LOC_REF.LOCATION_GID = sh.source_location_gid
	)) or 
	(SELECT LOC_REF.LOCATION_REFNUM_VALUE
	FROM LOCATION_REFNUM LOC_REF
	WHERE LOC_REF.LOCATION_REFNUM_QUAL_GID = 'ULE.ULE_REPORTING_NAME'
	AND LOC_REF.LOCATION_GID = sh.dest_location_gid
	)  = NVL(:P_LOC_NAME,(SELECT LOC_REF.LOCATION_REFNUM_VALUE
	FROM LOCATION_REFNUM LOC_REF
	WHERE LOC_REF.LOCATION_REFNUM_QUAL_GID = 'ULE.ULE_REPORTING_NAME'
	AND LOC_REF.LOCATION_GID = sh.dest_location_gid
	))
	)	
		
	AND SH.SERVPROV_GID = NVL(:P_SERVPROV,SH.SERVPROV_GID)

	AND trunc(SH.START_TIME) between nvl(trunc(TO_DATE(:P_START_TIME_FROM,:P_DATE_TIME_FORMAT)),trunc(SH.START_TIME))  
	and nvl(trunc(TO_DATE(:P_START_TIME_TO,:P_DATE_TIME_FORMAT)),trunc(SH.START_TIME))
	AND trunc(SH.END_TIME) BETWEEN nvl(trunc(TO_DATE(:P_END_TIME_FROM,:P_DATE_TIME_FORMAT)),trunc(SH.END_TIME)) 
	AND nvl(trunc(TO_DATE(:P_END_TIME_TO,:P_DATE_TIME_FORMAT)),trunc(SH.END_TIME))	
		
	AND (CASE WHEN :P_START_TIME_FROM IS NOT NULL THEN trunc(SH.START_TIME)
		WHEN :P_END_TIME_FROM IS NOT NULL THEN trunc(SH.END_TIME) 
		when (:P_START_TIME_FROM is null or :P_END_TIME_FROM is null) then trunc(SH.START_TIME) END
		) between coalesce(trunc(TO_DATE(NVL(:P_START_TIME_FROM,:P_END_TIME_FROM),:P_DATE_TIME_FORMAT)),trunc(sysdate))  
		and coalesce(trunc(TO_DATE(NVL(:P_START_TIME_FROM,:P_END_TIME_FROM),:P_DATE_TIME_FORMAT)),trunc(sysdate))+100	
		
	and 
	(select NVL(SR_REGION.SHIPMENT_REFNUM_VALUE,'N/A') AS REGION
		from SHIPMENT_REFNUM SR_REGION 
		where SR_REGION.SHIPMENT_GID = sh.SHIPMENT_GID AND SR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION' and rownum = 1
		) = decode(:P_REGION,'ALL',(select NVL(SR_REGION.SHIPMENT_REFNUM_VALUE,'N/A') AS REGION
		from SHIPMENT_REFNUM SR_REGION 
		where SR_REGION.SHIPMENT_GID = sh.SHIPMENT_GID AND SR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION' and rownum = 1
		),:P_REGION)
		
) TEMP
WHERE 1=1
	
	
	
