SELECT rpt_general.f_remove_domain(B.ORDER_RELEASE_GID), A.SHIPMENT_XID 


FROM SHIPMENT A, VIEW_SHIPMENT_ORDER_RELEASE B



WHERE   A.SHIPMENT_GID=B.SHIPMENT_GID 
AND A.BULK_PLAN_GID= :P_BULK_PLAN_ID 
 AND   A.TOTAL_ACTUAL_COST =0 
 AND A.TOTAL_NUM_REFERENCE_UNITS < 6.5 
 AND A.TRANSPORT_MODE_GID ='LTL'
 AND NOT EXISTS 
 (SELECT '1' FROM LOCATION_ROLE_PROFILE
 WHERE LOCATION_GID = A.DEST_LOCATION_GID 
 AND LOCATION_ROLE_GID='DECONSOLIDATION_POOL')
 

