select distinct temp.X_dock,
	    temp.LATE_DELIVERY_MONTH,
		temp.LATE_DELIVERY_WEEK,
		temp.SOURCE_LOC_NAME,
		temp.DEST_LOC_NAME,
		TEMP.TRANSPORT_HANDLING_UNIT_GID,
		sum(temp.pallets_in)									pallets_in,
		sum(temp.pallets_out)									pallets_out,
		sum(temp.pallets_in)+	sum(temp.pallets_out)						TOTAL_SHIP_UNIT_COUNT,
		count(temp.order_release_gid)							or_count
		

from (
SELECT orls.order_release_gid,
		ORLS.SOURCE_LOCATION_GID,
		ORLS.DEST_LOCATION_GID,
		case when ORLS.SOURCE_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837') then
		ORLS.SOURCE_LOCATION_GID
		else
		dest_LOCATION_GID end																								X_dock,
		-- ORLS.TOTAL_SHIP_UNIT_COUNT,
		
		
		
		case when ORLS.SOURCE_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837') then
		SU.SHIP_UNIT_COUNT
		else 0
		end as 														pallets_out,	
		case when ORLS.dest_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837') then
		SU.SHIP_UNIT_COUNT
		else 0
		end as 														pallets_in,	
		SU.SHIP_UNIT_GID,
		SU.TRANSPORT_HANDLING_UNIT_GID,
		-- SU.SHIP_UNIT_COUNT,
		
		
		
		
		
		

		(SELECT LOC.LOCATION_NAME
		FROM LOCATION LOC
		WHERE LOC.LOCATION_GID = ORLS.SOURCE_LOCATION_GID)		SOURCE_LOC_NAME,
		(SELECT LOC.LOCATION_NAME
		FROM LOCATION LOC
		WHERE LOC.LOCATION_GID = ORLS.DEST_LOCATION_GID)		DEST_LOC_NAME,
		(SELECT LOC.CITY
		FROM LOCATION LOC
		WHERE LOC.LOCATION_GID = ORLS.SOURCE_LOCATION_GID)		SOURCE_LOC_CITY,
		(SELECT LOC.CITY
		FROM LOCATION LOC
		WHERE LOC.LOCATION_GID = ORLS.DEST_LOCATION_GID)		DEST_LOC_CITY,
		TO_CHAR(ORLS.LATE_DELIVERY_DATE,'MM') AS 				LATE_DELIVERY_MONTH,
		TO_CHAR(ORLS.LATE_DELIVERY_DATE,'WW') AS 				LATE_DELIVERY_WEEK


FROM ORDER_rELEASE ORLS,
	SHIP_UNIT SU

WHERE
SU.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
AND (ORLS.SOURCE_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837')
OR ORLS.DEST_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837'))

and NOT EXISTS
		(SELECT 1
		FROM ORDER_RELEASE_REFNUM sh_ref_1
		WHERE sh_ref_1.ORDER_RELEASE_Refnum_Qual_Gid = 'ULE.ULE_SHIPMENT_STREAM'
		   AND sh_ref_1.ORDER_RELEASE_Refnum_Value = 'SECONDARY'
		   AND sh_ref_1.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID)	
		   
		   
and TO_CHAR(ORLS.LATE_DELIVERY_DATE,'YYYY') = '2015'
) temp

group by

temp.X_dock,
	    temp.LATE_DELIVERY_MONTH,
		temp.LATE_DELIVERY_WEEK,
		temp.SOURCE_LOC_NAME,
		temp.DEST_LOC_NAME,
		TEMP.TRANSPORT_HANDLING_UNIT_GID
