WITH pivot_data AS (

(SELECT TEMP_1.SHIPMENT_END_DATE AS SH_DATE,
		TEMP_1.ACCESSORIAL AS		ACC_NAME,
		SUM(TEMP_1.COST_EUR) AS SHIPMENT_COST_2

FROM
(
SELECT DISTINCT 
		( 
		CASE WHEN ORLS.ORDER_RELEASE_TYPE_GID = 'INBOUND'
		THEN(
			SELECT TO_CHAR(SH_TEMP.end_time,'MM')
			FROM SHIPMENT SH_TEMP
			WHERE SH_TEMP.SHIPMENT_GID = sh.SHIPMENT_GID)
		ELSE
			(
			SELECT TO_CHAR(SH_TEMP.START_TIME,'MM')
			FROM SHIPMENT SH_TEMP
			WHERE SH_TEMP.SHIPMENT_GID = sh.SHIPMENT_GID)
			END
		)	AS																																					SHIPMENT_END_DATE,

		sh.SHIPMENT_GID 																																		SH_GID,

		IVLI.ACCESSORIAL_CODE_GID                  																											ACCESSORIAL,
		(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)																																		COST_EUR

FROM

SHIPMENT SH,
INVOICE_LINEITEM_COST_REF ILCR,
INVOICE_LINEITEM IVLI,
ORDER_RELEASE ORLS,
ORDER_RELEASE_LINE ORLSL,
VIEW_SHIPMENT_ORDER_RELEASE VORLS



WHERE


(SELECT SH_TEMP.TRANSPORT_MODE_GID
		FROM SHIPMENT SH_TEMP
		WHERE SH_TEMP.SHIPMENT_GID = sh.SHIPMENT_GID
		
		) IN ('UL_OCEAN','UL_LCL')


AND ILCR.COST_REFERENCE_GID = ORLSL.ORDER_RELEASE_LINE_GID
AND IVLI.INVOICE_GID = ILCR.INVOICE_GID
AND IVLI.INVOICE_GID IS NOT NULL
AND VORLS.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
AND SH.SHIPMENT_GID = VORLS.SHIPMENT_GID
and ORLS.ORDER_RELEASE_GID=ORLSL.ORDER_RELEASE_GID
AND ORLS.DOMAIN_NAME='UGO'

and to_char(sh.end_time,'YYYY') = :P_YEAR
AND SH.DOMAIN_NAME = 'UGO' 
and IVLI.ACCESSORIAL_CODE_GID is not null

AND IVLI.ACCESSORIAL_CODE_GID NOT IN ('UGO.UGO_OTHC','UGO.UGO_BAF','UGO.UGO_DTHC','UGO.UGO_INLAND_ORIGIN','UGO.UGO_INLAND_DESTINATION','UGO.UGO_BAS','UGO.UGO_FCL_FREIGHT_COST_CORRECTION',
'UGO.UGO_DESTINATION_INLAND','UGO.UGO_FUEL_SURCHARGE_ORIGIN')


)  TEMP_1
GROUP BY 
TEMP_1.SHIPMENT_END_DATE,
		TEMP_1.ACCESSORIAL
 ) 
	)
select * from pivot_data
		
		

PIVOT (SUM(SHIPMENT_COST_2) AS SUM_TOTAL FOR (SH_DATE) IN ('01' AS "01", '02' AS "02", '03' AS "03",'04' AS "04",'05' AS "05"
,'06' AS "06",'07' AS "07",'08' AS "08",'09' AS "09",'10' AS "10",'11' AS "11",'12' AS "12"))










