select distinct temp.SHIPMENT_START_DATE,--WORKAROUND To be rebuilded
temp.OR_LINE_ID,
temp.OR_ID,
temp.SH_GID,
temp.CATEGORY,
temp.MATERIAL,
temp.TRANSPORT_MODE,
temp.INB_OUTB,
temp.INCOTERM,
temp.CARRIAGE_CONDITION,
temp.CONSIGNOR_ID,
temp.CONSIGNOR_NAME,
temp.CONSIGNOR_CITY,
temp.CONSIGNOR_COUNTRY,
temp.CONSIGNEE_ID,
temp.CONSIGNEE_NAME,
temp.CONSIGNEE_CITY,
temp.CONSIGNEE_COUNTRY,
temp.SOURCE_LOCATION_ID,
temp.SOURCE_LOC_NAME,
temp.SOURCE_LOC_CITY,
temp.SOURCE_LOC_COUNTRY,
temp.POL,
temp.POL_NAME,
temp.POL_CITY,
temp.POL_COUNTRY,
temp.POD,
temp.POD_NAME,
temp.POD_CITY,
temp.POD_COUNTRY,
temp.DEST_LOCATION_ID,
temp.DEST_LOC_NAME,
temp.DEST_LOC_CITY,
temp.DEST_LOC_COUNTRY,
temp.TRANSPORT_CONDITION,
temp.EQUIPMENT_GR,
temp.SERVPROV_ID,
temp.SERVPROV_NAME,
temp.GROSS_WEIGHT_KG,
temp.PACKAGE_COUNT,
temp.CANCELATION_STATUS,
temp.SH_INSERT_USER,
temp.INVOICE_NUMBERS,
temp.COST_CENTER,
sum(temp.BASE_COST_BAS),
sum(temp.BAF),
sum(temp.DTHC),
sum(temp.OTHC),
sum(temp.INLAND_ORIGIN),
sum(temp.INLAND_DESTINATION),
sum(temp.FCL_FREIGHTCOST_CORR),
sum(temp.ADDITIONAL_DISTANCE),
sum(temp.UGO_ALL_IN_RATE),
sum(temp.UGO_CANCELLATION_COST),
sum(temp.UGO_CONTAINER_COOLING),
sum(temp.UGO_CREDIT_NOTE),
sum(temp.UGO_CUSTOM_CLEARANCE_EXPORT),
sum(temp.UGO_CUSTOM_CLEARANCE_IMPORT),
sum(temp.UGO_DEMURRAGE_AT_CUSTOMS),
sum(temp.UGO_DEMURRAGE_AT_TERMINAL),
sum(temp.UGO_DEMURRAGE_AT_THE_PORT),
sum(temp.UGO_DEMURRAGE_LOADING_COST),
sum(temp.UGO_DEMURRAGE_UNLOADING_COST),
sum(temp.UGO_DETENTION),
sum(temp.UGO_DG_SURCHARGE),
sum(temp.UGO_DOCUMENTATION_COST),
sum(temp.UGO_PICK_UP_FEE),
sum(temp.UGO_STORAGE_COSTS),
sum(temp.UGO_TERMINAL_HANDLING_COST),
sum(temp.OTHER)

from(
SELECT DISTINCT (SELECT TO_CHAR(SH_TEMP.START_TIME,'DD-MM-YYYY')
		FROM SHIPMENT SH_TEMP
		WHERE SH_TEMP.SHIPMENT_GID = VORLS.SHIPMENT_GID
		)	AS																																					SHIPMENT_START_DATE,
		ORLSL.ORDER_RELEASE_LINE_GID                                																							OR_LINE_ID,
		ORLS.ORDER_RELEASE_GID																																	OR_ID,
		VORLS.SHIPMENT_GID 																																		SH_GID,
		(SELECT LISTAGG(OR_CAT.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY OR_CAT.ORDER_RELEASE_GID)
		FROM ORDER_RELEASE_REFNUM OR_CAT
		WHERE OR_CAT.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID 
		AND OR_CAT.ORDER_RELEASE_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_CATEGORY') AS 																				CATEGORY,
		(SELECT LISTAGG(OR_MAT.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY OR_MAT.ORDER_RELEASE_GID)
		FROM ORDER_RELEASE_REFNUM OR_MAT
		WHERE OR_MAT.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID 
		AND OR_MAT.ORDER_RELEASE_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_TYPE') AS 																					MATERIAL,
	
		(SELECT SH_TEMP.TRANSPORT_MODE_GID
		FROM SHIPMENT SH_TEMP
		WHERE SH_TEMP.SHIPMENT_GID = VORLS.SHIPMENT_GID
		
		)																																						TRANSPORT_MODE,

		CASE WHEN ORLS.ORDER_RELEASE_TYPE_GID = 'INBOUND' THEN 'INBOUND'
		ELSE 'OUTBOUND'
		END AS																																					INB_OUTB,
		
		ORLS.INCO_TERM_GID																																		INCOTERM,
		
		NVL((SELECT LISTAGG(OR_CARR.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY OR_CARR.ORDER_RELEASE_GID)
		FROM ORDER_RELEASE_REFNUM OR_CARR
		WHERE OR_CARR.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID 
		AND OR_CARR.ORDER_RELEASE_REFNUM_QUAL_GID ='UGO.ULE_CARRIAGE_CONDITION'),'-') AS 																		CARRIAGE_CONDITION,
		
		(SELECT LISTAGG(OR_CONSIGNOR.INVOLVED_PARTY_CONTACT_GID,'|') WITHIN GROUP (ORDER BY OR_CONSIGNOR.ORDER_RELEASE_GID)
		FROM ORDER_RELEASE_INV_PARTY OR_CONSIGNOR
		WHERE OR_CONSIGNOR.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID 
		AND OR_CONSIGNOR.INVOLVED_PARTY_QUAL_GID ='UGO.UGO_CONSIGNOR') AS 																						CONSIGNOR_ID,
		
		(SELECT LISTAGG(LOC_TEMP.LOCATION_NAME,'|') WITHIN GROUP (ORDER BY LOC_TEMP.LOCATION_GID)
		FROM LOCATION LOC_TEMP,
		ORDER_RELEASE_INV_PARTY OR_CONSIGNOR
		WHERE
		OR_CONSIGNOR.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID 
		AND OR_CONSIGNOR.INVOLVED_PARTY_QUAL_GID ='UGO.UGO_CONSIGNOR'
		AND OR_CONSIGNOR.INVOLVED_PARTY_CONTACT_GID = LOC_TEMP.LOCATION_GID
		
		) AS																																					CONSIGNOR_NAME,
		(SELECT LISTAGG(LOC_TEMP.CITY,'|') WITHIN GROUP (ORDER BY LOC_TEMP.LOCATION_GID)
		FROM LOCATION LOC_TEMP,
		ORDER_RELEASE_INV_PARTY OR_CONSIGNOR
		WHERE
		OR_CONSIGNOR.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID 
		AND OR_CONSIGNOR.INVOLVED_PARTY_QUAL_GID ='UGO.UGO_CONSIGNOR'
		AND OR_CONSIGNOR.INVOLVED_PARTY_CONTACT_GID = LOC_TEMP.LOCATION_GID
		
		) AS																																					CONSIGNOR_CITY,
		(SELECT LISTAGG(LOC_TEMP.COUNTRY_CODE3_GID,'|') WITHIN GROUP (ORDER BY LOC_TEMP.LOCATION_GID)
		FROM LOCATION LOC_TEMP,
		ORDER_RELEASE_INV_PARTY OR_CONSIGNOR
		WHERE
		OR_CONSIGNOR.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID 
		AND OR_CONSIGNOR.INVOLVED_PARTY_QUAL_GID ='UGO.UGO_CONSIGNOR'
		AND OR_CONSIGNOR.INVOLVED_PARTY_CONTACT_GID = LOC_TEMP.LOCATION_GID
		
		) AS																																					CONSIGNOR_COUNTRY,
		
		(SELECT LISTAGG(OR_CONSIGNEE.INVOLVED_PARTY_CONTACT_GID,'|') WITHIN GROUP (ORDER BY OR_CONSIGNEE.ORDER_RELEASE_GID)
		FROM ORDER_RELEASE_INV_PARTY OR_CONSIGNEE
		WHERE OR_CONSIGNEE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID 
		AND OR_CONSIGNEE.INVOLVED_PARTY_QUAL_GID ='CONSIGNEE') AS 																								CONSIGNEE_ID,
		
		(SELECT LISTAGG(LOC_TEMP.LOCATION_NAME,'|') WITHIN GROUP (ORDER BY LOC_TEMP.LOCATION_GID)
		FROM LOCATION LOC_TEMP,
		ORDER_RELEASE_INV_PARTY OR_CONSIGNOR
		WHERE
		OR_CONSIGNOR.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID 
		AND OR_CONSIGNOR.INVOLVED_PARTY_QUAL_GID ='CONSIGNEE'
		AND OR_CONSIGNOR.INVOLVED_PARTY_CONTACT_GID = LOC_TEMP.LOCATION_GID
		
		) AS																																					CONSIGNEE_NAME,
		(SELECT LISTAGG(LOC_TEMP.CITY,'|') WITHIN GROUP (ORDER BY LOC_TEMP.LOCATION_GID)
		FROM LOCATION LOC_TEMP,
		ORDER_RELEASE_INV_PARTY OR_CONSIGNOR
		WHERE
		OR_CONSIGNOR.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID 
		AND OR_CONSIGNOR.INVOLVED_PARTY_QUAL_GID ='CONSIGNEE'
		AND OR_CONSIGNOR.INVOLVED_PARTY_CONTACT_GID = LOC_TEMP.LOCATION_GID
		
		) AS																																					CONSIGNEE_CITY,
		(SELECT LISTAGG(LOC_TEMP.COUNTRY_CODE3_GID,'|') WITHIN GROUP (ORDER BY LOC_TEMP.LOCATION_GID)
		FROM LOCATION LOC_TEMP,
		ORDER_RELEASE_INV_PARTY OR_CONSIGNOR
		WHERE
		OR_CONSIGNOR.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID 
		AND OR_CONSIGNOR.INVOLVED_PARTY_QUAL_GID ='CONSIGNEE'
		AND OR_CONSIGNOR.INVOLVED_PARTY_CONTACT_GID = LOC_TEMP.LOCATION_GID
		
		) AS																																					CONSIGNEE_COUNTRY,

		ORLS.SOURCE_LOCATION_GID AS																																SOURCE_LOCATION_ID,
		(SELECT LOC_TEMP.LOCATION_NAME
		FROM LOCATION LOC_TEMP
		WHERE
		LOC_TEMP.LOCATION_GID = ORLS.SOURCE_LOCATION_GID
		) AS																																					SOURCE_LOC_NAME,
		(SELECT LOC_TEMP.CITY
		FROM LOCATION LOC_TEMP
		WHERE
		LOC_TEMP.LOCATION_GID = ORLS.SOURCE_LOCATION_GID
		) AS																																					SOURCE_LOC_CITY,
		(SELECT LOC_TEMP.COUNTRY_CODE3_GID
		FROM LOCATION LOC_TEMP
		WHERE
		LOC_TEMP.LOCATION_GID = ORLS.SOURCE_LOCATION_GID
		) AS																																					SOURCE_LOC_COUNTRY,
		
		ORLS.PORT_OF_LOAD_LOCATION_GID AS																														POL,
		(SELECT LOC_TEMP.LOCATION_NAME
		FROM LOCATION LOC_TEMP
		WHERE
		LOC_TEMP.LOCATION_GID = ORLS.PORT_OF_LOAD_LOCATION_GID
		) AS																																					POL_NAME,
		(SELECT LOC_TEMP.CITY
		FROM LOCATION LOC_TEMP
		WHERE
		LOC_TEMP.LOCATION_GID = ORLS.PORT_OF_LOAD_LOCATION_GID
		) AS																																					POL_CITY,
		(SELECT LOC_TEMP.COUNTRY_CODE3_GID
		FROM LOCATION LOC_TEMP
		WHERE
		LOC_TEMP.LOCATION_GID = ORLS.PORT_OF_LOAD_LOCATION_GID
		) AS																																					POL_COUNTRY,
		
		ORLS.PORT_OF_DIS_LOCATION_GID AS																														POD,
		(SELECT LOC_TEMP.LOCATION_NAME
		FROM LOCATION LOC_TEMP
		WHERE
		LOC_TEMP.LOCATION_GID = ORLS.PORT_OF_DIS_LOCATION_GID
		) AS																																					POD_NAME,
		(SELECT LOC_TEMP.CITY
		FROM LOCATION LOC_TEMP
		WHERE
		LOC_TEMP.LOCATION_GID = ORLS.PORT_OF_DIS_LOCATION_GID
		) AS																																					POD_CITY,
		(SELECT LOC_TEMP.COUNTRY_CODE3_GID
		FROM LOCATION LOC_TEMP
		WHERE
		LOC_TEMP.LOCATION_GID = ORLS.PORT_OF_DIS_LOCATION_GID
		) AS																																					POD_COUNTRY,
		
		ORLS.DEST_LOCATION_GID AS																																DEST_LOCATION_ID,
		(SELECT LOC_TEMP.LOCATION_NAME
		FROM LOCATION LOC_TEMP
		WHERE
		LOC_TEMP.LOCATION_GID = ORLS.DEST_LOCATION_GID
		) AS																																					DEST_LOC_NAME,
		(SELECT LOC_TEMP.CITY
		FROM LOCATION LOC_TEMP
		WHERE
		LOC_TEMP.LOCATION_GID = ORLS.DEST_LOCATION_GID
		) AS																																					DEST_LOC_CITY,
		(SELECT LOC_TEMP.COUNTRY_CODE3_GID
		FROM LOCATION LOC_TEMP
		WHERE
		LOC_TEMP.LOCATION_GID = ORLS.DEST_LOCATION_GID
		) AS																																					DEST_LOC_COUNTRY,
		(SELECT ORLS_REF.ORDER_RELEASE_REFNUM_VALUE
		FROM ORDER_RELEASE_REFNUM ORLS_REF
		WHERE
		ORLS_REF.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
		AND ORLS_REF.ORDER_RELEASE_REFNUM_QUAL_GID='ULE.ULE_TRANSPORT_CONDITION'
		
		) AS																																					TRANSPORT_CONDITION,
		NVL(ORLS.EQUIPMENT_GROUP_GID,'-')																														EQUIPMENT_GR,
		(SELECT SH_TEMP.SERVPROV_GID
		FROM SHIPMENT SH_TEMP
		WHERE VORLS.SHIPMENT_GID = SH_TEMP.SHIPMENT_GID
		
		)	AS																																					SERVPROV_ID,
		(SELECT SERVPROV_TEMP.LOCATION_NAME
		FROM SHIPMENT SH_TEMP,
				LOCATION SERVPROV_TEMP
		WHERE VORLS.SHIPMENT_GID = SH_TEMP.SHIPMENT_GID
			AND SH_TEMP.SERVPROV_GID = SERVPROV_TEMP.LOCATION_GID
		
		)	AS																																					SERVPROV_NAME,
		LTRIM(TO_CHAR(ORLSL.WEIGHT_BASE*0.45,'999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')) 																GROSS_WEIGHT_KG,
		LTRIM(TO_CHAR(ORLSL.ITEM_PACKAGE_COUNT,'999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')) 																PACKAGE_COUNT,
		
		(SELECT LISTAGG(SHS_STATUS_CANC.STATUS_VALUE_GID,'/') WITHIN GROUP (ORDER BY SHS_STATUS_CANC.SHIPMENT_GID)
				FROM SHIPMENT_STATUS SHS_STATUS_CANC
				WHERE SHS_STATUS_CANC.SHIPMENT_GID = VORLS.SHIPMENT_GID 
				AND SHS_STATUS_CANC.STATUS_TYPE_GID = 'UGO.TRANSPORT CANCELLATION'
		)																																						CANCELATION_STATUS,
		
	
				
				
				
				
		(SELECT SH_TEMP.INSERT_USER
		FROM SHIPMENT SH_TEMP
		WHERE SH_TEMP.SHIPMENT_GID = VORLS.SHIPMENT_GID
		) AS																																					SH_INSERT_USER,
		(SELECT LISTAGG(II.INVOICE_NUMBER,'/') WITHIN GROUP (ORDER BY ORLS.ORDER_RELEASE_GID)
		FROM INVOICE II 
		WHERE II.INVOICE_GID IN
		(SELECT ILCR.INVOICE_GID
		FROM ORDER_RELEASE_LINE ORLSL_TEMP,
			INVOICE_LINEITEM_COST_REF ILCR
			
		WHERE ORLSL_TEMP.ORDER_RELEASE_LINE_GID = ILCR.	COST_REFERENCE_GID
			AND ORLSL_TEMP.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID)
		
		) 																																						INVOICE_NUMBERS,
		(SELECT LISTAGG(ORLS_REF.ORDER_RELEASE_REFNUM_VALUE,'/') WITHIN GROUP (ORDER BY ORLS_REF.ORDER_RELEASE_GID)
				FROM ORDER_RELEASE_REFNUM ORLS_REF
				WHERE ORLS_REF.ORDER_RELEASE_GID = VORLS.ORDER_RELEASE_GID 
				AND ORLS_REF.ORDER_RELEASE_REFNUM_QUAL_GID = 'ULE.ULE_COST CENTER'
		)																																						COST_CENTER,

				
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
			
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID

				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_BAS' OR INV_LINE.ACCESSORIAL_CODE_GID IS NULL)
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																				BASE_COST_BAS,

				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
			
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
			
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_BAF')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																			BAF,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
			
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_DTHC')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																			DTHC,
				
				
				
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
			
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_OTHC')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																			OTHC,
				
				
				
				
				
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
	
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
	
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_INLAND_ORIGIN')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																			INLAND_ORIGIN,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
			
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
		
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_INLAND_DESTINATION' OR INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_DESTINATION_INLAND')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																			INLAND_DESTINATION,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
			
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
		
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_FCL_FREIGHT_COST_CORRECTION')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																			FCL_FREIGHTCOST_CORR,

				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
	
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				

				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_ADDITIONAL_DISTANCE')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																			ADDITIONAL_DISTANCE,
				
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
		
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_ALL_IN_RATE')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																			UGO_ALL_IN_RATE,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID

				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
			
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_CANCELLATION_COST')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																			UGO_CANCELLATION_COST,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
		
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_CONTAINER_COOLING')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																			UGO_CONTAINER_COOLING,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
			
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
			
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_CREDIT_NOTE')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																			UGO_CREDIT_NOTE,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
				
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_CUSTOM_CLEARANCE_EXPORT')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_CUSTOM_CLEARANCE_EXPORT,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
			
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
		
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_CUSTOM_CLEARANCE_IMPORT')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_CUSTOM_CLEARANCE_IMPORT,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
			
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_DEMURRAGE_AT_CUSTOMS')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_DEMURRAGE_AT_CUSTOMS,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
				
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
			
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_DEMURRAGE_AT_TERMINAL')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_DEMURRAGE_AT_TERMINAL,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				

				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_DEMURRAGE_AT_THE_PORT')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_DEMURRAGE_AT_THE_PORT,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
	
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_DEMURRAGE_LOADING_COST')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_DEMURRAGE_LOADING_COST,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
	
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
	
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_DEMURRAGE_UNLOADING_COST')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_DEMURRAGE_UNLOADING_COST,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				

				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_DETENTION')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_DETENTION,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
		
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_DG_SURCHARGE')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_DG_SURCHARGE,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
	
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_DOCUMENTATION_COST')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_DOCUMENTATION_COST,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
			
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE
				,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_PICK_UP_FEE')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_PICK_UP_FEE,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
	
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE
				,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_STORAGE_COSTS')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_STORAGE_COSTS,
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
			
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
			
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_TERMINAL_HANDLING_COST')
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	UGO_TERMINAL_HANDLING_COST,
				
				
				TRIM(NVL((SELECT TO_CHAR((SUM(CASE
				WHEN (IVLI.FREIGHT_CHARGE_GID = 'EUR' or IVLI.FREIGHT_CHARGE_GID is null) THEN IVLI.FREIGHT_CHARGE
				when IVLI.FREIGHT_CHARGE_GID <> 'EUR' then IVLI.FREIGHT_CHARGE * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),IVLI.FREIGHT_CHARGE_GID,'EUR')
				END)/
				(SELECT CASE WHEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)> 0 THEN COUNT(DISTINCT ILREF_TEMP.COST_REFERENCE_GID)
				ELSE 1
				END
				
				FROM INVOICE_SHIPMENT ISH,
					INVOICE_LINEITEM IL_TEMP,
					INVOICE_LINEITEM_COST_REF ILREF_TEMP
				WHERE
				ISH.SHIPMENT_GID = VORLS.SHIPMENT_GID
				AND ISH.INVOICE_GID = IL_TEMP.INVOICE_GID
		
				AND ISH.INVOICE_GID = INV_LINE.INVOICE_GID
				AND IL_TEMP.LINEITEM_SEQ_NO = ILREF_TEMP.LINEITEM_SEQ_NO
				AND ILREF_TEMP.INVOICE_GID = ISH.INVOICE_GID
				
			
				)),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
				
				FROM INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE
				
				WHERE IVLI.INVOICE_GID = INV_LINE.INVOICE_GID
				AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
				and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO
				AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID
				AND	(INV_LINE.ACCESSORIAL_CODE_GID IN ('UGO.UGO_CONTAINER_STUFFING_DESTUFFING','UGO.UGO_OVERWEIGHT_SURCHARGE'))
				GROUP BY
				INV_LINE.INVOICE_GID
				),0))																																	OTHER

FROM
ORDER_RELEASE ORLS,
SHIPMENT SH,
ORDER_RELEASE_LINE ORLSL,
VIEW_SHIPMENT_ORDER_RELEASE VORLS,
INVOICE_LINEITEM_COST_REF ILCR,
INVOICE_LINEITEM IVLI


WHERE
ORLS.ORDER_RELEASE_GID=ORLSL.ORDER_RELEASE_GID
AND SH.SHIPMENT_GID = VORLS.SHIPMENT_GID

AND VORLS.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
AND ORLS.DOMAIN_NAME='UGO'
AND (SELECT SH_TEMP.TRANSPORT_MODE_GID
		FROM SHIPMENT SH_TEMP
		WHERE SH_TEMP.SHIPMENT_GID = VORLS.SHIPMENT_GID
		
		)	IN ('UL_OCEAN','UL_LCL')
AND ILCR.COST_REFERENCE_GID = ORLSL.ORDER_RELEASE_LINE_GID
AND IVLI.INVOICE_GID = ILCR.INVOICE_GID
and ILCR.LINEITEM_SEQ_NO = ILCR.LINEITEM_SEQ_NO
AND IVLI.INVOICE_GID IS NOT NULL


/* AND SH.START_TIME BETWEEN TO_DATE('01-07-2014','DD-MM-YYYY') AND TO_DATE('01-08-2014','DD-MM-YYYY') */

/* AND	SH.START_TIME BETWEEN TRUNC(TRUNC(TRUNC(TRUNC(SYSDATE,'MM')-1,'MM')-1,'MM')-1,'MM')  AND TRUNC(SYSDATE,'MM') -- PREV 3 MONTHS MAX */
 
/* AND(SH.END_TIME BETWEEN TO_DATE(:INSERT_DATE_FROM,:P_DATE_TIME_FORMAT) AND TO_DATE(:INSERT_DATE_TO,:P_DATE_TIME_FORMAT) and ORLS.ORDER_RELEASE_TYPE_GID = 'INBOUND')
AND(SH.START_TIME BETWEEN TO_DATE(:INSERT_DATE_FROM,:P_DATE_TIME_FORMAT) AND TO_DATE(:INSERT_DATE_TO,:P_DATE_TIME_FORMAT) and  ORLS.ORDER_RELEASE_TYPE_GID = 'OUTBOUND') */
/* AND
(
CASE 
WHEN (ORLS.ORDER_RELEASE_TYPE_GID = 'INBOUND')
THEN SH.END_TIME
ELSE SH.START_TIME
END 
) >= TO_DATE(:INSERT_DATE_FROM,:P_DATE_TIME_FORMAT)
AND
(
CASE 
WHEN (ORLS.ORDER_RELEASE_TYPE_GID = 'INBOUND')
THEN SH.END_TIME
ELSE SH.START_TIME
END 
) <= TO_DATE(:INSERT_DATE_TO,:P_DATE_TIME_FORMAT)

AND
(
CASE 
WHEN (ORLS.ORDER_RELEASE_TYPE_GID = 'INBOUND')
THEN trunc(SH.END_TIME)
ELSE trunc(SH.START_TIME)
END 
) <= trunc(TO_DATE(:INSERT_DATE_FROM,:P_DATE_TIME_FORMAT))+100 */
and sh.shipment_gid='UGO.10002761'

/* and trunc(sh.start_time) <= trunc(TO_DATE(:INSERT_DATE_FROM,:P_DATE_TIME_FORMAT))+100 */
/* AND VORLS.SHIPMENT_GID ='UGO.10002860' */
) temp
group by
temp.SHIPMENT_START_DATE,
temp.OR_LINE_ID,
temp.OR_ID,
temp.SH_GID,
temp.CATEGORY,
temp.MATERIAL,
temp.TRANSPORT_MODE,
temp.INB_OUTB,
temp.INCOTERM,
temp.CARRIAGE_CONDITION,
temp.CONSIGNOR_ID,
temp.CONSIGNOR_NAME,
temp.CONSIGNOR_CITY,
temp.CONSIGNOR_COUNTRY,
temp.CONSIGNEE_ID,
temp.CONSIGNEE_NAME,
temp.CONSIGNEE_CITY,
temp.CONSIGNEE_COUNTRY,
temp.SOURCE_LOCATION_ID,
temp.SOURCE_LOC_NAME,
temp.SOURCE_LOC_CITY,
temp.SOURCE_LOC_COUNTRY,
temp.POL,
temp.POL_NAME,
temp.POL_CITY,
temp.POL_COUNTRY,
temp.POD,
temp.POD_NAME,
temp.POD_CITY,
temp.POD_COUNTRY,
temp.DEST_LOCATION_ID,
temp.DEST_LOC_NAME,
temp.DEST_LOC_CITY,
temp.DEST_LOC_COUNTRY,
temp.TRANSPORT_CONDITION,
temp.EQUIPMENT_GR,
temp.SERVPROV_ID,
temp.SERVPROV_NAME,
temp.GROSS_WEIGHT_KG,
temp.PACKAGE_COUNT,
temp.CANCELATION_STATUS,
temp.SH_INSERT_USER,
temp.INVOICE_NUMBERS,
temp.COST_CENTER


