select sh.shipment_gid,
		orls.order_release_gid,
		orlsl.ORDER_RELEASE_LINE_GID,
		(SELECT LISTAGG(II.invoice_gid,'/') WITHIN GROUP (ORDER BY ORLS.ORDER_RELEASE_GID)
		FROM INVOICE II 
		WHERE II.INVOICE_GID IN
		(SELECT ILCR.INVOICE_GID
		FROM ORDER_RELEASE_LINE ORLSL_TEMP,
			INVOICE_LINEITEM_COST_REF ILCR
			
		WHERE ORLSL_TEMP.ORDER_RELEASE_LINE_GID = ILCR.COST_REFERENCE_GID
			AND ORLSL_TEMP.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID)
		
		) 																						INVOICE_NUMBERS,
		(SELECT SUM(INV_LINE.FREIGHT_CHARGE)
				
				
				
				FROM invoice_shipment iv_sh,
				INVOICE_LINEITEM INV_LINE,
				ORDER_RELEASE_LINE OR_LINE,
				INVOICE_LINEITEM_COST_REF ILCR
				
				WHERE 
				/* IVLI.INVOICE_GID = INV_LINE.INVOICE_GID */
				 OR_LINE.ORDER_RELEASE_LINE_GID = ILCR.COST_REFERENCE_GID
				 and iv_sh.invoice_gid in (SELECT ILCR.INVOICE_GID
		FROM ORDER_RELEASE_LINE ORLSL_TEMP,
			INVOICE_LINEITEM_COST_REF ILCR
			
		WHERE ORLSL_TEMP.ORDER_RELEASE_LINE_GID = ILCR.COST_REFERENCE_GID
			AND ORLSL_TEMP.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID)
				 and iv_sh.invoice_gid = INV_LINE.INVOICE_GID
				/* AND OR_LINE.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID */
				/* and INV_LINE.LINEITEM_SEQ_NO = IVLI.LINEITEM_SEQ_NO */
				/* AND OR_LINE.ORDER_RELEASE_LINE_GID = ORLSL.ORDER_RELEASE_LINE_GID */
				AND	(INV_LINE.ACCESSORIAL_CODE_GID ='UGO.UGO_BAS' OR INV_LINE.ACCESSORIAL_CODE_GID IS NULL)
				GROUP BY
				sh.shipment_gid
				)																																			BASE_COST_BAS





FROM
ORDER_RELEASE ORLS,
SHIPMENT SH,
ORDER_RELEASE_LINE ORLSL,
VIEW_SHIPMENT_ORDER_RELEASE VORLS



where
ORLS.ORDER_RELEASE_GID=ORLSL.ORDER_RELEASE_GID
AND SH.SHIPMENT_GID = VORLS.SHIPMENT_GID
/* AND ORLSL.ORDER_RELEASE_LINE_GID = AOLD.ORDER_RELEASE_LINE_GID */
AND VORLS.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
AND ORLS.DOMAIN_NAME='UGO'
AND (SELECT SH_TEMP.TRANSPORT_MODE_GID
		FROM SHIPMENT SH_TEMP
		WHERE SH_TEMP.SHIPMENT_GID = VORLS.SHIPMENT_GID
		
		)	IN ('UL_OCEAN','UL_LCL')
AND VORLS.SHIPMENT_GID ='UGO.10002860'