SELECT
  la.X_LANE_GID,
  la.LANE_ATTRIBUTE_DEF_GID,


  count (la.LANE_ATTRIBUTE_DEF_GID)
FROM
  LANE_ATTRIBUTE la
WHERE
 1=1

GROUP BY
  la.X_LANE_GID,
  la.LANE_ATTRIBUTE_DEF_GID
HAVING
--  la.LANE_ATTRIBUTE_DEF_GID in ('ULE.ULE_FUNCTIONAL_REGION','ULE.ULE_TRANSPORT_CONDITION','ULE.ULE_SHIPMENT_STREAM','ULE.ULE_ORIGINAL_PFS','ULE.ULE_MATERIAL_TYPE')
  COUNT(la.LANE_ATTRIBUTE_DEF_GID) > 1
