select SH.SHIPMENT_GID,
to_char(sh.insert_date,'YYYY-MM-DD') AS SHIPMENT_INSERT_DATE,
TO_CHAR(SH.START_TIME,'YYYY-MM-DD') AS SHIPMENT_START_TIME,
TO_CHAR(SH.END_TIME,'YYYY-MM-DD') AS SHIPMENT_END_TIME,
SH.SHIPMENT_TYPE_GID SHIPMENT_TYPE





from shipment sh




where trunc(sh.insert_date) >= to_date('2015-01-01','YYYY-MM-DD')

AND NOT EXISTS
(SELECT 1
FROM SHIPMENT_COST SHC
WHERE SH.SHIPMENT_GID = SHC.SHIPMENT_GID
AND SHC.ACCESSORIAL_CODE_GID IN ('ACCESSORIAL_CODE_GID','ULE/PR.ULE_FUEL_SURCHARGE_10','ULE/SE.ULE_FUEL_SURCHARGE_RABEN_2Y','ULE/PR.ULE_FUEL_SURCHARGE_EDDIE_STOBART_18','ULE/PR.ULE_FUEL_SURCHARGE_GREAT_BEAR_17','ULE/SE.ULE_FUEL_SURCHARGE_FRESH_2Y','ULE/PR.ULE_FUEL_SURCHARGE_FRANCE_12','ULE/PR.ULE_FUEL_SURCHARGE_INTERMODAL_11','ULE/PR.ULE_FUEL_REIMBURSEMENT','ULE/PR.ULE_FUEL_SURCHARGE_E5_INTERMODAL_22','ULE/PR.ULE_FUEL_SURCHARGE_BULK_OCEAN_24','ULE/PR.ULE_FUEL_SURCHARGE_SPAIN_16','ULE/SE.ULE_FUEL_SURCHARGE_HOPI_2Y','ULE/PR.ULE_FUEL_SURCHARGE_OLIVE','ULE/PR.UAT_FUEL_SURCHARGE_TEST','ULE/PR.ULE_FUEL_SURCHARGE_KUEHNE_NAGEL_23','ULE/SE.ULE_FUEL_SURCHARGE_BALTICS','ULE/PR.ULE_FUEL_SURCHARGE_CEE_20','ULE/SE.ULE_FUEL_SURCHARGE_NAGEL_2Y','ULE/PR.ULE_FUEL_SURCHARGE_E5_21','ULE/PR.ULE_FUEL_SURCHARGE_HOPE_13','ULE/SE.ULE_FUEL_SURCHARGE_FM_CESKA_2Y','ULE/PR.ULE_FUEL_SURCHARGE_UK_15','ULE/PR.ULE_FUEL_SURCHARGE_ITALY_14','ULE/PR.ULE_FUEL_SURCHARGE_INTERMODAL_BULK_OCEAN_25','ULE/PR.ULE_FUEL SURCHARGE_UPLOAD','ULE/PR.ULE_FUEL_SURCHARGE_TOPEKA_13','ULE/SE.ULE_FUEL_SURCHARGE_TESCO (BACKHAUL)_2Y','ULE/PR.ULE_FUEL_SURCHARGE_WINCANTON_BULK_19','ULE/PR.ULE_FUEL_SURCHARGE_HOPI')

)
AND 
(SELECT SHS.SHIPMENT_GID
FROM SHIPMENT_STATUS SHS
WHERE SHS.SHIPMENT_GID = SH.SHIPMENT_GID
AND SHS.STATUS_TYPE_GID = 'ULE/PR.TRANSPORT CANCELLATION'
AND SHS.STATUS_VALUE_GID='ULE/PR.NOT CANCELLED'
) IS NOT NULL
AND NOT EXISTS(SELECT 1
	FROM SHIPMENT_REFNUM
	WHERE SHIPMENT_GID = SH.SHIPMENT_GID
	AND SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_SHIPMENT_STREAM'
	AND SHIPMENT_REFNUM_VALUE = 'SECONDARY')
AND
(SELECT SHS.STATUS_VALUE_GID
FROM SHIPMENT_STATUS SHS
WHERE SHS.SHIPMENT_GID = SH.SHIPMENT_GID
AND SHS.STATUS_TYPE_GID = 'ULE/PR.SHIPMENT_COST'
AND SHS.STATUS_VALUE_GID <>'ULE/PR.SC_NO CHANGES ALLOWED'
) IS NOT NULL
AND SH.RATE_GEO_GID IS NOT NULL



