select TO_CHAR(SH.START_TIME,'YYYY-MM-DD') 							SH_START_TIME,
TO_CHAR(ORLS.LATE_PICKUP_DATE,'YYYY-MM-DD') 							OR_LATEST_PICK_DATE,
ORLS.SOURCE_LOCATION_GID											OR_SOURCE,
(SELECT LOC_TEMP.POSTAL_CODE
FROM LOCATION LOC_TEMP
WHERE LOC_TEMP.LOCATION_GID = ORLS.SOURCE_LOCATION_GID
)																ORLS_SOURCE_LOC_POSTAL_CODE,
(SELECT LOC_TEMP.ADDRESS_LINE
FROM LOCATION_ADDRESS LOC_TEMP
WHERE LOC_TEMP.LOCATION_GID = ORLS.SOURCE_LOCATION_GID
)																ORLS_SOURCE_LOC_ADDRESS,
SH.SOURCE_LOCATION_GID											SH_SOURCE,
SH.SHIPMENT_GID,
ORLS.ORDER_RELEASE_GID,
SH.SERVPROV_GID																							HAULIER,
(SELECT LOC.LOCATION_NAME
FROM LOCATION LOC
WHERE LOC.LOCATION_GID = SH.SERVPROV_GID

) 																										HAULIER_NAME,


sh.rate_geo_gid,



ORLS.DEST_LOCATION_GID													OR_DEST_LOC_ID,
(SELECT LOC_TEMP.POSTAL_CODE
FROM LOCATION LOC_TEMP
WHERE LOC_TEMP.LOCATION_GID = ORLS.DEST_LOCATION_GID
)																ORLS_DEST_LOC_POSTAL_CODE,
(SELECT LOC_TEMP.ADDRESS_LINE
FROM LOCATION_ADDRESS LOC_TEMP
WHERE LOC_TEMP.LOCATION_GID = ORLS.DEST_LOCATION_GID
)																ORLS_DEST_LOC_ADDRESS,
SH.DEST_LOCATION_GID														SH_DEST_LOC,
(SELECT 
		or_ref_3.ORDER_RELEASE_REFNUM_VALUE
	FROM 
		ORDER_RELEASE_REFNUM or_ref_3
	WHERE 
		orls.ORDER_RELEASE_GID = or_ref_3.ORDER_RELEASE_GID
		AND or_ref_3.ORDER_RELEASE_REFNUM_QUAL_GID = 'ULE.ULE_ORIGINAL_PFS')																	OR_PFS,
(SELECT 
TRIM(TO_CHAR((SUM(CASE
				WHEN (ALLOC_OR.COST_CURRENCY_GID = 'EUR' or ALLOC_OR.COST_CURRENCY_GID is null) THEN ALLOC_OR.COST
				when ALLOC_OR.COST_CURRENCY_GID <> 'EUR' then ALLOC_OR.COST * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),ALLOC_OR.COST_CURRENCY_GID,'EUR')
				END)
			),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', '''))
FROM ALLOCATION_ORDER_RELEASE_D ALLOC_OR
WHERE ALLOC_OR.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
AND ALLOC_OR.COST_DESCRIPTION = 'B'





)																																									OR_BASE_COST,
(SELECT 
TRIM(TO_CHAR((SUM(CASE
				WHEN (ALLOC_OR.COST_CURRENCY_GID = 'EUR' or ALLOC_OR.COST_CURRENCY_GID is null) THEN ALLOC_OR.COST
				when ALLOC_OR.COST_CURRENCY_GID <> 'EUR' then ALLOC_OR.COST * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),ALLOC_OR.COST_CURRENCY_GID,'EUR')
				END)
			),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', '''))
FROM ALLOCATION_ORDER_RELEASE_D ALLOC_OR
WHERE ALLOC_OR.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
AND ALLOC_OR.COST_DESCRIPTION = 'A'
AND ALLOC_OR.ACCESSORIAL_CODE_GID <> 'ULE/PR.ULE_MULTISTOP'
AND ALLOC_OR.ACCESSORIAL_CODE_GID NOT LIKE '%FUEL%'





)																																									OR_CLAIM_COSTS,
(SELECT 
TRIM(TO_CHAR((SUM(CASE
				WHEN (ALLOC_OR.COST_CURRENCY_GID = 'EUR' or ALLOC_OR.COST_CURRENCY_GID is null) THEN ALLOC_OR.COST
				when ALLOC_OR.COST_CURRENCY_GID <> 'EUR' then ALLOC_OR.COST * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),ALLOC_OR.COST_CURRENCY_GID,'EUR')
				END)
			),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', '''))
FROM ALLOCATION_ORDER_RELEASE_D ALLOC_OR
WHERE ALLOC_OR.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
AND ALLOC_OR.COST_DESCRIPTION = 'A'
AND ALLOC_OR.ACCESSORIAL_CODE_GID <> 'ULE/PR.ULE_MULTISTOP'
AND ALLOC_OR.ACCESSORIAL_CODE_GID  LIKE '%FUEL%'





)																																									OR_FUEL_COSTS,
(SELECT 
TRIM(TO_CHAR((SUM(CASE
				WHEN (ALLOC_OR.COST_CURRENCY_GID = 'EUR' or ALLOC_OR.COST_CURRENCY_GID is null) THEN ALLOC_OR.COST
				when ALLOC_OR.COST_CURRENCY_GID <> 'EUR' then ALLOC_OR.COST * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(to_date(SH.END_TIME,'DD.MM.YYYY'),ALLOC_OR.COST_CURRENCY_GID,'EUR')
				END)
			),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', '''))
FROM ALLOCATION_ORDER_RELEASE_D ALLOC_OR
WHERE ALLOC_OR.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
AND ALLOC_OR.COST_DESCRIPTION = 'A'
AND ALLOC_OR.ACCESSORIAL_CODE_GID  = 'ULE/PR.ULE_MULTISTOP'





)																																									OR_MULTISTOP_ACC



from
shipment sh,
order_release orls,
order_movement om



where 1=1
AND SH.END_TIME BETWEEN TO_DATE('2015-04-01','YYYY-MM-DD') AND TO_DATE('2015-08-31','YYYY-MM-DD')
AND sh.shipment_gid = om.shipment_gid
and orls.order_release_gid = om.order_release_gid
	AND EXISTS(SELECT 1
	FROM SHIPMENT_REFNUM
	WHERE SHIPMENT_GID = SH.SHIPMENT_GID
	AND SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_SHIPMENT_STREAM'
	AND SHIPMENT_REFNUM_VALUE = 'SECONDARY')
	
and 
orls.source_location_gid in ('ULE.V206638','ULE.V226018','ULE.V205315','ULE.V205304')
AND
(SELECT COUNT(*)
FROM SHIPMENT_STOP SH_S
WHERE SH_S.SHIPMENT_GID = SH.SHIPMENT_GID
) > 2





















