select SH.SHIPMENT_GID,
to_char(sh.insert_date,'YYYY-MM-DD') AS SHIPMENT_INSERT_DATE,
TO_CHAR(SH.START_TIME,'YYYY-MM-DD') AS SHIPMENT_START_TIME,
TO_CHAR(SH.END_TIME,'YYYY-MM-DD') AS SHIPMENT_END_TIME,
SH.SHIPMENT_TYPE_GID SHIPMENT_TYPE,
case when (TRIM(TO_CHAR((select nvl((SELECT SUM(CASE
				WHEN (AC.CHARGE_AMOUNT_GID = 'EUR' OR AC.CHARGE_AMOUNT_GID IS NULL) THEN AC.CHARGE_AMOUNT
				WHEN AC.CHARGE_AMOUNT_GID <> 'EUR' THEN AC.CHARGE_AMOUNT * 
				UNILEVER.EBS_PROCEDURES_ULE.GET_QUARTERLY_EX_RATE(SYSDATE,AC.CHARGE_AMOUNT_GID,'EUR')
				else 0
				END)
	
				FROM ACCESSORIAL_COST AC,
					RATE_GEO_ACCESSORIAL RG_AC
				WHERE RG_AC.ACCESSORIAL_COST_GID = AC.ACCESSORIAL_COST_GID
				AND RG_AC.RATE_GEO_GID = sh.RATE_GEO_GID
				AND TO_CHAR(AC.EFFECTIVE_DATE,'YYYY-MM-DD') = TO_CHAR(TRUNC(SYSDATE,'MM'),'YYYY-MM-DD')
				and AC.ACCESSORIAL_COST_XID LIKE '%REIMBURSEMENT%'
				),0) from dual),'999999999999D99','NLS_NUMERIC_CHARACTERS = ''. '''))) <> 0 then 'Y' else 'N' end as							REIMBURSMENT_FUEL_eur_ON_rr,
		(TRIM((select nvl((SELECT DISTINCT rG_AC.ACCESSORIAL_CODE_GID
	
				FROM ACCESSORIAL_COST AC,
					RATE_GEO_ACCESSORIAL RG_AC
				WHERE RG_AC.ACCESSORIAL_COST_GID = AC.ACCESSORIAL_COST_GID
				AND RG_AC.RATE_GEO_GID = sh.RATE_GEO_GID
				AND TO_CHAR(AC.EFFECTIVE_DATE,'YYYY-MM-DD') = TO_CHAR(TRUNC(SYSDATE,'MM'),'YYYY-MM-DD')
				),0) from dual)))  as							acc_ON_RR,
				
SH_C.ACCESSORIAL_CODE_GID   ACCESSORIAL_ON_SH,
SH_C.COST,
SH_C.COST_GID,
sh.rate_geo_gid

				






from shipment sh,
shipment sh_cost
LEFT OUTER JOIN shipment_cost sh_c ON (sh_cost.shipment_gid = sh_c.shipment_gid and SH_C.ACCESSORIAL_CODE_GID LIKE '%FUEL%')




where trunc(sh.insert_date) >= to_date('2015-01-01','YYYY-MM-DD')
AND SH.shipment_gid = sh_cost.shipment_gid
AND EXISTS
(SELECT 1
FROM 
ACCESSORIAL_COST AC,
					RATE_GEO_ACCESSORIAL RG_AC
					
WHERE 
RG_AC.ACCESSORIAL_COST_GID = AC.ACCESSORIAL_COST_GID
				AND RG_AC.RATE_GEO_GID = sh.RATE_GEO_GID
 and AC.ACCESSORIAL_COST_XID LIKE '%FUEL%'
)
AND NOT EXISTS
(SELECT 1
FROM SHIPMENT_COST SHC
WHERE SH.SHIPMENT_GID = SHC.SHIPMENT_GID
AND SHC.ACCESSORIAL_CODE_GID IN ('ULE/PR.ULE_FUEL_SURCHARGE_10','ULE/SE.ULE_FUEL_SURCHARGE_RABEN_2Y',
'ULE/PR.ULE_FUEL_SURCHARGE_EDDIE_STOBART_18','ULE/PR.ULE_FUEL_SURCHARGE_GREAT_BEAR_17','ULE/SE.ULE_FUEL_SURCHARGE_FRESH_2Y',
'ULE/PR.ULE_FUEL_SURCHARGE_FRANCE_12','ULE/PR.ULE_FUEL_SURCHARGE_INTERMODAL_11','ULE/PR.ULE_FUEL_REIMBURSEMENT',
'ULE/PR.ULE_FUEL_SURCHARGE_E5_INTERMODAL_22','ULE/PR.ULE_FUEL_SURCHARGE_BULK_OCEAN_24','ULE/PR.ULE_FUEL_SURCHARGE_SPAIN_16',
'ULE/SE.ULE_FUEL_SURCHARGE_HOPI_2Y','ULE/PR.ULE_FUEL_SURCHARGE_OLIVE','ULE/PR.UAT_FUEL_SURCHARGE_TEST','ULE/PR.ULE_FUEL_SURCHARGE_KUEHNE_NAGEL_23',
'ULE/SE.ULE_FUEL_SURCHARGE_BALTICS','ULE/PR.ULE_FUEL_SURCHARGE_CEE_20','ULE/SE.ULE_FUEL_SURCHARGE_NAGEL_2Y','ULE/PR.ULE_FUEL_SURCHARGE_E5_21',
'ULE/PR.ULE_FUEL_SURCHARGE_HOPE_13','ULE/SE.ULE_FUEL_SURCHARGE_FM_CESKA_2Y','ULE/PR.ULE_FUEL_SURCHARGE_UK_15','ULE/PR.ULE_FUEL_SURCHARGE_ITALY_14',
'ULE/PR.ULE_FUEL_SURCHARGE_INTERMODAL_BULK_OCEAN_25','ULE/PR.ULE_FUEL SURCHARGE_UPLOAD','ULE/PR.ULE_FUEL_SURCHARGE_TOPEKA_13',
'ULE/SE.ULE_FUEL_SURCHARGE_TESCO (BACKHAUL)_2Y','ULE/PR.ULE_FUEL_SURCHARGE_WINCANTON_BULK_19','ULE/PR.ULE_FUEL_SURCHARGE_HOPI','ULE/PR.FUEL_SURCHARGE_CZE_FRO',
'ULE/PR.FUEL_SURCHARGE_SVK_FRO')
)



AND 
(SELECT SHS.SHIPMENT_GID
FROM SHIPMENT_STATUS SHS
WHERE SHS.SHIPMENT_GID = SH.SHIPMENT_GID
AND SHS.STATUS_TYPE_GID = 'ULE/PR.TRANSPORT CANCELLATION'
AND SHS.STATUS_VALUE_GID='ULE/PR.NOT CANCELLED'
) IS NOT NULL
AND NOT EXISTS(SELECT 1
	FROM SHIPMENT_REFNUM
	WHERE SHIPMENT_GID = SH.SHIPMENT_GID
	AND SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_SHIPMENT_STREAM'
	AND SHIPMENT_REFNUM_VALUE = 'SECONDARY')
AND
(SELECT SHS.STATUS_VALUE_GID
FROM SHIPMENT_STATUS SHS
WHERE SHS.SHIPMENT_GID = SH.SHIPMENT_GID
AND SHS.STATUS_TYPE_GID = 'ULE/PR.SHIPMENT_COST'
AND SHS.STATUS_VALUE_GID <>'ULE/PR.SC_NO CHANGES ALLOWED'
) IS NOT NULL
AND SH.RATE_GEO_GID IS NOT NULL



