SELECT LOC.LOCATION_GID,
'LOCATION '||rpt_general.f_remove_domain(LOC.LOCATION_GID)||'- '||
(SELECT 
(LISTAGG(rpt_general.f_remove_domain(LOC_REM.REMARK_QUAL_GID)||': '||REMARK_TEXT,',') 
WITHIN GROUP (ORDER BY LOC_REM.LOCATION_GID))

FROM LOCATION_REMARK LOC_REM
WHERE LOC_REM.LOCATION_GID = LOC.LOCATION_GID
) AS REMARK,
length(
'LOCATION '||rpt_general.f_remove_domain(LOC.LOCATION_GID)||'- '||
(SELECT 
(LISTAGG(rpt_general.f_remove_domain(LOC_REM.REMARK_QUAL_GID)||': '||REMARK_TEXT,',') 
WITHIN GROUP (ORDER BY LOC_REM.LOCATION_GID))

FROM LOCATION_REMARK LOC_REM
WHERE LOC_REM.LOCATION_GID = LOC.LOCATION_GID
)
) as txt_len
FROM LOCATION LOC

/* WHERE LOC.LOCATION_GID IN ('ULE.V189481','ULE.V207484') */

and

length(
'LOCATION '||rpt_general.f_remove_domain(LOC.LOCATION_GID)||'- '||
(SELECT 
(LISTAGG(rpt_general.f_remove_domain(LOC_REM.REMARK_QUAL_GID)||': '||REMARK_TEXT,',') 
WITHIN GROUP (ORDER BY LOC_REM.LOCATION_GID))

FROM LOCATION_REMARK LOC_REM
WHERE LOC_REM.LOCATION_GID = LOC.LOCATION_GID
)
)>400








