SELECT SH.SHIPMENT_GID,
	ORLS.ORDER_RELEASE_GID,
	ORLS.SOURCE_LOCATION_GID  							OR_SOURCE,
	ORLS.DEST_LOCATION_GID									OR_DEST,
	SH.SOURCE_LOCATION_GID								SH_SOURCE,
	SH.DEST_LOCATION_GID									SH_DEST,
	
	
	TO_CHAR(ORLS.EARLY_PICKUP_DATE,'YYYY-MM-DD')        OR_EARLY_PICKUP_DATE,
	TO_CHAR(ORLS.LATE_PICKUP_DATE,'YYYY-MM-DD')        OR_LATE_PICKUP_DATE,
	TO_CHAR(ORLS.EARLY_DELIVERY_DATE,'YYYY-MM-DD')        OR_EARLY_DELIVERY_DATE,
	TO_CHAR(ORLS.LATE_DELIVERY_DATE,'YYYY-MM-DD')        OR_LATE_DELIVERY_DATE,
	TO_CHAR(SH.START_TIME,'YYYY-MM-DD')        					SH_START_TIME,
	TO_CHAR(SH.END_TIME,'YYYY-MM-DD')        					SH_END_TIME,
	TO_CHAR(SH.INSERT_DATE,'YYYY-MM-DD')        					SH_INSERT_DATE,
	SH.INSERT_USER																	SH_INSERT_USER,
	
	
	(
		SELECT LISTAGG(SHR_REGION.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_REGION.SHIPMENT_GID)
		FROM SHIPMENT_REFNUM SHR_REGION
		WHERE
			 SHR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION'
			AND	SHR_REGION.SHIPMENT_GID = SH.SHIPMENT_GID
	) 	AS 																																			REGION
	
FROM ORDER_RELEASE ORLS,
	ORDER_MOVEMENT VORLS,
	SHIPMENT SH
	
WHERE 1=1

AND TRUNC(SH.INSERT_DATE) >= TO_DATE('2015-05-26','YYYY-MM-DD')

AND ORLS.ORDER_RELEASE_GID = VORLS.ORDER_RELEASE_GID
AND SH.SHIPMENT_GID = VORLS.SHIPMENT_GID

AND NOT EXISTS
							(SELECT 1
							 FROM SHIPMENT_REFNUM SH_REF_1
							 WHERE SH_REF_1.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_SHIPMENT_STREAM'
							 AND SH_REF_1.SHIPMENT_REFNUM_VALUE = 'SECONDARY'
							 AND SH_REF_1.SHIPMENT_GID = SH.SHIPMENT_GID)

AND NOT EXISTS
		   (
		   SELECT 1
			FROM SHIPMENT SH_TEMP,
			VIEW_SHIPMENT_ORDER_RELEASE VORLS_TEMP,
				ORDER_RELEASE ORLS_TEMP
				
			WHERE 1=1
			AND SH_TEMP.SHIPMENT_GID = VORLS_TEMP.SHIPMENT_GID
			AND ORLS_TEMP.ORDER_RELEASE_GID = VORLS_TEMP.ORDER_RELEASE_GID
			AND ORLS_TEMP.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
			AND SH_TEMP.SHIPMENT_TYPE_GID = 'HANDLING'
				
			)
	
AND (
		CASE
				WHEN (SELECT 
					SH_REF_1.SHIPMENT_REFNUM_VALUE
				FROM 
					SHIPMENT_REFNUM SH_REF_1
				WHERE 
					SH.SHIPMENT_GID = SH_REF_1.SHIPMENT_GID
					AND SH_REF_1.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_XLS_UPLD_SHIPMENT_REF_NO') IS NULL THEN 'N'
				ELSE 'Y'
			END 	) = 'N'