SELECT SH.SHIPMENT_GID,
		SH.RATE_GEO_GID,
		XL.X_LANE_GID,
		(SELECT LA.LANE_ATTRIBUTE_VALUE
		FROM LANE_ATTRIBUTE LA
		WHERE LA.X_LANE_GID = XL.X_LANE_GID
		AND LA.LANE_ATTRIBUTE_DEF_GID = 'ULE.ULE_MASTER_TAG'
		)																										MASTER_TAG,
		TRIM((SELECT TO_CHAR(SUM(CASE
				WHEN (SHC.COST_GID = 'EUR' OR SHC.COST_GID IS NULL) THEN SHC.COST
				WHEN SHC.COST_GID <> 'EUR' THEN SHC.COST * 
				UNILEVER.EBS_PROCEDURES_ULE.GET_QUARTERLY_EX_RATE(TO_DATE(SH.END_TIME,'DD.MM.YYYY'),SHC.COST_GID,'EUR')
				END),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
		FROM SHIPMENT_COST SHC
		WHERE SHC.SHIPMENT_GID = SH.SHIPMENT_GID
		AND SHC.COST_TYPE	IN ('B')
		))																																																									BASE_COST_EUR,
		TRIM((SELECT TO_CHAR(SUM(CASE
				WHEN (SHC.COST_GID = 'EUR' OR SHC.COST_GID IS NULL) THEN SHC.COST
				WHEN SHC.COST_GID <> 'EUR' THEN SHC.COST * 
				UNILEVER.EBS_PROCEDURES_ULE.GET_QUARTERLY_EX_RATE(TO_DATE(SH.END_TIME,'DD.MM.YYYY'),SHC.COST_GID,'EUR')
				END),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
		FROM SHIPMENT_COST SHC
		WHERE SHC.SHIPMENT_GID = SH.SHIPMENT_GID
		AND SHC.COST_TYPE	IN ('A','O')
		AND SHC.ACCESSORIAL_CODE_GID = 'ULE/PR.ULE_FUEL_REIMBURSEMENT'
		))																																																									FUEL_REIMBURSMENT_EUR


FROM SHIPMENT SH,
	RATE_GEO RG,
	X_LANE XL
	
	
WHERE SH.RATE_GEO_GID = RG.RATE_GEO_GID
AND RG.X_LANE_GID = XL.X_LANE_GID
AND TRUNC(SH.END_TIME) BETWEEN TRUNC(TO_DATE('2015-03-01','YYYY-MM-DD')) AND TRUNC(TO_DATE('2015-03-31','YYYY-MM-DD'))

AND SH.DOMAIN_NAME IN ('ULE','ULE/PR')
AND NOT EXISTS
	(SELECT 1
	 FROM SHIPMENT_REFNUM SH_REF_1
	 WHERE SH_REF_1.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_SHIPMENT_STREAM'
		   AND SH_REF_1.SHIPMENT_REFNUM_VALUE = 'SECONDARY'
		   AND SH_REF_1.SHIPMENT_GID = SH.SHIPMENT_GID)
