SELECT TEMP.SERVPROV_ID,
		TEMP.SERVPROV_NAME,
		TEMP.RESPONSIBLE_REGION,
		LISTAGG(TEMP.STREAM,'/') WITHIN GROUP (ORDER BY TEMP.SERVPROV_ID)					stream



FROM(
select DISTINCT sh.servprov_gid																								SERVPROV_ID,
(SELECT LOC.LOCATION_NAME
FROM LOCATION LOC
WHERE LOC.LOCATION_GID = SH.SERVPROV_GID
)																															SERVPROV_NAME,
(SELECT LOC_REF.LOCATION_REFNUM_VALUE
FROM LOCATION_REFNUM LOC_REF
WHERE LOC_REF.LOCATION_GID = SH.SERVPROV_GID
AND LOC_REF.LOCATION_REFNUM_QUAL_GID = 'ULE.ULE_RESPONSIBLE_REGION'
)																															RESPONSIBLE_REGION,


(SELECT sh_ref_1.shipment_Refnum_Value
		FROM shipment_refnum sh_ref_1
		WHERE sh_ref_1.shipment_Refnum_Qual_Gid = 'ULE.ULE_SHIPMENT_STREAM'
		   AND sh_ref_1.shipment_gid = sh.shipment_gid)																		STREAM
		   
		   
		   -- (SELECT LISTAGg(SH_REF_TEMP.shipment_Refnum_Value) WITHIN GROUP (ORDER BY SH_TEMP.SERVPROV_GID)
		   -- FROM SHIPMENT SH_TEMP,
		   -- SHIPMENT_REFNUM SH_REF_TEMP
		   -- WHERE SH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
		   -- AND SH_TEMP.SHIPMENT_GID	= SH_REF_TEMP.SHIPMENT_GID
		   -- SH_REF_TEMP.shipment_Refnum_Qual_Gid = 'ULE.ULE_SHIPMENT_STREAM'
		   -- AND SH_TEMP.SERVPROV_GID = SH.SERVPROV_GID
		   
		   
		   -- )
		   
		   





from shipment sh


where 

to_char(sh.end_time,'YYYY') = '2015'
AND SH.SERVPROV_GID NOT LIKE 'ULE.X%'
AND SH.SERVPROV_GID NOT LIKE 'ULE. X%'
AND SH.SERVPROV_GID NOT LIKE 'ULE.V%'
AND SH.SERVPROV_GID NOT IN ('ULE.SPOT','ULE.TSP_CUSTOMER_PICKUP')
AND SH.SERVPROV_GID NOT LIKE '%FTI_DEFAULT%'


AND SH.SERVPROV_GID IS NOT NULL
) TEMP

GROUP BY 
TEMP.SERVPROV_ID,
		TEMP.SERVPROV_NAME,
		TEMP.RESPONSIBLE_REGION