SELECT SH.SHIPMENT_GID,
sh.servprov_gid,

(select loc.location_name
from location loc
where loc.location_gid = sh.servprov_gid
)																						servprov_name,

(SELECT SH_STAT.STATUS_VALUE_GID
FROM SHIPMENT_STATUS SH_STAT
WHERE SH_STAT.SHIPMENT_GID = SH.SHIPMENT_GID
AND SH_STAT.STATUS_TYPE_GID = 'ULE/PR.ENROUTE'


)																						ENROUTE_STATUS,
(SELECT SH_STAT.STATUS_VALUE_GID
FROM SHIPMENT_STATUS SH_STAT
WHERE SH_STAT.SHIPMENT_GID = SH.SHIPMENT_GID
AND SH_STAT.STATUS_TYPE_GID = 'ULE/PR.FINANCE'


)																						FINANCE_STATUS,
(SELECT SH_STAT.STATUS_VALUE_GID
FROM SHIPMENT_STATUS SH_STAT
WHERE SH_STAT.SHIPMENT_GID = SH.SHIPMENT_GID
AND SH_STAT.STATUS_TYPE_GID = 'ULE/PR.INVOICE_READY'


)																						INVOICE_STATUS,
(SELECT SH_STAT.STATUS_VALUE_GID
FROM SHIPMENT_STATUS SH_STAT
WHERE SH_STAT.SHIPMENT_GID = SH.SHIPMENT_GID
AND SH_STAT.STATUS_TYPE_GID = 'ULE/PR.SHIPMENT_COST'


)																						SH_COST_STATUS

/* orls.order_release_gid, */
/* CASE WHEN 
(SELECT SH_TEMP.SHIPMENT_GID
FROM SHIPMENT SH_TEMP,
VIEW_SHIPMENT_ORDER_RELEASE VORLS_TEMP,
	ORDER_RELEASE ORLS_TEMP

WHERE 1=1
AND SH_TEMP.SHIPMENT_GID = VORLS_TEMP.SHIPMENT_GID
AND ORLS_TEMP.ORDER_RELEASE_GID = VORLS_TEMP.ORDER_RELEASE_GID
AND ORLS_TEMP.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
AND SH_TEMP.SHIPMENT_TYPE_GID = 'HANDLING'
	
) IS NOT NULL THEN 'Y' ELSE 'N' END AS 										X_DOCK */



FROM SHIPMENT SH,
	VIEW_SHIPMENT_ORDER_RELEASE VORLS,
	ORDER_RELEASE ORLS



WHERE 1=1
AND SH.SHIPMENT_GID = VORLS.SHIPMENT_GID
AND ORLS.ORDER_RELEASE_GID = VORLS.ORDER_RELEASE_GID
/* AND SH.SHIPMENT_GID IN () */

and EXISTS
(SELECT SH_TEMP.SHIPMENT_GID
FROM SHIPMENT SH_TEMP,
VIEW_SHIPMENT_ORDER_RELEASE VORLS_TEMP,
	ORDER_RELEASE ORLS_TEMP
	
WHERE 1=1
AND SH_TEMP.SHIPMENT_GID = VORLS_TEMP.SHIPMENT_GID
AND ORLS_TEMP.ORDER_RELEASE_GID = VORLS_TEMP.ORDER_RELEASE_GID
AND ORLS_TEMP.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
AND SH_TEMP.SHIPMENT_TYPE_GID = 'HANDLING'
	
)
/* and 
(SELECT SH_STAT.STATUS_VALUE_GID
FROM SHIPMENT_STATUS SH_STAT
WHERE SH_STAT.SHIPMENT_GID = SH.SHIPMENT_GID
AND SH_STAT.STATUS_TYPE_GID = 'ULE/PR.SHIPMENT_COST'


) <> 'ULE/PR.SC_NO CHANGES ALLOWED' */