SELECT SH.SHIPMENT_GID	AS																														SH_ID,
		'ORDERLESS' AS 																															OR_ID,
		TO_CHAR(UTC.GET_LOCAL_DATE(SH.START_TIME,SH.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS') AS											SH_START_TIME,
		TO_CHAR(UTC.GET_LOCAL_DATE(SH.END_TIME,SH.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI:SS') AS 											SH_END_TIME,
		
		(SELECT LISTAGG(SHR_RA.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_RA.SHIPMENT_GID)																										
		FROM SHIPMENT_REFNUM SHR_RA 
		WHERE (SHR_RA.SHIPMENT_GID = SH.SHIPMENT_GID AND SHR_RA.SHIPMENT_REFNUM_QUAL_GID='ULE/PR.ULE_OR_REL_ATR')
		) AS 																																	RELEASE_ATTR,
		'N/A' AS 																																OR_INDICATOR,
		(
		SELECT LISTAGG(SHR_REGION.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SH_REGION.SHIPMENT_GID)
		FROM SHIPMENT SH_REGION
				LEFT OUTER JOIN SHIPMENT_REFNUM SHR_REGION ON (SH_REGION.SHIPMENT_GID = SHR_REGION.SHIPMENT_GID 
				AND SHR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION')
		WHERE
			SH_REGION.DOMAIN_NAME ='ULE/PR'
			AND	SH_REGION.SHIPMENT_GID = SH.SHIPMENT_GID
		) 	AS 																																	REGION,
		SH.SOURCE_LOCATION_GID AS																												SOURCE_LOC_ID,
		LOC_SOURCE.CITY AS 																														SOURCE_CITY,
		LOC_SOURCE.LOCATION_NAME AS 																											SOURCE_NAME,
		SH.DEST_LOCATION_GID AS																													DEST_LOC_ID,
		LOC_DEST.CITY AS 																														DESTINATION_CITY,
		LOC_DEST.LOCATION_NAME AS 																												DEST_NAME,
		(SH.SERVPROV_GID) AS 																													SERVICE_PROVIDER,
		
		(SELECT LOC_TSP.LOCATION_NAME
		FROM SHIPMENT SH_SERVPROV
		LEFT OUTER JOIN LOCATION LOC_TSP ON (LOC_TSP.LOCATION_GID = SH_SERVPROV.SERVPROV_GID)
		WHERE
			SH_SERVPROV.SHIPMENT_GID = SH.SHIPMENT_GID
		)AS 																																	SERVICE_PROVIDER_NAME,
		
		
		
		SU.TRANSPORT_HANDLING_UNIT_GID AS 																										TRANSPORT_HANDLING_UNIT,
		TO_CHAR(SH.TOTAL_SHIP_UNIT_COUNT,'9,999,999.99') AS 																							NUMBER_OF_PALLETS,
		LTRIM(TO_CHAR(SU.TOTAL_GROSS_WEIGHT_BASE*0.45359237,'999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')) AS 									GROSS_WEIGHT,
		(
		SELECT LISTAGG(SH_COND.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SH_COND.SHIPMENT_GID)
		FROM SHIPMENT_REFNUM SH_COND
		
		WHERE SH_COND.SHIPMENT_GID = SH.SHIPMENT_GID 
		AND SH_COND.SHIPMENT_REFNUM_QUAL_GID ='ULE.ULE_TRANSPORT_CONDITION'
		
		
		) AS 																																	TRANSPORT_COND,
		(
		SELECT LISTAGG(SH_CAT.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SH_CAT.SHIPMENT_GID)
		FROM SHIPMENT_REFNUM SH_CAT
		
		WHERE SH_CAT.SHIPMENT_GID = SH.SHIPMENT_GID 
		AND SH_CAT.SHIPMENT_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_CATEGORY'
		
		
		) AS 																																	CATEGORY,
		SH.IS_HAZARDOUS AS 																														HAZARDOUS,
		'N/A' AS																																SPECIAL_ORDER,
		(SELECT LISTAGG(SHR_STAND.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_STAND.SHIPMENT_GID)
		FROM SHIPMENT_REFNUM SHR_STAND
		WHERE SHR_STAND.SHIPMENT_GID = SH.SHIPMENT_GID AND SHR_STAND.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_STANDBY_TRAILER'
		
		) AS 																																	STAND_TRAILER,
		
		'N/A' AS 																																EXPRESS,
		SH.INCO_TERM_GID AS 																													INCOTERM,
		'N/A' AS 																																IS_MULTISTOP,
		'N/A' AS																																STATUS,
		SH.INSERT_USER AS 																														ORLS_INSERT_USER,
		SH.DOMAIN_NAME AS																														ORLS_DOMAIN_NAME,
		SH.INDICATOR AS 																														SH_INDICATOR,
		(
		SELECT LISTAGG(SHS_SECURE.STATUS_VALUE_GID,'|') WITHIN GROUP (ORDER BY SHS_SECURE.SHIPMENT_GID)
		FROM SHIPMENT_STATUS SHS_SECURE
		
		WHERE SH.SHIPMENT_GID = SHS_SECURE.SHIPMENT_GID 
				AND SHS_SECURE.STATUS_TYPE_GID IN ('ULE/PR.SECURE RESOURCES')
		
		
		) AS 																																	SECURE_RES_STATUS,

		'N/A' AS 																																OR_PO_NUM,
		'N/A' AS																																OR_DN_NUM,
		'"'||(SELECT LISTAGG(SHR_PO.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_PO.SHIPMENT_GID)
		FROM SHIPMENT_REFNUM SHR_PO 
		WHERE SHR_PO.SHIPMENT_GID = SH.SHIPMENT_GID AND SHR_PO.SHIPMENT_REFNUM_QUAL_GID = 'ULE.PO'
		)||'"' AS 																																SH_PO,
		'"'||(SELECT LISTAGG(SHR_DN.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_DN.SHIPMENT_GID)
		FROM SHIPMENT_REFNUM SHR_DN
		WHERE SHR_DN.SHIPMENT_GID = SH.SHIPMENT_GID AND SHR_DN.SHIPMENT_REFNUM_QUAL_GID = 'ULE.DN'
		)||'"' AS 																																SH_DN,
		
		
		'"'||(SELECT LISTAGG(SHR_PLATE.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_PLATE.SHIPMENT_GID)
		FROM SHIPMENT_REFNUM SHR_PLATE 
		WHERE SHR_PLATE.SHIPMENT_GID = SH.SHIPMENT_GID AND SHR_PLATE.SHIPMENT_REFNUM_QUAL_GID = 'ULE.TRUCK PLATE'
		
		)||'"' AS TRUCK_PLATE,
		'"'||(SELECT LISTAGG(SHR_TRAILER.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_TRAILER.SHIPMENT_GID)
		FROM SHIPMENT_REFNUM SHR_TRAILER 
		WHERE (SHR_TRAILER.SHIPMENT_GID = SH.SHIPMENT_GID AND SHR_TRAILER.SHIPMENT_REFNUM_QUAL_GID = 'TRAILER')
		
		)||'"' AS TRAILER_NUMBER,
		'N/A' AS 																																EARLY_PICKUP_DATE,
		'N/A' AS 																																LATE_PICKUP_DATE,
		'N/A' AS 																																EARLY_DELIVERY_DATE,
		'N/A' AS 																																LATE_DELIVERY_DATE,
		
		
		SS.STOP_NUM AS 																															STOP_NUM,
		SS.STOP_TYPE AS																																	STOP_TYPE,
		SS.LOCATION_GID AS																														APP_LOCATION,
		(CASE WHEN SS.STOP_TYPE ='D' THEN 
		(
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_TYPE ='P' THEN (
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				AND APP_LOAD_T.INSERT_DATE = (SELECT DISTINCT 
        MAX(APP_LOAD_T_TEMP.INSERT_DATE)
        FROM APPOINTMENT APP_LOAD_T_TEMP
        WHERE APP_LOAD_T_TEMP.OBJECT_GID = APP_LOAD_T.OBJECT_GID
		AND	APP_LOAD_T_TEMP.STOP_NUM = APP_LOAD_T.STOP_NUM)
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_NUM ='1' THEN (
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				AND APP_LOAD_T.INSERT_DATE = (SELECT DISTINCT 
        MAX(APP_LOAD_T_TEMP.INSERT_DATE)
        FROM APPOINTMENT APP_LOAD_T_TEMP
        WHERE APP_LOAD_T_TEMP.OBJECT_GID = APP_LOAD_T.OBJECT_GID
		AND	APP_LOAD_T_TEMP.STOP_NUM = APP_LOAD_T.STOP_NUM)
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_NUM ='2' THEN 
		(
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		ELSE NULL
		END
		) AS 																																			APP_START,
		
		(CASE WHEN SS.STOP_TYPE ='D' THEN 
		(
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_END_TIME,SH.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_TYPE ='P' THEN (
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_END_TIME,SH.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				AND APP_LOAD_T.INSERT_DATE = (SELECT DISTINCT 
        MAX(APP_LOAD_T_TEMP.INSERT_DATE)
        FROM APPOINTMENT APP_LOAD_T_TEMP
        WHERE APP_LOAD_T_TEMP.OBJECT_GID = APP_LOAD_T.OBJECT_GID
		AND	APP_LOAD_T_TEMP.STOP_NUM = APP_LOAD_T.STOP_NUM)
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_NUM ='1' THEN (
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_END_TIME,SH.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				AND APP_LOAD_T.INSERT_DATE = (SELECT DISTINCT 
        MAX(APP_LOAD_T_TEMP.INSERT_DATE)
        FROM APPOINTMENT APP_LOAD_T_TEMP
        WHERE APP_LOAD_T_TEMP.OBJECT_GID = APP_LOAD_T.OBJECT_GID
		AND	APP_LOAD_T_TEMP.STOP_NUM = APP_LOAD_T.STOP_NUM)
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_NUM ='2' THEN 
		(
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_END_TIME,SH.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		ELSE NULL
		END
		) AS 																																			APP_END,
		(
		SELECT LISTAGG(LR_LOAD_T.LOCATION_RESOURCE_NAME,'|') 
		WITHIN GROUP (ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				AND APP_LOAD_T.INSERT_DATE = (SELECT DISTINCT 
        MAX(APP_LOAD_T_TEMP.INSERT_DATE)
        FROM APPOINTMENT APP_LOAD_T_TEMP
        WHERE APP_LOAD_T_TEMP.OBJECT_GID = APP_LOAD_T.OBJECT_GID
		AND	APP_LOAD_T_TEMP.STOP_NUM = APP_LOAD_T.STOP_NUM)
				/* AND	(SH.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)	AS 																																			APP_DOCK,
		TO_CHAR(UTC.GET_LOCAL_DATE(SS.PLANNED_ARRIVAL,SS.LOCATION_GID),'YYYY-MM-DD HH24:MI') AS 														PLANNED_ARRIVAL,
		
		(CASE WHEN SS.STOP_TYPE ='P' THEN 
			TO_CHAR(UTC.GET_LOCAL_DATE(SH.START_TIME,SH.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI')
		WHEN SS.STOP_TYPE ='D' THEN
			TO_CHAR(UTC.GET_LOCAL_DATE(SH.END_TIME,SH.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI')
		END) AS																																			LATEST_PICK_DEL_DATE,
		(SELECT SHS_STATUS_CANC.STATUS_VALUE_GID
		FROM shipment_status SHS_STATUS_CANC 
		where SHS_STATUS_CANC.SHIPMENT_GID = sh.SHIPMENT_GID 
		AND SHS_STATUS_CANC.STATUS_TYPE_GID = 'ULE/PR.TRANSPORT CANCELLATION'
		)																																				CANCELLATION_STATUS,
		(SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ss.location_gid),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID = 'ULE/PR.0005'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = 1
			  
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID =  'ULE/PR.0005' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = SS.STOP_NUM
			   
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   ))  																																		REGISTRATION_IN,
		(SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ss.location_gid),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID = 'ULE/PR.0008'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = 1
			  
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID =  'ULE/PR.0008' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = SS.STOP_NUM
			   
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   ))  																																		REGISTRATION_OUT,
			   (SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ss.location_gid),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID = 'ULE/PR.0006'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = 1
			  
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID =  'ULE/PR.0006' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = SS.STOP_NUM
			   
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   ))  																																		HANDLING_START,
			   (SELECT DISTINCT
		listagg(TO_CHAR(UTC.GET_LOCAL_DATE(IESH_EVENT_DELIVER.EVENTDATE,ss.location_gid),'YYYY-MM-DD HH24:MI:SS'),',') within group (order by sh.shipment_gid)
        FROM   SS_STATUS_HISTORY SSH,
              IE_SHIPMENTSTATUS IESH_EVENT_DELIVER 
        WHERE  IESH_EVENT_DELIVER.STATUS_CODE_GID = 'ULE/PR.0007'
            
               AND SSH.SHIPMENT_GID = SH.SHIPMENT_GID
			   AND SSH.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER.I_TRANSACTION_NO
			   AND SSH.SHIPMENT_STOP_NUM = 1
			  
			   AND IESH_EVENT_DELIVER.INSERT_DATE = (SELECT DISTINCT MAX(IESH_EVENT_DELIVER_TEMP.INSERT_DATE)
        FROM   SS_STATUS_HISTORY SSH_TEMP,
               IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 

        WHERE  IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID =  'ULE/PR.0007' 
               AND SSH_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
			   and SSH_TEMP.SHIPMENT_STOP_NUM = SS.STOP_NUM
			   
			   AND SSH_TEMP.I_TRANSACTION_NO = 
                                 IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO 
			   ))  																																		HANDLING_end
		


FROM
		SHIPMENT SH
				LEFT OUTER JOIN SHIPMENT_STOP SS ON	(SS.SHIPMENT_GID = SH.SHIPMENT_GID)
				LEFT OUTER JOIN SHIPMENT_STOP_D SSD ON (SSD.SHIPMENT_GID = SS.SHIPMENT_GID AND SSD.STOP_NUM = SS.STOP_NUM)
				LEFT OUTER JOIN S_SHIP_UNIT SSU ON (SSD.S_SHIP_UNIT_GID = SSU.S_SHIP_UNIT_GID)
				LEFT OUTER JOIN S_SHIP_UNIT_LINE SSUL ON (SSU.S_SHIP_UNIT_GID = SSUL.S_SHIP_UNIT_GID)
				LEFT OUTER JOIN SHIP_UNIT SU ON (SU.SHIP_UNIT_GID = SSU.SHIP_UNIT_GID),
				/* LEFT OUTER JOIN SHIP_UNIT_EQUIP_REF_UNIT_JOIN SUERUJ_PALLET ON (SU.SHIP_UNIT_GID = SUERUJ_PALLET.SHIP_UNIT_GID), */
				
		LOCATION LOC_SOURCE,
		LOCATION LOC_DEST

WHERE 1=1	
	AND SH.DOMAIN_NAME IN ('ULE/PR','SERVPROV','ULE','UGO')
	AND NOT EXISTS
	(SELECT 1
	 FROM shipment_refnum sh_ref_1
	 WHERE sh_ref_1.Shipment_Refnum_Qual_Gid = 'ULE.ULE_SHIPMENT_STREAM'
		   AND sh_ref_1.Shipment_Refnum_Value = 'SECONDARY'
		   AND sh_ref_1.SHIPMENT_GID = SH.SHIPMENT_GID)
	AND	SH.SHIPMENT_TYPE_GID IN ('APPOINTMENT')
	
	AND NOT EXISTS(SELECT 1
	FROM shipment_refnum
	WHERE shipment_gid = Sh.shipment_gid
	AND shipment_refnum_qual_gid = 'ULE.ULE_SHIPMENT_STREAM'
	AND shipment_refnum_value = 'SECONDARY')
	
	AND	LOC_SOURCE.LOCATION_GID = SH.SOURCE_LOCATION_GID
	AND	LOC_DEST.LOCATION_GID = SH.DEST_LOCATION_GID
	
/* 	AND	SH.START_TIME BETWEEN TO_DATE(NVL(:START_TIME, TO_CHAR(TRUNC((TRUNC(SYSDATE,'MM')-1),'MM'),:P_DATE_TIME_FORMAT)),:P_DATE_TIME_FORMAT) AND 
	TO_DATE(NVL(:END_TIME,TO_CHAR(TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,1))+1),:P_DATE_TIME_FORMAT)),:P_DATE_TIME_FORMAT) */

	AND TRUNC(SH.START_TIME) BETWEEN TO_DATE('2015-11-01','YYYY-MM-DD') AND  TO_DATE('2015-11-30','YYYY-MM-DD')