SELECT TEMP.SH_END_TIME,
TEMP.SHIPMENT_GID,
	TEMP.SOURCE_CITY,
	TEMP.SOURCE_POSTAL_CODE,
	TEMP.SOURCE_LOC_NAME,
	TEMP.DEST_CITY,
	TEMP.DEST_POSTAL_CODE,
	TEMP.DEST_LOC_NAME,
	TEMP.ORDER_RELEASE_GID,
	TEMP.TRANSPORT_HANDLING_UNIT_GID,
	SUM(TEMP.SHIP_UNIT_COUNT)

FROM(
select 
	TO_CHAR(SH.END_TIME,'YYYY-MM-DD') SH_END_TIME,
	SH.SHIPMENT_GID,
	SOURCE_LOC.CITY  			SOURCE_CITY,
	SOURCE_LOC.POSTAL_CODE			SOURCE_POSTAL_CODE,
	SOURCE_LOC.LOCATION_NAME		SOURCE_LOC_NAME,
	DEST_LOC.CITY				DEST_CITY,
	DEST_LOC.POSTAL_CODE 		DEST_POSTAL_CODE,
	DEST_LOC.LOCATION_NAME		DEST_LOC_NAME,
	OM.ORDER_RELEASE_GID,
	SU.SHIP_UNIT_GID,
	SU.TRANSPORT_HANDLING_UNIT_GID,
	SU.SHIP_UNIT_COUNT


from shipment sh,
	order_movement om,
	SHIP_UNIT SU,
	 SHIP_UNIT_LINE SUL,
	 S_SHIP_UNIT_LINE SSUL,
	 LOCATION SOURCE_LOC,
	 LOCATION DEST_LOC
	 
	 
where 
	SU.ORDER_RELEASE_GID = om.ORDER_RELEASE_GID
 and om.shipment_gid = sh.shipment_gid
 AND SUL.SHIP_UNIT_GID = SU.SHIP_UNIT_GID
 AND SSUL.SHIP_UNIT_GID = SUL.SHIP_UNIT_GID
 AND SOURCE_LOC.LOCATION_GID = SH.SOURCE_LOCATION_GID
 AND DEST_LOC.LOCATION_GID = SH.DEST_LOCATION_GID
 and sh.source_location_gid in ('ULE.V207503','ULE.V207480')
 AND TO_CHAR(SH.INSERT_DATE,'YYYY') = '2015'
AND
		(SELECT sh_ref_1.shipment_Refnum_Value
		FROM shipment_refnum sh_ref_1
		WHERE sh_ref_1.shipment_Refnum_Qual_Gid = 'ULE.ULE_SHIPMENT_STREAM'
		   AND sh_ref_1.shipment_gid = sh.shipment_gid)	= 'SECONDARY'
) TEMP
GROUP BY 
TEMP.SH_END_TIME,
TEMP.SHIPMENT_GID,
	TEMP.SOURCE_CITY,
	TEMP.SOURCE_POSTAL_CODE,
	TEMP.SOURCE_LOC_NAME,
	TEMP.DEST_CITY,
	TEMP.DEST_POSTAL_CODE,
	TEMP.DEST_LOC_NAME,
	TEMP.ORDER_RELEASE_GID,
	TEMP.TRANSPORT_HANDLING_UNIT_GID