SELECT TEMP.SOURCE_LOCATION_ID,
		TEMP.DESTINATION_LOCATION_ID,
		SUM(TEMP.PRICE_PALLET_1)/COUNT(TEMP.PRICE_PALLET_1) 																		SUM_PAL1,
		SUM(TEMP.PRICE_PALLET_2)/COUNT(TEMP.PRICE_PALLET_2) 																		SUM_PAL2,
		SUM(TEMP.PRICE_PALLET_3)/COUNT(TEMP.PRICE_PALLET_3) 																		SUM_PAL3,
		SUM(TEMP.PRICE_PALLET_4)/COUNT(TEMP.PRICE_PALLET_4) 																		SUM_PAL4,
		SUM(TEMP.PRICE_PALLET_5)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL5,
		SUM(TEMP.PRICE_PALLET_6)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL6,
		SUM(TEMP.PRICE_PALLET_7)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL7,
		SUM(TEMP.PRICE_PALLET_8)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL8,
		SUM(TEMP.PRICE_PALLET_9)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL9,
		SUM(TEMP.PRICE_PALLET_10)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL10,
		SUM(TEMP.PRICE_PALLET_11)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL11,
		SUM(TEMP.PRICE_PALLET_12)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL12,
		SUM(TEMP.PRICE_PALLET_13)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL13,
		SUM(TEMP.PRICE_PALLET_14)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL14,
		SUM(TEMP.PRICE_PALLET_15)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL15,
		SUM(TEMP.PRICE_PALLET_16)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL16,
		SUM(TEMP.PRICE_PALLET_17)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL17,
		SUM(TEMP.PRICE_PALLET_18)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL18,
		SUM(TEMP.PRICE_PALLET_19)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL19,
		SUM(TEMP.PRICE_PALLET_20)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL20,
		SUM(TEMP.PRICE_PALLET_21)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL21,
		SUM(TEMP.PRICE_PALLET_22)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL22,
		SUM(TEMP.PRICE_PALLET_23)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL23,
		SUM(TEMP.PRICE_PALLET_24)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL24,
		SUM(TEMP.PRICE_PALLET_25)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL25,
		SUM(TEMP.PRICE_PALLET_26)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL26,
		SUM(TEMP.PRICE_PALLET_27)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL27,
		SUM(TEMP.PRICE_PALLET_28)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL28,
		SUM(TEMP.PRICE_PALLET_29)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL29,
		SUM(TEMP.PRICE_PALLET_30)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL30,
		SUM(TEMP.PRICE_PALLET_31)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL31,
		SUM(TEMP.PRICE_PALLET_32)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL32,
		SUM(TEMP.PRICE_PALLET_33)/COUNT(TEMP.PRICE_PALLET_5) 																		SUM_PAL33
		
		


FROM(
SELECT XL.X_LANE_XID																																	X_LANE_XID,
	'"'||(SELECT LISTAGG(LOC_SOURCE.CITY,'/') WITHIN GROUP (ORDER BY XL.X_LANE_GID)
				FROM LOCATION LOC_SOURCE
				WHERE LOC_SOURCE.LOCATION_GID = XL.SOURCE_LOCATION_GID
		 )||'-'||
		(SELECT LISTAGG(LOC_DEST.CITY,'/') WITHIN GROUP (ORDER BY XL.X_LANE_GID)
			FROM LOCATION LOC_DEST
			WHERE LOC_DEST.LOCATION_GID = XL.DEST_LOCATION_GID
		)||'"' AS 																																	LANE_NAME,
		CASE WHEN XL.SOURCE_LOCATION_GID IS NOT NULL THEN SUBSTR(XL.SOURCE_LOCATION_GID,INSTR(LTI.SERVPROV_GID,'.')+1)
			ELSE substr(XL.SOURCE_REGION_GID,INSTR(LTI.SERVPROV_GID,'.')+1)
		END AS 																																		SOURCE_LOCATION_ID,
		CASE WHEN XL.DEST_LOCATION_GID IS NOT NULL THEN substr(XL.DEST_LOCATION_GID,INSTR(LTI.SERVPROV_GID,'.')+1)
			ELSE substr(XL.DEST_REGION_GID,INSTR(LTI.SERVPROV_GID,'.')+1)
		END AS 																																		DESTINATION_LOCATION_ID,
		SUBSTR(LTI.SERVPROV_GID,INSTR(LTI.SERVPROV_GID,'.')+1) 																						SERVICE_PROVIDER_ID,
		'"'||loc_tsp.location_name||'"'																														SERVPROV_NAME,
		rpt_general.f_remove_domain(CASE
							WHEN RGC.LEFT_OPERAND1 = 'SHIPMENT.EQUIPMENT.EQUIPMENT_GROUP_GID' THEN RGC.LOW_VALUE1
							ELSE
								CASE
									WHEN RGC.LEFT_OPERAND2 = 'SHIPMENT.EQUIPMENT.EQUIPMENT_GROUP_GID' THEN RGC.LOW_VALUE2
									ELSE 
										CASE
											WHEN RGC.LEFT_OPERAND3 = 'SHIPMENT.EQUIPMENT.EQUIPMENT_GROUP_GID' THEN RGC.LOW_VALUE3
											ELSE 
												CASE
													WHEN RGC.LEFT_OPERAND4 = 'SHIPMENT.EQUIPMENT.EQUIPMENT_GROUP_GID' THEN RGC.LOW_VALUE4
												ELSE ' '
												END
										END
								END
		END)					 																													EQUIPMENT_TYPE,
		case when 
		(CASE
							WHEN RGC.LEFT_OPERAND1 = 'SHIPMENT.EQUIPMENT.EQUIPMENT_GROUP_GID' THEN RGC.LOW_VALUE1
							ELSE
								CASE
									WHEN RGC.LEFT_OPERAND2 = 'SHIPMENT.EQUIPMENT.EQUIPMENT_GROUP_GID' THEN RGC.LOW_VALUE2
									ELSE 
										CASE
											WHEN RGC.LEFT_OPERAND3 = 'SHIPMENT.EQUIPMENT.EQUIPMENT_GROUP_GID' THEN RGC.LOW_VALUE3
											ELSE 
												CASE
													WHEN RGC.LEFT_OPERAND4 = 'SHIPMENT.EQUIPMENT.EQUIPMENT_GROUP_GID' THEN RGC.LOW_VALUE4
												ELSE ' '
												END
										END
								END
		END) in ('ULE.13_45M SWAP BODY-33_26 PAL','ULE.13_6M BOX TRAILER-33_26 PAL_28T_A','ULE.13_6M BOX TRAILER-33_26 PAL-A','ULE.13_6M CURTAIN SIDE TRAILER-33_26 PAL','ULE.13_6M CURTAIN SIDE TRAILER-33_26 PAL_1','ULE.13_6M CURTAIN SIDE TRAILER-34_26 PAL','ULE.13_6M DOUBLE DECK-2 WIN TYPE-50_40 PAL-A-NEW','ULE.13_6M DOUBLE DECK-2 WIN TYPE-52_40 PAL-A','ULE.13_6M DOUBLE DECKER TRAILER-DHL UK-50_44 PAL','ULE.13_6M DOUBLE DECK-REMOV FLOOR-66_52 PAL-A','ULE.13_6M ISOTHERMAL BOX TRAILER-33_26 PAL','ULE.13_6M MEGA TRAILER-33_26 PAL','ULE.13_6M RAIL CAR-33_30 PAL','ULE.13_6M RAIL CAR-38_30 PAL','ULE.13_6M TILT TRAILER-33_26 PAL','ULE.13_6M TILT TRAILER-33_26 PAL_1','ULE.14_3M SWAP BODY-DOUBLE SET-36_28 PAL','ULE.14_4M LONGER TRAILER-DHL TYPE 1-28 IND PAL','ULE.15_34M SWAP BODY-38_28 PAL','ULE.15_4M LONGER TRAILER-DHL TYPE 2-30 IND PAL','ULE.15_4M RAIL CAR-42_30 PAL','ULE.15_6M ROAD-TRAIN DOUBLE-STACK-76_56 PAL','ULE.15_6M ROAD-TRAIN DOUBLE-STACK-81_60 PAL','ULE.15_6M ROAD-TRAIN-38_30 PAL','ULE.16M RAIL CAR-44_30 PAL','ULE.21_3M BOX ROAD-TRAIN-48_38 PAL-A','ULE.21_3M BOX ROAD-TRAIN-52_40 PAL-A','ULE.21_3M TILT ROAD-TRAIN-52_40 PAL','ULE.40FT PALLETWIDE CTR-30_24 PAL','ULE.45FT CTR-32_26 PAL','ULE.45FT PALLETWIDE CTR-33_26 PAL_A','ULE.7_15M SWAP BODY-18_14 PAL','ULE.8_2M TILT LINK TRAILER-20_16PAL','ULE.BARGE_AMB_1299_MT','ULE.COASTER_BARGE_AMB_6513_MT','ULE.DRY_20CO-11_10 PAL','ULE.DRY_40CO-24_21 PAL','ULE.DRY_40HC-24_21 PAL','ULE.LTL GENERIC AMB','ULE.SILO-UP TO 28T','ULE.SMALL TRUCK-UP TO 1_5T-8_6 PAL-A','ULE.SMALL TRUCK-UP TO 3_5T-15_12 PAL-A','ULE.SMALL TRUCK-UP TO 5_5T-18_14 PAL-A','ULE.TANKER-UP TO 33T MULTICOMPARTMENT-A','ULE.TANKER-UP TO 33T-A','ULE.TANKER-UP TO 35T-A','ULE.14_2M RAIL CAR-40_28 PAL','ULE.15_6M ROAD-TRAIN-38_30 PAL (23T)','ULE.30_8M RAIL CAR-84_66 PAL (45T)','ULE.13_6M TILT TRAILER-34_26 PAL (26T)','ULE.13_6M CURTAIN SIDE TRAILER-34_26 PAL NL','ULE.LTL GENERIC AMB NL','ULE.13_6M TILT TRAILER-33_26 PAL _NORDICS','ULE.13_6M ISOTHERMAL BOX TRAILER-33_26 PAL_NORDICS','ULE.30_8M RAIL-CAR-84_66 PAL','ULE.13_6M DOUBLE DECK-REMOV FLOOR-66_52 PAL_NORDICS','ULE.30_8M RAIL-CAR-84_66 PAL','ULE.13_6M CURTAIN SIDE TRAILER-33_26 PAL_NORDICS','ULE.13_6M BOX TRAILER-33_26 PAL-A NL','ULE.13_6M CURTAIN SIDE TRAILER-104_82 PAL','ULE.122M TRAIN_3_WAGONS_252_198 PAL','ULE.21_3M BOX ROAD-TRAIN-52_40 PAL-NORDICS_AMB','ULE.163M TRAIN_4_WAGONS_336_264 PAL','ULE.81M TRAIN_2_WAGONS_168_132 PAL','ULE.13_6M TILT TRAILER-33_26 PAL 28T','ULE.13_6M DOUBLE DECK REMOV FLOOR-66_52 PAL','ULE.13_6M DOUBLE DECK 2 WIN TYPE-52_40 PAL','ULE.MULTI-BULK COMP','ULE.15_6M ROAD-TRAIN-38_30 PAL-29T','ULE.13_6M DOUBLE DECK-2 WIN TYPE-54_40 PAL-A','ULE.15_6M ROAD-TRAIN-38_30 PAL (29T)') 
		then 'AMB'	
		when 
		(CASE
							WHEN RGC.LEFT_OPERAND1 = 'SHIPMENT.EQUIPMENT.EQUIPMENT_GROUP_GID' THEN RGC.LOW_VALUE1
							ELSE
								CASE
									WHEN RGC.LEFT_OPERAND2 = 'SHIPMENT.EQUIPMENT.EQUIPMENT_GROUP_GID' THEN RGC.LOW_VALUE2
									ELSE 
										CASE
											WHEN RGC.LEFT_OPERAND3 = 'SHIPMENT.EQUIPMENT.EQUIPMENT_GROUP_GID' THEN RGC.LOW_VALUE3
											ELSE 
												CASE
													WHEN RGC.LEFT_OPERAND4 = 'SHIPMENT.EQUIPMENT.EQUIPMENT_GROUP_GID' THEN RGC.LOW_VALUE4
												ELSE ' '
												END
										END
								END
		END) in ('ULE.13_6M BOX TRAILER-33_26 PAL','ULE.13_6M BOX TRAILER-33_26 PAL 28T','ULE.13_6M DOUBLE DECK-2 WIN TYPE-52_40 PAL','ULE.13_6M DOUBLE DECK-REMOV FLOOR-66_52 PAL','ULE.21_3M BOX ROAD-TRAIN-52_40 PAL','ULE.45FT PALLETWIDE CTR-33_26 PAL','ULE.BARGE_TEMPC_2333_MT','ULE.COASTER_BARGE_TEMPC_6513_MT','ULE.LTL GENERIC TEMP_C','ULE.REF_20CO-10_9 PAL','ULE.REF_40CO-23_20 PAL','ULE.REF_40HC-23_20 PAL','ULE.SMALL TRUCK-UP TO 1_5T-8_6 PAL','ULE.SMALL TRUCK-UP TO 3_5T-15_12 PAL','ULE.SMALL TRUCK-UP TO 5_5T-18_14 PAL','ULE.TANKER-UP TO 33T','ULE.TANKER-UP TO 33T MULTICOMPARTMENT','ULE.TANKER-UP TO 35T','ULE.13_6M BOX TRAILER-33_26 PAL_NORDICS','ULE.21_3M BOX ROAD-TRAIN-52_40 PAL-NORD','ULE.13_6M DOUBLE DECK-REMOV FLOOR-66_52 PAL [26T]','ULE.13_6M DOUBLE DECK-2 WIN TYPE-54_40 PAL','ULE.LTL GENERIC TEMP NL') 
		then 'TEMPC'
		
		
		
		
		END AS																																					AMB_TEMPC,
		
		(SELECT listagg(NVL(LA_AUTO_ACC.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)
				FROM LANE_ATTRIBUTE LA_AUTO_ACC
				WHERE
				xl.X_LANE_GID = LA_AUTO_ACC.X_LANE_GID 
				AND LA_AUTO_ACC.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_AUTO_ACCEPT_TENDER'
		) AS 																																		ULE_AUTO_ACCEPT_TENDER,
		(SELECT listagg(NVL(LA_AUTO_TEN.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)
				FROM LANE_ATTRIBUTE LA_AUTO_TEN
				WHERE
				xl.X_LANE_GID = LA_AUTO_TEN.X_LANE_GID 
				AND LA_AUTO_TEN.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_AUTO_TENDER'
		) AS 																																		ULE_AUTO_TENDER,
		(SELECT listagg(NVL(LA_SENDASS.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				FROM LANE_ATTRIBUTE LA_SENDASS
				WHERE
				xl.X_LANE_GID = LA_SENDASS.X_LANE_GID 
				AND LA_SENDASS.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_SEND_ASSIGNMENT'
		) AS 																																		SEND_ASSIGMENT,
		(SELECT listagg(NVL(LA_DGCLASS.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				FROM LANE_ATTRIBUTE LA_DGCLASS
				WHERE
				xl.X_LANE_GID = LA_DGCLASS.X_LANE_GID 
				AND LA_DGCLASS.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_DANGEROUS_CLASS'
		) AS 																																		DANG_CLASS,
	
		(SELECT listagg(NVL(LA_INOUT.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				FROM LANE_ATTRIBUTE LA_INOUT
				WHERE
				xl.X_LANE_GID = LA_INOUT.X_LANE_GID 
				AND LA_INOUT.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_IN-OUT_LANE'
		) AS 																																		IN_OUT_LANE,
				
		(SELECT listagg(NVL(LA_CLASSIF1.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				FROM LANE_ATTRIBUTE LA_CLASSIF1
				WHERE
				xl.X_LANE_GID = LA_CLASSIF1.X_LANE_GID 
				AND LA_CLASSIF1.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_LANE_CLASSIF_1'
		) AS 																																		LANE_CLASSIF_1,
		(SELECT listagg(NVL(LA_CLASSIF2.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				FROM LANE_ATTRIBUTE LA_CLASSIF2
				WHERE
				xl.X_LANE_GID = LA_CLASSIF2.X_LANE_GID 
				AND LA_CLASSIF2.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_LANE_CLASSIF_2'
		) AS 																																		LANE_CLASSIF_2,
		(SELECT listagg(NVL(LA_MATCAT.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				FROM LANE_ATTRIBUTE LA_MATCAT
				WHERE
				xl.X_LANE_GID = LA_MATCAT.X_LANE_GID 
				AND LA_MATCAT.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_MAT_CATEG'
		) AS 																																		MAT_CAT,
		(SELECT listagg(NVL(LA_MID.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				FROM LANE_ATTRIBUTE LA_MID
				WHERE
				xl.X_LANE_GID = LA_MID.X_LANE_GID 
				AND LA_MID.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_MID_STOP'
		) AS 																																		MID_STOP,
		(SELECT listagg(NVL(LA_NOTIF.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				FROM LANE_ATTRIBUTE LA_NOTIF
				WHERE
				xl.X_LANE_GID = LA_NOTIF.X_LANE_GID 
				AND LA_NOTIF.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_NOTIFICATION_TIME_H'
		) AS 																																		NOTIFICATION_H,
		(select NVL(ST_TT_H.SERVICE_TIME_VALUE,0)/3600
		from SERVICE_TIME ST_TT_H
		where xl.X_LANE_GID = ST_TT_H.X_LANE_GID
		and ST_TT_H.RATE_SERVICE_GID = rg.RATE_SERVICE_GID
		)																																			TRANSIT_TIME_H,	
		RO.TRANSPORT_MODE_GID AS 																													TRANSPORT_MODE,
		(SELECT listagg(NVL(LA_TYPE.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				FROM LANE_ATTRIBUTE LA_TYPE
				WHERE
				xl.X_LANE_GID = LA_TYPE.X_LANE_GID 
				AND LA_TYPE.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_TRANSPORT_MODE'
		) AS 																													TRANSPORT_MODE_2,
		(SELECT listagg(NVL(LA_TYPE.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				FROM LANE_ATTRIBUTE LA_TYPE
				WHERE
				xl.X_LANE_GID = LA_TYPE.X_LANE_GID 
				AND LA_TYPE.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_TRANSPORT_TYPE'
		) AS 																																		TRANSPORT_TYPE,

		upper((SELECT listagg(NVL(LA_REGION.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				FROM LANE_ATTRIBUTE LA_REGION
				WHERE
				xl.X_LANE_GID = LA_REGION.X_LANE_GID 
				AND LA_REGION.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_REGION'
		)) AS 																																		REGION,

		(select listagg('"'||NVL(LR_TRANGE.REMARK_TEXT,' ')||'"','/') WITHIN GROUP (ORDER BY xl.X_LANE_GID)
				from LANE_REMARK LR_TRANGE
				where xl.X_LANE_GID = LR_TRANGE.X_LANE_GID
				and LR_TRANGE.REMARK_QUAL_GID ='ULE.ULE_LANE_TEMPERATURE_RANGE'
		) 																																			AS TEMPERATURE_RANGE,
		
		(select rgc_temp.CHARGE_AMOUNT
		from rate_geo_cost rgc_temp
		WHERE rgc_temp.RATE_GEO_COST_GROUP_GID = RGC.RATE_GEO_COST_GROUP_GID
		AND rgc_temp.CHARGE_ACTION = 'A'
		and rownum=1
		)																												CHARGE_AMOUNT,																						
		--RGC.CHARGE_AMOUNT,
		
		
		
		case when RGC.CHARGE_CURRENCY_GID is null then 
		(SELECT substr(listagg(RGCUB_PALLETS_1.CHARGE_AMOUNT_GID,'/') within group (order by RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID ),0,3)
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				and RGCUB_PALLETS_1.CHARGE_AMOUNT_GID is not null
				)
				
				
		else RGC.CHARGE_CURRENCY_GID end  																												CHARGE_CURRENCY_GID,
		(select listagg(CASE
					WHEN CAP_L.LIMIT IS NOT NULL THEN 'Y'
					ELSE ' '
				END,'/') within group (ORDER BY XL.x_lane_gid)
				from CAPACITY_GROUP CAP_G,
				CAPACITY_LIMIT CAP_L
				where CAP_G.CAPACITY_GROUP_GID = ro.CAPACITY_GROUP_GID
				and	CAP_L.CAPACITY_GROUP_GID = CAP_G.CAPACITY_GROUP_GID and CAP_L.x_lane_gid = xl.x_lane_gid
		)																																			CAP_LIMIT,
		(select listagg(CAP_L.LIMIT,'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				from CAPACITY_GROUP CAP_G,
				CAPACITY_LIMIT CAP_L
				where CAP_G.CAPACITY_GROUP_GID = ro.CAPACITY_GROUP_GID
				and	CAP_L.CAPACITY_GROUP_GID = CAP_G.CAPACITY_GROUP_GID and CAP_L.x_lane_gid = xl.x_lane_gid
		)																																			CAPACITY_LIMIT_WEEKLY,
		(SELECT listagg(RGR_DCAP.REMARK_TEXT,'/') within group (order by RG.RATE_GEO_GID)
				FROM RATE_GEO_REMARK RGR_DCAP
				WHERE RGR_DCAP.REMARK_QUALIFIER_GID ='ULE.ULE_DAILY_CAPACITY'
				AND	RGR_DCAP.RATE_GEO_GID = RG.RATE_GEO_GID
		)																																			CAPACITY_LIMIT_DAILY,
		TO_CHAR(RG.EFFECTIVE_DATE,'DD.MM.YYYY') AS 																									VALID_FROM,
		TO_CHAR(RG.EXPIRATION_DATE,'DD.MM.YYYY') AS 																								VALID_TO,
		CASE
					WHEN RGC.RATE_UNIT_BREAK_PROFILE_GID IS NOT NULL THEN 'LTL'
					ELSE 
						CASE WHEN RGC.LEFT_OPERAND1 = 'SHIPMENT.NUM_EQ_REF_UNITS' THEN
							CASE 
							WHEN RGC.OPER1_GID = 'EQ' THEN to_char(RGC.LOW_VALUE1)
							WHEN RGC.OPER1_GID = 'BETWEEN' THEN to_char(RGC.LOW_VALUE1 + 1)
							WHEN RGC.OPER1_GID = 'LE' THEN '1'
							ELSE 'ERROR'
						END
					WHEN RGC.LEFT_OPERAND2 = 'SHIPMENT.NUM_EQ_REF_UNITS' THEN
					CASE 
							WHEN RGC.OPER2_GID = 'EQ' THEN to_char(RGC.LOW_VALUE1)
							WHEN RGC.OPER2_GID = 'BETWEEN' THEN to_char(RGC.LOW_VALUE1 + 1)
							WHEN RGC.OPER2_GID = 'LE' THEN '1'
							ELSE 'ERROR'
						END
					WHEN RGC.LEFT_OPERAND3 = 'SHIPMENT.NUM_EQ_REF_UNITS' THEN
					CASE 
							WHEN RGC.OPER3_GID = 'EQ' THEN to_char(RGC.LOW_VALUE1)
							WHEN RGC.OPER3_GID = 'BETWEEN' THEN to_char(RGC.LOW_VALUE1 + 1)
							WHEN RGC.OPER3_GID = 'LE' THEN '1'
							ELSE 'ERROR'
						END	
					WHEN RGC.LEFT_OPERAND4 = 'SHIPMENT.NUM_EQ_REF_UNITS' THEN
					CASE 
							WHEN RGC.OPER4_GID = 'EQ' THEN to_char(RGC.LOW_VALUE1)
							WHEN RGC.OPER4_GID = 'BETWEEN' THEN to_char(RGC.LOW_VALUE1 + 1)
							WHEN RGC.OPER4_GID = 'LE' THEN '1'
							ELSE 'ERROR'
					END
						END
				END AS 																																MIN_PFS,
				CASE
					WHEN RGC.RATE_UNIT_BREAK_PROFILE_GID IS NOT NULL THEN 'LTL'
					ELSE 
						CASE
							WHEN RGC.OPER1_GID = 'EQ' THEN RGC.LOW_VALUE1
							WHEN RGC.OPER1_GID = 'BETWEEN' THEN RGC.HIGH_VALUE1
							WHEN RGC.OPER1_GID = 'LE' THEN RGC.LOW_VALUE1
							ELSE 'ERROR'
						END
				END AS 																																MAX_PFS,
				(select xl_att.LANE_ATTRIBUTE_VALUE
				from LANE_ATTRIBUTE xl_att
				where xl_att.LANE_ATTRIBUTE_DEF_GID = 'ULE.ULE_PALLET_TYPE'
				and xl_att.X_LANE_GID = xl.X_LANE_GID
				)																																					PALLET_TYPE,
				NVL((SELECT r_geo_rem.REMARK_TEXT
				FROM RATE_GEO_REMARK r_geo_rem
				WHERE r_geo_rem.REMARK_QUALIFIER_GID = 'ULE.ULE_SHIPMENTS_PER_YEAR' AND RG.RATE_GEO_GID = r_geo_rem.RATE_GEO_GID),'-')								AS SHIPMENTS_PER_YEAR,
				CASE
							WHEN RGC.LOW_VALUE1 = 'ULE.ULE_EXPRESS_BY_CUSTOMER' THEN 'Y'
							ELSE
								CASE
									WHEN RGC.LOW_VALUE2 = 'ULE.ULE_EXPRESS_BY_CUSTOMER' THEN 'Y'
									ELSE 
										CASE
											WHEN RGC.LOW_VALUE3 = 'ULE.ULE_EXPRESS_BY_CUSTOMER' THEN 'Y'
											ELSE 
												CASE
													WHEN RGC.LOW_VALUE4 = 'ULE.ULE_EXPRESS_BY_CUSTOMER' THEN 'Y'
												ELSE 'N'
												END
										END
								END
				END AS 																																				EXPRESS,

				CASE
							WHEN RGC.LOW_VALUE1 = 'ULE.ULE_STANDBY_TRAILER' THEN 'Y'
							ELSE
								CASE
									WHEN RGC.LOW_VALUE2 = 'ULE.ULE_STANDBY_TRAILER' THEN 'Y'
									ELSE 
										CASE
											WHEN RGC.LOW_VALUE3 = 'ULE.ULE_STANDBY_TRAILER' THEN 'Y'
											ELSE 
												CASE
													WHEN RGC.LOW_VALUE4 = 'ULE.ULE_STANDBY_TRAILER' THEN 'Y'
												ELSE 'N'
												END
										END
								END
				END AS 																																		STAND_TRAILER,
				
				-------------------------------------------------------------------------------------------------------------
(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_1'
				) AS 																																		PRICE_PALLET_1,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_2'
				) AS 																																		PRICE_PALLET_2,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_3'
				) AS 																																		PRICE_PALLET_3,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_4'
				) AS 																																		PRICE_PALLET_4,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_5'
				) AS 																																		PRICE_PALLET_5,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_6'
				) AS 																																		PRICE_PALLET_6,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_7'
				) AS 																																		PRICE_PALLET_7,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_8'
				) AS 																																		PRICE_PALLET_8,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_9'
				) AS 																																		PRICE_PALLET_9,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_10'
				) AS 																																		PRICE_PALLET_10,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_11'
				) AS 																																		PRICE_PALLET_11,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_12'
				) AS 																																		PRICE_PALLET_12,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_13'
				) AS 																																		PRICE_PALLET_13,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_14'
				) AS 																																		PRICE_PALLET_14,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_15'
				) AS 																																		PRICE_PALLET_15,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_16'
				) AS 																																		PRICE_PALLET_16,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_17'
				) AS 																																		PRICE_PALLET_17,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_18'
				) AS 																																		PRICE_PALLET_18,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_19'
				) AS 																																		PRICE_PALLET_19,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_20'
				) AS 																																		PRICE_PALLET_20,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_21'
				) AS 																																		PRICE_PALLET_21,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_22'
				) AS 																																		PRICE_PALLET_22,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_23'
				) AS 																																		PRICE_PALLET_23,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_24'
				) AS 																																		PRICE_PALLET_24,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_25'
				) AS 																																		PRICE_PALLET_25,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_26'
				) AS 																																		PRICE_PALLET_26,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_27'
				) AS 																																		PRICE_PALLET_27,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_28'
				) AS 																																		PRICE_PALLET_28,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_29'
				) AS 																																		PRICE_PALLET_29,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_30'
				) AS 																																		PRICE_PALLET_30,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_31'
				) AS 																																		PRICE_PALLET_31,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_32'
				) AS 																																		PRICE_PALLET_32,
				(SELECT (CASE WHEN RGCUB_PALLETS_1.CHARGE_AMOUNT IS NULL THEN 0 ELSE (RGCUB_PALLETS_1.CHARGE_AMOUNT) END) AS
				FROM RATE_GEO_COST_UNIT_BREAK RGCUB_PALLETS_1 
				WHERE RGC.RATE_GEO_COST_GROUP_GID = RGCUB_PALLETS_1.RATE_GEO_COST_GROUP_GID 
				AND RGCUB_PALLETS_1.RATE_UNIT_BREAK_GID = 'ULE/PR.PALLET_33'
				) AS 																																		PRICE_PALLET_33,
		rpt_general.f_remove_domain((select distinct NVL(RFRJ_FUEL.RATE_FACTOR_RULE_GID,' ')
		from RATE_FACTOR_RULE_JOIN RFRJ_FUEL
		where RG.RATE_GEO_GID = RFRJ_FUEL.RATE_GEO_GID
		))																																					FUEL_SURCHARGE,
		
		(SELECT NVL(LA_TYPE.LANE_ATTRIBUTE_VALUE,' ')	
				FROM LANE_ATTRIBUTE LA_TYPE
				WHERE
				xl.X_LANE_GID = LA_TYPE.X_LANE_GID 
				AND LA_TYPE.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_MASTER_TAG'
		) AS 																																				MASTER_TAG,
	
				(select rgc_temp.CHARGE_AMOUNT
				from rate_geo_cost rgc_temp
				WHERE rgc_temp.RATE_GEO_COST_GROUP_GID = RGC.RATE_GEO_COST_GROUP_GID
				AND rgc_temp.CHARGE_ACTION = 'W'
				)																																																												ULE_FUEL_WEIGHTED_COST,	
				(SELECT listagg(NVL(LA_REGION.LANE_ATTRIBUTE_VALUE,' '),'/') WITHIN GROUP (ORDER BY XL.x_lane_gid)	
				FROM LANE_ATTRIBUTE LA_REGION
				WHERE
				xl.X_LANE_GID = LA_REGION.X_LANE_GID 
				AND LA_REGION.LANE_ATTRIBUTE_DEF_GID ='ULE.ULE_FUEL_POLICY'
		)  fuel_policy,
				
				
				
				RG.RATE_GEO_GID as 																															RATE_GEO_GID,

				CASE
					WHEN RGC.RATE_UNIT_BREAK_PROFILE_GID IS NULL THEN ' '
					ELSE 
						CASE
							WHEN RGC.LEFT_OPERAND1 = 'SHIPMENT.SHIPUNITS.SPEC' THEN RGC.LOW_VALUE1
							ELSE
								CASE
									WHEN RGC.LEFT_OPERAND2 = 'SHIPMENT.SHIPUNITS.SPEC' THEN RGC.LOW_VALUE2
									ELSE 
										CASE
											WHEN RGC.LEFT_OPERAND3 = 'SHIPMENT.SHIPUNITS.SPEC' THEN RGC.LOW_VALUE3
											ELSE 
												CASE
													WHEN RGC.LEFT_OPERAND4 = 'SHIPMENT.SHIPUNITS.SPEC' THEN RGC.LOW_VALUE4
												ELSE ' '
												END
										END
								END
						END
				END AS 																																		PALLET_TYPE_RR,
				TRIM(TO_CHAR((select nvl((SELECT SUM(CASE
				WHEN (AC.CHARGE_AMOUNT_GID = 'EUR' OR AC.CHARGE_AMOUNT_GID IS NULL) THEN AC.CHARGE_AMOUNT
				WHEN AC.CHARGE_AMOUNT_GID <> 'EUR' THEN AC.CHARGE_AMOUNT * 
				UNILEVER.EBS_PROCEDURES_ULE.GET_QUARTERLY_EX_RATE(SYSDATE,AC.CHARGE_AMOUNT_GID,'EUR')
				else 0
				END)
	
				FROM ACCESSORIAL_COST AC,
					RATE_GEO_ACCESSORIAL RG_AC
				WHERE RG_AC.ACCESSORIAL_COST_GID = AC.ACCESSORIAL_COST_GID
				AND RG_AC.RATE_GEO_GID = RG.RATE_GEO_GID
				AND TO_CHAR(AC.EFFECTIVE_DATE,'YYYY-MM-DD') = TO_CHAR(TRUNC(SYSDATE,'MM'),'YYYY-MM-DD')
				and AC.ACCESSORIAL_COST_XID LIKE '%REIMBURSEMENT%'
				),0) from dual),'999999999999D99','NLS_NUMERIC_CHARACTERS = ''. ''')) as																	REIMBURSMENT_FUEL_eur
				

FROM
	X_LANE XL,
	RATE_GEO RG,
	LANE_TENDER_INFO LTI,
	location loc_tsp,
	RATE_GEO_COST RGC,
	RATE_OFFERING RO


WHERE
		XL.X_LANE_GID = RG.X_LANE_GID
AND 	XL.DOMAIN_NAME <> 'ULE/SE'
AND		XL.X_LANE_GID = LTI.X_LANE_GID
and 		loc_tsp.location_gid = LTI.SERVPROV_GID
AND     RGC.RATE_GEO_COST_GROUP_GID = RG.RATE_GEO_GID
AND 	RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID
AND 	RO.SERVPROV_GID = LTI.SERVPROV_GID
AND 	rgc.RATE_GEO_COST_GROUP_GID NOT LIKE '%2Y%'
and 		RGC.CHARGE_ACTION <> 'W'
and 	(CASE WHEN INSTR(XL.X_LANE_XID,'XD')>0 THEN 'Y' ELSE 'N' END) = 'N'




and (CASE WHEN RG.EXPIRATION_DATE<SYSDATE OR RG.IS_ACTIVE='N' THEN 'N' ELSE 'Y' END) = 'Y'



) TEMP
where
temp.charge_amount is null

GROUP BY
TEMP.SOURCE_LOCATION_ID,
		TEMP.DESTINATION_LOCATION_ID

