SELECT DISTINCT sh.shipment_gid,
	   om.order_release_gid,
		sh.SOURCE_LOCATION_GID,
		sh.DEST_LOCATION_GID,
		(select or_temp.source_location_gid
		from order_release or_temp
		where or_temp.order_release_gid = om.order_release_gid
		)																												or_source_loc,
		(select or_temp.dest_location_gid
		from order_release or_temp
		where or_temp.order_release_gid = om.order_release_gid
		)																												or_dest_loc,
		(SELECT SUM(ORL_TEMP.COST)
		FROM ALLOCATION_OR_LINE_D ORL_TEMP,
			ALLOCATION_BASE AB
		WHERE ORL_TEMP.ORDER_RELEASE_LINE_GID = SSUL.OR_LINE_GID
			AND AB.ALLOC_SEQ_NO = ORL_TEMP.ALLOC_SEQ_NO
		AND ORL_TEMP.COST_DESCRIPTION ='B'
		AND AB.SHIPMENT_GID = SH.SHIPMENT_GID
		
		)																																	BASE_cost_sum,
		
		
		
		
		
		
		
		SSUL.OR_LINE_GID,
		case when sh.SOURCE_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837') then
		(SELECT SUM(ORL_TEMP.COST)
		FROM ALLOCATION_OR_LINE_D ORL_TEMP,
			ALLOCATION_BASE AB
		WHERE ORL_TEMP.ORDER_RELEASE_LINE_GID = SSUL.OR_LINE_GID
			AND AB.ALLOC_SEQ_NO = ORL_TEMP.ALLOC_SEQ_NO
		AND ORL_TEMP.COST_DESCRIPTION ='B'
		AND AB.SHIPMENT_GID = SH.SHIPMENT_GID
		
		)
		else 0
		end as 																																BASE_COST_OUT,
		case when sh.SOURCE_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837') then
		(SELECT SUM(ORL_TEMP.COST)
		FROM ALLOCATION_OR_LINE_D ORL_TEMP,
			ALLOCATION_BASE AB
		WHERE ORL_TEMP.ORDER_RELEASE_LINE_GID = SSUL.OR_LINE_GID
			AND AB.ALLOC_SEQ_NO = ORL_TEMP.ALLOC_SEQ_NO
		AND ORL_TEMP.COST_DESCRIPTION ='A'
		AND AB.SHIPMENT_GID = SH.SHIPMENT_GID
		
		)
		else 0
		end as 																																ACC_COST_OUT,
		case when sh.dest_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837') then
		(SELECT SUM(ORL_TEMP.COST)
		FROM ALLOCATION_OR_LINE_D ORL_TEMP,
			ALLOCATION_BASE AB
		WHERE ORL_TEMP.ORDER_RELEASE_LINE_GID = SSUL.OR_LINE_GID
			AND AB.ALLOC_SEQ_NO = ORL_TEMP.ALLOC_SEQ_NO
		AND ORL_TEMP.COST_DESCRIPTION ='B'
		AND AB.SHIPMENT_GID = SH.SHIPMENT_GID
		
		)
		else 0
		end as 																																BASE_COST_IN,
		case when sh.dest_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837') then
		(SELECT SUM(ORL_TEMP.COST)
		FROM ALLOCATION_OR_LINE_D ORL_TEMP,
			ALLOCATION_BASE AB
		WHERE ORL_TEMP.ORDER_RELEASE_LINE_GID = SSUL.OR_LINE_GID
			AND AB.ALLOC_SEQ_NO = ORL_TEMP.ALLOC_SEQ_NO
		AND ORL_TEMP.COST_DESCRIPTION ='A'
		AND AB.SHIPMENT_GID = SH.SHIPMENT_GID
		
		)
		else 0
		end as 																																ACC_COST_IN,
		'CONST COST * NUM_PALLETS' AS																										HANDLING_COST,
		(SELECT LISTAGG(XL.X_LANE_GID,'/') WITHIN GROUP (ORDER BY XL.X_LANE_GID)
		FROM X_LANE XL
		WHERE XL.SOURCE_LOCATION_GID = OM.SOURCE_LOCATION_GID
		AND XL.DEST_LOCATION_GID = OM.DEST_LOCATION_GID
		AND XL.DOMAIN_NAME = 'ULE/PR'
		
		)																																		MATCHING_XL,
		
		
		
		
		
		
		
		
		
		
		case when sh.SOURCE_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837') then
		sh.SOURCE_LOCATION_GID
		else
		sh.dest_LOCATION_GID end																								X_dock,
		(select loc.location_name
		from location loc
		where loc.location_gid =
		(case when sh.SOURCE_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837') then
		sh.SOURCE_LOCATION_GID
		else
		sh.dest_LOCATION_GID end)
		)																														x_dock_name,
		(select loc.city
		from location loc
		where loc.location_gid =
		(case when sh.SOURCE_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837') then
		sh.SOURCE_LOCATION_GID
		else
		sh.dest_LOCATION_GID end)
		)																														x_dock_city,

		case when sh.SOURCE_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837') then
		su.SHIP_UNIT_COUNT
		else 0
		end as 														pallets_out,	
		case when sh.dest_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837') then
		su.SHIP_UNIT_COUNT
		else 0
		end as 														pallets_in,	
		SU.SHIP_UNIT_GID,
		SU.TRANSPORT_HANDLING_UNIT_GID,
		SU.SHIP_UNIT_COUNT,

		(SELECT LOC.LOCATION_NAME
		FROM LOCATION LOC
		WHERE LOC.LOCATION_GID = sh.SOURCE_LOCATION_GID)		SOURCE_LOC_NAME,
		(SELECT LOC.LOCATION_NAME
		FROM LOCATION LOC
		WHERE LOC.LOCATION_GID = sh.DEST_LOCATION_GID)		DEST_LOC_NAME,
		(SELECT LOC.CITY
		FROM LOCATION LOC
		WHERE LOC.LOCATION_GID = sh.SOURCE_LOCATION_GID)		SOURCE_LOC_CITY,
		(SELECT LOC.CITY
		FROM LOCATION LOC
		WHERE LOC.LOCATION_GID = sh.DEST_LOCATION_GID)		DEST_LOC_CITY,
		TO_CHAR(sh.end_time,'MM') AS 				LATE_DELIVERY_MONTH,
		TO_CHAR(end_time,'WW') AS 				LATE_DELIVERY_WEEK
		
		
		
		


FROM shipment sh,
	order_movement om,
	 SHIP_UNIT SU,
	 SHIP_UNIT_LINE SUL,
	 S_SHIP_UNIT_LINE SSUL

WHERE
 SU.ORDER_RELEASE_GID = om.ORDER_RELEASE_GID
 AND SUL.SHIP_UNIT_GID = SU.SHIP_UNIT_GID
 AND SSUL.SHIP_UNIT_GID = SUL.SHIP_UNIT_GID
and om.shipment_gid = sh.shipment_gid
and (sh.SOURCE_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837')
OR sh.DEST_LOCATION_GID IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837'))

and NOT EXISTS
		(SELECT 1
		FROM shipment_refnum sh_ref_1
		WHERE sh_ref_1.shipment_Refnum_Qual_Gid = 'ULE.ULE_SHIPMENT_STREAM'
		   AND sh_ref_1.shipment_Refnum_Value = 'SECONDARY'
		   AND sh_ref_1.shipment_gid = sh.shipment_gid)	
		   
		   
and TO_CHAR(sh.end_time,'YYYY') = '2015'
-- and TO_CHAR(sh.end_time,'MM') = '05'
-- and sh.shipment_gid in ('ULE/PR.100661104')
AND SH.SHIPMENT_TYPE_GID IN ('TRANSPORT')

and exists 
(SELECT ORLS_TEMP.order_release_gid
			FROM SHIPMENT SH_TEMP,
			order_movement VORLS_TEMP,
				ORDER_RELEASE ORLS_TEMP
				
			WHERE 1=1
			AND SH_TEMP.SHIPMENT_GID = VORLS_TEMP.SHIPMENT_GID
			AND ORLS_TEMP.ORDER_RELEASE_GID = VORLS_TEMP.ORDER_RELEASE_GID
			AND ORLS_TEMP.ORDER_RELEASE_GID = om.ORDER_RELEASE_GID
			AND SH_TEMP.SHIPMENT_TYPE_GID = 'HANDLING'
				
			)
and (SELECT SH_STATUS.STATUS_VALUE_GID
		FROM
		SHIPMENT_STATUS SH_STATUS
		WHERE
		SH_STATUS.SHIPMENT_GID = SH.SHIPMENT_GID
		AND SH_STATUS.STATUS_TYPE_GID = 'ULE/PR.TRANSPORT CANCELLATION'
		)='ULE/PR.NOT CANCELLED'
-- AND OM.ORDER_RELEASE_GID='ULE.0180618648'