SELECT SH.SHIPMENT_GID,
	sh.insert_user,
	to_char(sh.insert_date,'YYYY-MM-DD') INSERT_DATE


FROM
SHIPMENT SH


WHERE 

 NOT EXISTS
(SELECT 1
FROM SHIPMENT_STOP SS_TEMP,
LOCATION_ROLE_PROFILE LOC_P
WHERE SS_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
AND LOC_P.LOCATION_GID  = SS_TEMP.LOCATION_GID
AND LOC_P.LOCATION_ROLE_GID = 'XDOCK'
AND SS_TEMP.STOP_NUM =1
-- AND SS_TEMP.LOCATION_GID NOT IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837','ULE.X207480')


)
AND NOT EXISTS
(SELECT 1
FROM SHIPMENT_STOP SS_TEMP,
LOCATION_ROLE_PROFILE LOC_P
WHERE SS_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
AND LOC_P.LOCATION_GID  = SS_TEMP.LOCATION_GID
AND LOC_P.LOCATION_ROLE_GID = 'XDOCK'
AND SS_TEMP.STOP_NUM = SH.NUM_STOPS
-- AND SS_TEMP.LOCATION_GID NOT IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837','ULE.X207480')


)
AND EXISTS
(SELECT 1
FROM SHIPMENT_STOP SS_TEMP,
LOCATION_ROLE_PROFILE LOC_P
WHERE SS_TEMP.SHIPMENT_GID = SH.SHIPMENT_GID
AND LOC_P.LOCATION_GID  = SS_TEMP.LOCATION_GID
AND LOC_P.LOCATION_ROLE_GID = 'XDOCK'
AND SS_TEMP.STOP_NUM <>1
AND SS_TEMP.STOP_NUM <> SH.NUM_STOPS
-- AND SS_TEMP.LOCATION_GID  IN ('ULE.V50360873','ULE.V50413833','ULE.V50413835','ULE.V50413836','ULE.V50413837','ULE.X207480')


)
AND SH.NUM_STOPS >2
	AND NOT EXISTS(SELECT 1
	FROM SHIPMENT_REFNUM
	WHERE SHIPMENT_GID = SH.SHIPMENT_GID
	AND SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_SHIPMENT_STREAM'
	AND SHIPMENT_REFNUM_VALUE = 'SECONDARY')
AND NOT EXISTS(SELECT 1
	FROM shipment_status
	WHERE SHIPMENT_GID = SH.SHIPMENT_GID
	AND STATUS_TYPE_GID = 'ULE/PR.SHIPMENT_COST'
	AND STATUS_VALUE_GID = 'ULE/PR.SC_NO CHANGES ALLOWED')