SELECT ORLS.ORDER_RELEASE_GID

FROM ORDER_RELEASE ORLS
JOIN ORDER_RELEASE_STATUS ORLS_ST ON (ORLS.ORDER_RELEASE_GID = ORLS_ST.ORDER_RELEASE_GID AND ORLS_ST.STATUS_TYPE_GID = 'ULE.CANCELLED'
AND ORLS_ST.STATUS_VALUE_GID = 'ULE.CANCELLED_CANCELLED')

WHERE ORLS.EARLY_PICKUP_DATE >= TO_DATE(:P_DATE_FROM,:P_DATE_TIME_FORMAT)
AND ORLS.EARLY_PICKUP_DATE <= TO_DATE(:P_DATE_TO,:P_DATE_TIME_FORMAT)
and orls.early_pickup_date is not null
and orls.late_delivery_date is not null