SELECT * FROM ORDER_RELEASE_REFNUM OR_REF



WHERE OR_REF.ORDER_RELEASE_GID 

IN(
SELECT ORDER_RELEASE_GID FROM ORDER_RELEASE_REFNUM WHERE ORDER_RELEASE_REFNUM_QUAL_GID LIKE '%FINAL%' AND 	ORDER_RELEASE_REFNUM_VALUE in (
'W20160313/F26149'
))

AND 

or_ref.ORDER_RELEASE_REFNUM_QUAL_GID LIKE '%FINANCE_PO%' --'%FINANCE_PO%'

-- or_ref.ORDER_RELEASE_REFNUM_QUAL_GID LIKE '%PO%'


--

select vorls.shipment_gid,
'ULE/PR.SHIPMENT_COST'     STATUS_TYPE_GID,
'ULE/PR.SC_APPROVED'				STATUS_VALUE_GID,
'ULE/PR' 										DOMAIN_NAME
-- SHS.DOMAIN_NAME



from
-- shipment_status shs,
view_shipment_order_release vorls

where
-- vorls.shipment_gid = shs.shipment_gid
-- AND SHS.STATUS_TYPE_GID = 'ULE/PR.SHIPMENT_COST'
vorls.order_release_gid in 
(
SELECT ORDER_RELEASE_GID FROM ORDER_RELEASE_REFNUM WHERE 	ORDER_RELEASE_REFNUM_VALUE in (
'W20160313/F26149'
)


)