SELECT * FROM
(SELECT DISTINCT ORLS.SOURCE_LOCATION_GID AS																												SOURCE_LOC_ID,
		LOC_SOURCE.LOCATION_NAME AS																															SOURCE_NAME,
		LOC_SOURCE.CITY AS 																																	SOURCE_CITY,
		ORLS.DEST_LOCATION_GID	AS																															DEST_LOC_ID,
		LOC_DEST.LOCATION_NAME AS																															DEST_NAME,
		LOC_DEST.CITY AS 																																	DESTINATION_CITY,
		SH.SERVPROV_GID AS TSP_ID,
		LOC_TSP.LOCATION_NAME AS TSP_NAME,
		
		(SELECT LISTAGG(NVL(SR_REGION.SHIPMENT_REFNUM_VALUE,'N/A'),'/') WITHIN GROUP (ORDER BY SH.SHIPMENT_GID) AS REGION
		FROM SHIPMENT_REFNUM SR_REGION 
		WHERE SR_REGION.SHIPMENT_GID = SH.SHIPMENT_GID AND SR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION'
		)																																					REGION,
		(SELECT LISTAGG(SE.EQUIPMENT_TYPE_GID,'/') WITHIN GROUP (ORDER BY SH.SHIPMENT_GID)
		FROM SHIPMENT_S_EQUIPMENT_JOIN SHJ,
			S_EQUIPMENT SE
		WHERE SHJ.S_EQUIPMENT_GID = SE.S_EQUIPMENT_GID 
		AND SHJ.SHIPMENT_GID = SH.SHIPMENT_GID
		)																																					EQUIPMENT,
		
		(SELECT LISTAGG(L_REF.LANE_ATTRIBUTE_VALUE,'/') WITHIN GROUP (ORDER BY L_REF.X_LANE_GID)
				FROM LANE_ATTRIBUTE L_REF
				WHERE L_REF.LANE_ATTRIBUTE_DEF_GID = 'ULE.ULE_TRANSPORT_MODE'
				AND L_REF.X_LANE_GID = 
				(SELECT RG.X_LANE_GID
				FROM RATE_GEO RG
				WHERE RG.RATE_GEO_GID = SH.RATE_GEO_GID)
				
				) 																																			TRANSPORT_MODE,
		SSUL.S_SHIP_UNIT_GID																																SHIP_UNIT_GID,
		SSUL.PACKAGED_ITEM_GID																																PACKAGED_ITEM_GID,
		(SELECT LISTAGG(IT.ITEM_NAME,'/') WITHIN GROUP (ORDER BY SSUL.PACKAGED_ITEM_GID)
		FROM ITEM IT
		WHERE IT.ITEM_GID = SSUL.PACKAGED_ITEM_GID
		
		)																																					ITEM_NAME,
		ltrim(TO_CHAR(SSUL.	WEIGHT_BASE*0.45,'999999999D99','NLS_NUMERIC_CHARACTERS = '', '''))																ITEM_WEIGHT_KG,
		trim((SELECT TO_CHAR(SUM(CASE
				WHEN (SHC.COST_GID = 'EUR' OR SHC.COST_GID IS NULL) THEN SHC.COST
				WHEN SHC.COST_GID <> 'EUR' THEN SHC.COST * 
				UNILEVER.EBS_PROCEDURES_ULE.GET_QUARTERLY_EX_RATE(TO_DATE(SH.END_TIME,'DD.MM.YYYY'),SHC.COST_GID,'EUR')
				END),'999999999999D99','NLS_NUMERIC_CHARACTERS = '', ''')
				
		FROM SHIPMENT_COST SHC
		WHERE SHC.SHIPMENT_GID = SH.SHIPMENT_GID
		AND SHC.COST_TYPE	IN ('B','A')
		))																																					COST_EUR,

		ORLS.ORDER_RELEASE_XID	AS																															OR_ID,	
		SH.SHIPMENT_XID AS																																	SH_ID,

		TO_CHAR(UTC.GET_LOCAL_DATE(SH.END_TIME,SH.DEST_LOCATION_GID),'YYYY-MM-DD')																			SH_END_TIME
		


FROM
	SHIPMENT_STOP SS,
	SHIPMENT SH,
	SHIPMENT_STOP_D SSD,
	S_SHIP_UNIT SSU,
	S_SHIP_UNIT_LINE SSUL,
	ORDER_RELEASE ORLS,
	LOCATION LOC_SOURCE,
	LOCATION LOC_DEST,
	LOCATION LOC_TSP


WHERE 1=1
	AND SH.DOMAIN_NAME IN ('ULE/PR','ULE')
	AND	SH.SHIPMENT_TYPE_GID = 'TRANSPORT'
	
	AND	SS.SHIPMENT_GID = SH.SHIPMENT_GID
	AND SSD.SHIPMENT_GID = SS.SHIPMENT_GID
	AND SSD.STOP_NUM = SS.STOP_NUM
	AND SSD.S_SHIP_UNIT_GID = SSU.S_SHIP_UNIT_GID
	AND SSU.S_SHIP_UNIT_GID = SSUL.S_SHIP_UNIT_GID
	AND SSUL.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID

	
	AND	LOC_SOURCE.LOCATION_GID = ORLS.SOURCE_LOCATION_GID
	AND	LOC_DEST.LOCATION_GID = ORLS.DEST_LOCATION_GID
	
	AND	LOC_TSP.LOCATION_GID = SH.SERVPROV_GID
	
	

	AND (SELECT SHS_STATUS_CANC.STATUS_VALUE_GID
	FROM SHIPMENT SH_STATUS_CANC
	LEFT OUTER JOIN SHIPMENT_STATUS SHS_STATUS_CANC ON (SH_STATUS_CANC.SHIPMENT_GID = SHS_STATUS_CANC.SHIPMENT_GID 
	AND SHS_STATUS_CANC.STATUS_TYPE_GID = 'ULE/PR.TRANSPORT CANCELLATION')
	WHERE SH_STATUS_CANC.SHIPMENT_GID = SH.SHIPMENT_GID
	)='ULE/PR.NOT CANCELLED'
	
	--------------------------------------------------------------------
	AND	SH.END_TIME >= TRUNC(SYSDATE) - 99
	AND	SH.END_TIME <= TRUNC(SYSDATE) + 99
	
	AND	SH.END_TIME >= TO_DATE(:END_TIME_FROM,:P_DATE_TIME_FORMAT)
	AND	SH.END_TIME <= TO_DATE(:END_TIME_TO,:P_DATE_TIME_FORMAT)
	
	AND 
	(SELECT NVL(SR_REGION.SHIPMENT_REFNUM_VALUE,'N/A') AS REGION
		FROM SHIPMENT_REFNUM SR_REGION 
		WHERE SR_REGION.SHIPMENT_GID = SH.SHIPMENT_GID AND SR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION'
		) = NVL(:P_REGION,(SELECT NVL(SR_REGION.SHIPMENT_REFNUM_VALUE,'N/A') AS REGION
		FROM SHIPMENT_REFNUM SR_REGION 
		WHERE SR_REGION.SHIPMENT_GID = SH.SHIPMENT_GID AND SR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION'
		))
		
) TEMP
WHERE 1=1
	
	
	
