SELECT DISTINCT SH.SHIPMENT_GID AS																														SH_ID,
		ORLS.ORDER_RELEASE_GID	AS																														OR_ID,		
		ORLS.SOURCE_LOCATION_GID AS																														SOURCE_LOC_ID,
		LOC_SOURCE.CITY AS 																																SOURCE_CITY,
		LOC_SOURCE.COUNTRY_CODE3_GID AS 																												SOURCE_country,
		ORLS.DEST_LOCATION_GID	AS																														DEST_LOC_ID,
		LOC_DEST.CITY AS 																																DESTINATION_CITY,
		LOC_DEST.COUNTRY_CODE3_GID AS 																													DEST_country,
		
		(select listagg(  TO_CHAR(FROM_TZ(CAST(IESH_EVENT_DELIVER.EVENTDATE AS TIMESTAMP), 'GMT') AT TIME ZONE LOC_SOURCE.TIME_ZONE_GID, 'DD-MM-YYYY HH24:MI:SS'))
				within group (order by SH_EVENT_DELIVER.shipment_gid)
				from 
				SHIPMENT SH_EVENT_DELIVER 
				LEFT OUTER JOIN SS_STATUS_HISTORY SSSH_EVENT_DELIVER ON (SH_EVENT_DELIVER.SHIPMENT_GID = SSSH_EVENT_DELIVER.SHIPMENT_GID)
				LEFT OUTER JOIN IE_SHIPMENTSTATUS IESH_EVENT_DELIVER ON (SSSH_EVENT_DELIVER.I_TRANSACTION_NO = IESH_EVENT_DELIVER.I_TRANSACTION_NO 
				AND IESH_EVENT_DELIVER.STATUS_CODE_GID in ('ULE/PR.CP','CP'))
				LEFT OUTER JOIN BS_STATUS_CODE BSSC_EVENT_DELIVER ON (IESH_EVENT_DELIVER.STATUS_CODE_GID = BSSC_EVENT_DELIVER.BS_STATUS_CODE_GID)
				
				
				where	SH_EVENT_DELIVER.SHIPMENT_GID = SH.SHIPMENT_GID
								AND	(SSSH_EVENT_DELIVER.INSERT_DATE = (
														SELECT 	MAX(SSSH_EVENT_DELIVER_TEMP.INSERT_DATE)
														FROM	SS_STATUS_HISTORY SSSH_EVENT_DELIVER_TEMP
																LEFT OUTER JOIN IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 
																ON (SSSH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO = IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO)
														WHERE 	SSSH_EVENT_DELIVER_TEMP.SHIPMENT_GID=SH.SHIPMENT_GID
																AND IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID in ('ULE/PR.CP','CP')
																AND	SSSH_EVENT_DELIVER_TEMP.SHIPMENT_STOP_NUM = SS.STOP_NUM
																/* AND	IESH_EVENT_DELIVER_TEMP.EVENTDATE BETWEEN TO_DATE('2013-10-01','YYYY-MM-DD') 
																AND TO_DATE('2013-11-01 00:00:00','YYYY-MM-DD HH24:MI:SS') */
														
				
			))
				
				
				) as 																																		ACTUAL_PICKUP,
				
		
		(select listagg(  TO_CHAR(FROM_TZ(CAST(IESH_EVENT_DELIVER.EVENTDATE AS TIMESTAMP), 'GMT') AT TIME ZONE LOC_DEST.TIME_ZONE_GID, 'YYYY-MM-DD HH24:MI:SS'))
				within group (order by SH_EVENT_DELIVER.shipment_gid)
				from 
				SHIPMENT SH_EVENT_DELIVER 
				LEFT OUTER JOIN SS_STATUS_HISTORY SSSH_EVENT_DELIVER ON (SH_EVENT_DELIVER.SHIPMENT_GID = SSSH_EVENT_DELIVER.SHIPMENT_GID)
				LEFT OUTER JOIN IE_SHIPMENTSTATUS IESH_EVENT_DELIVER ON (SSSH_EVENT_DELIVER.I_TRANSACTION_NO = IESH_EVENT_DELIVER.I_TRANSACTION_NO 
				AND IESH_EVENT_DELIVER.STATUS_CODE_GID in ('ULE/PR.D1','D1'))
				LEFT OUTER JOIN BS_STATUS_CODE BSSC_EVENT_DELIVER ON (IESH_EVENT_DELIVER.STATUS_CODE_GID = BSSC_EVENT_DELIVER.BS_STATUS_CODE_GID)
				
				
				where	SH_EVENT_DELIVER.SHIPMENT_GID = SH.SHIPMENT_GID
								AND	(SSSH_EVENT_DELIVER.INSERT_DATE = (
														SELECT 	MAX(SSSH_EVENT_DELIVER_TEMP.INSERT_DATE)
														FROM	SS_STATUS_HISTORY SSSH_EVENT_DELIVER_TEMP
																LEFT OUTER JOIN IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 
																ON (SSSH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO = IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO)
														WHERE 	SSSH_EVENT_DELIVER_TEMP.SHIPMENT_GID=SH.SHIPMENT_GID
																AND IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID in ('ULE/PR.D1','D1')
																AND	SSSH_EVENT_DELIVER_TEMP.SHIPMENT_STOP_NUM = SS.STOP_NUM
										/* 						AND	IESH_EVENT_DELIVER_TEMP.EVENTDATE BETWEEN TO_DATE('2013-10-01','YYYY-MM-DD') 
																AND TO_DATE('2013-11-01 00:00:00','YYYY-MM-DD HH24:MI:SS') */

			))
				
				
				) as 																																	ACTUAL_DELIVERY,
				
				
		(sh.servprov_gid) as 																															SERVICE_PROVIDER,
		loc_tsp.LOCATION_NAME as 																														SERVPROV_NAME,
		TO_char(sh.start_time,'DD-MM-YYYY HH24:MI:SS')																									SH_START_TIME,
		TO_char(sh.END_TIME,'DD-MM-YYYY HH24:MI:SS')																									SH_END_TIME,
		'-' AS																																			NEW_PICKUP,
		'-' AS 																																			NEW_DELIVERY,
		(
		
		select listagg(orls_CAT.order_release_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orls_CAT.order_release_GID)
		from order_release_REFNUM orls_CAT
		
		where orls_CAT.order_release_GID = orls.order_release_GID 
		AND orls_CAT.order_release_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_CATEGORY'
		
		
		) AS 																																	CATEGORY,
		
		(
		
		select listagg(orls_CAT.order_release_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orls_CAT.order_release_GID)
		from order_release_REFNUM orls_CAT
		
		where orls_CAT.order_release_GID = orls.order_release_GID 
		AND orls_CAT.order_release_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_TYPE'
		
		
		) AS 																																	MATERIAL,
		(
		select listagg(orlsr_SPEC.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orlsr_SPEC.ORDER_RELEASE_GID)
		from ORDER_RELEASE_REFNUM orlsr_SPEC
		
		where orls.ORDER_RELEASE_GID = orlsr_SPEC.ORDER_RELEASE_GID 
				AND orlsr_SPEC.ORDER_RELEASE_REFNUM_QUAL_GID IN ('ULE.ULE_SPECIAL_ORDER')
		
		
		) AS 																																			SPECIAL_ORDER,
		(
		select listagg(orlsr_EXP.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orlsr_EXP.ORDER_RELEASE_GID)
		from ORDER_RELEASE_REFNUM orlsr_EXP
		
		where orls.ORDER_RELEASE_GID = orlsr_EXP.ORDER_RELEASE_GID 
				AND orlsr_EXP.ORDER_RELEASE_REFNUM_QUAL_GID IN ('ULE.ULE_EXPRESS_BY_CUSTOMER')
		
		
		) AS 																																			EXPRESS,
		ORLS.INSERT_USER AS 																															INSERT_USER,
		'"'||(
		select listagg(orlsr_po.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orlsr_po.ORDER_RELEASE_GID)
		from ORDER_RELEASE_REFNUM orlsr_po 
		
		where orls.ORDER_RELEASE_GID = orlsr_po.ORDER_RELEASE_GID 
				AND orlsr_po.ORDER_RELEASE_REFNUM_QUAL_GID IN ('PO','ULE.ULE_PO_NUMBER','ULE.ULE_SAP_PO_NUMBER','CUST_PO','ULE.ULE_FINANCE_PO_NUMBER')
		
		
		)||'"' AS 																																			OR_PO_NUM,
		'"'||(
		select listagg(orlsr_DN_ULE.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orlsr_DN_ULE.ORDER_RELEASE_GID)
		from ORDER_RELEASE_REFNUM orlsr_DN_ULE 
		
		where orls.ORDER_RELEASE_GID = orlsr_DN_ULE.ORDER_RELEASE_GID 
				AND orlsr_DN_ULE.ORDER_RELEASE_REFNUM_QUAL_GID IN ('ULE.ULE_DN_NUMBER','UL_SAP_DN')
		
		
		)||'"' AS 																																			OR_DN_NUM,
		
		

		
		
		'"'||(select listagg(SHR_PO.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_PO.SHIPMENT_GID)
		from SHIPMENT_REFNUM SHR_PO 
		where SHR_PO.SHIPMENT_GID = sh.SHIPMENT_GID AND SHR_PO.SHIPMENT_REFNUM_QUAL_GID = 'ULE.PO'
		)||'"' as 																																			SH_PO,
		'"'||(select listagg(SHR_DN.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_DN.SHIPMENT_GID)
		from SHIPMENT_REFNUM SHR_DN
		where SHR_DN.SHIPMENT_GID = sh.SHIPMENT_GID AND SHR_DN.SHIPMENT_REFNUM_QUAL_GID = 'ULE.DN'
		)||'"' as 																																			SH_DN,
		SS.STOP_NUM AS 																																	STOP_NUM,
		ss.stop_type as																																	STOP_TYPE,
		SS.LOCATION_GID AS																																APP_LOCATION,
		
		(CASE WHEN ss.stop_type ='D' THEN 
		(
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,ORLS.DEST_LOCATION_GID),'DD-MM-YYYY HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN ss.stop_type ='P' THEN (
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,ORLS.SOURCE_LOCATION_GID),'DD-MM-YYYY HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		ELSE NULL
		END
		) AS 																																			APP_START,
		
		(CASE WHEN ss.stop_type ='D' THEN 
		(
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,ORLS.DEST_LOCATION_GID),'DD-MM-YYYY HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN ss.stop_type ='P' THEN (
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,ORLS.SOURCE_LOCATION_GID),'DD-MM-YYYY HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		ELSE NULL
		END
		) AS 																																			APP_END,
		

		'-' AS																																			COMMENTS,
		'-' AS																																			ADDITIONAL_COMMENTS
	
		
FROM
	SHIPMENT_STOP SS,
	SHIPMENT SH,
	SHIPMENT_STOP_D SSD,
	S_SHIP_UNIT SSU,
	S_SHIP_UNIT_LINE SSUL,
	ORDER_RELEASE ORLS,
	LOCATION LOC_SOURCE,
	LOCATION LOC_DEST,
	location loc_tsp,
	SHIP_UNIT_EQUIP_REF_UNIT_JOIN SUERUJ_PALLET,
	ship_unit su

WHERE 1=1
	AND SH.DOMAIN_NAME = 'ULE/PR'
	AND	SH.SHIPMENT_TYPE_GID = 'TRANSPORT'
	
	AND	SS.SHIPMENT_GID = SH.SHIPMENT_GID
	AND SSD.SHIPMENT_GID = SS.SHIPMENT_GID
	AND SSD.STOP_NUM = SS.STOP_NUM
	AND SSD.S_SHIP_UNIT_GID = SSU.S_SHIP_UNIT_GID
	AND SSU.S_SHIP_UNIT_GID = SSUL.S_SHIP_UNIT_GID
	AND SSUL.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
	
	and	su.SHIP_UNIT_GID = SUERUJ_PALLET.SHIP_UNIT_GID
	and	su.SHIP_UNIT_GID = SSU.SHIP_UNIT_GID
	
	AND	LOC_SOURCE.LOCATION_GID = ORLS.SOURCE_LOCATION_GID
	AND	LOC_DEST.LOCATION_GID = ORLS.DEST_LOCATION_GID
	
	AND	loc_tsp.location_gid = sh.servprov_gid
	
	
	/* and sh.shipment_gid in ('ULE/PR.100187592') */

	AND (SELECT SHS_STATUS_CANC.STATUS_VALUE_GID
	FROM SHIPMENT SH_STATUS_CANC
	LEFT OUTER JOIN SHIPMENT_STATUS SHS_STATUS_CANC ON (SH_STATUS_CANC.SHIPMENT_GID = SHS_STATUS_CANC.SHIPMENT_GID 
	AND SHS_STATUS_CANC.STATUS_TYPE_GID = 'ULE/PR.TRANSPORT CANCELLATION')
	WHERE SH_STATUS_CANC.SHIPMENT_GID = SH.SHIPMENT_GID
	)='ULE/PR.NOT CANCELLED'
	AND	sh.start_time >= trunc(SYSDATE) - 5

	
UNION ALL
(
SELECT SH.SHIPMENT_GID	AS																														SH_ID,
		'ORDERLESS' AS 																															OR_ID,
		SH.SOURCE_LOCATION_GID AS																												SOURCE_LOC_ID,
		LOC_SOURCE.CITY AS 																														SOURCE_CITY,
		LOC_SOURCE.COUNTRY_CODE3_GID AS 																													SOURCE_country,
		SH.DEST_LOCATION_GID AS																													DEST_LOC_ID,
		LOC_DEST.CITY AS 																														DESTINATION_CITY,
		LOC_DEST.COUNTRY_CODE3_GID AS 																											DEST_country,
		(select listagg(  TO_CHAR(FROM_TZ(CAST(IESH_EVENT_DELIVER.EVENTDATE AS TIMESTAMP), 'GMT') AT TIME ZONE LOC_SOURCE.TIME_ZONE_GID, 'YYYY-MM-DD HH24:MI:SS'))
				within group (order by SH_EVENT_DELIVER.shipment_gid)
				from 
				SHIPMENT SH_EVENT_DELIVER 
				LEFT OUTER JOIN SS_STATUS_HISTORY SSSH_EVENT_DELIVER ON (SH_EVENT_DELIVER.SHIPMENT_GID = SSSH_EVENT_DELIVER.SHIPMENT_GID)
				LEFT OUTER JOIN IE_SHIPMENTSTATUS IESH_EVENT_DELIVER ON (SSSH_EVENT_DELIVER.I_TRANSACTION_NO = IESH_EVENT_DELIVER.I_TRANSACTION_NO
				AND IESH_EVENT_DELIVER.STATUS_CODE_GID IN ('ULE/PR.CP','CP'))
				LEFT OUTER JOIN BS_STATUS_CODE BSSC_EVENT_DELIVER ON (IESH_EVENT_DELIVER.STATUS_CODE_GID = BSSC_EVENT_DELIVER.BS_STATUS_CODE_GID)
				
				
				where	SH_EVENT_DELIVER.SHIPMENT_GID = SH.SHIPMENT_GID
								AND	(SSSH_EVENT_DELIVER.INSERT_DATE = (
														SELECT 	MAX(SSSH_EVENT_DELIVER_TEMP.INSERT_DATE)
														FROM	SS_STATUS_HISTORY SSSH_EVENT_DELIVER_TEMP
																LEFT OUTER JOIN IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 
																ON (SSSH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO = IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO)
														WHERE 	SSSH_EVENT_DELIVER_TEMP.SHIPMENT_GID=SH.SHIPMENT_GID
																AND IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID IN ('ULE/PR.CP','CP')
														/* 		AND	IESH_EVENT_DELIVER_TEMP.EVENTDATE BETWEEN TO_DATE('2013-10-01','YYYY-MM-DD') 
																AND TO_DATE('2013-11-01 00:00:00','YYYY-MM-DD HH24:MI:SS') */
														
				
			))
				
				
				) as 																																		ACTUAL_PICKUP,
		
		(select listagg(  TO_CHAR(FROM_TZ(CAST(IESH_EVENT_DELIVER.EVENTDATE AS TIMESTAMP), 'GMT') AT TIME ZONE LOC_DEST.TIME_ZONE_GID, 'YYYY-MM-DD HH24:MI:SS'))
				within group (order by SH_EVENT_DELIVER.shipment_gid)
				from 
				SHIPMENT SH_EVENT_DELIVER 
				LEFT OUTER JOIN SS_STATUS_HISTORY SSSH_EVENT_DELIVER ON (SH_EVENT_DELIVER.SHIPMENT_GID = SSSH_EVENT_DELIVER.SHIPMENT_GID)
				LEFT OUTER JOIN IE_SHIPMENTSTATUS IESH_EVENT_DELIVER ON (SSSH_EVENT_DELIVER.I_TRANSACTION_NO = IESH_EVENT_DELIVER.I_TRANSACTION_NO 
				AND IESH_EVENT_DELIVER.STATUS_CODE_GID in ('ULE/PR.D1','D1'))
				LEFT OUTER JOIN BS_STATUS_CODE BSSC_EVENT_DELIVER ON (IESH_EVENT_DELIVER.STATUS_CODE_GID = BSSC_EVENT_DELIVER.BS_STATUS_CODE_GID)
				
				
				where	SH_EVENT_DELIVER.SHIPMENT_GID = SH.SHIPMENT_GID
								AND	(SSSH_EVENT_DELIVER.INSERT_DATE = (
														SELECT 	MAX(SSSH_EVENT_DELIVER_TEMP.INSERT_DATE)
														FROM	SS_STATUS_HISTORY SSSH_EVENT_DELIVER_TEMP
																LEFT OUTER JOIN IE_SHIPMENTSTATUS IESH_EVENT_DELIVER_TEMP 
																ON (SSSH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO = IESH_EVENT_DELIVER_TEMP.I_TRANSACTION_NO)
														WHERE 	SSSH_EVENT_DELIVER_TEMP.SHIPMENT_GID=SH.SHIPMENT_GID
																AND IESH_EVENT_DELIVER_TEMP.STATUS_CODE_GID in ('ULE/PR.D1','D1')
														/* 		AND	IESH_EVENT_DELIVER_TEMP.EVENTDATE BETWEEN TO_DATE('2013-10-01','YYYY-MM-DD') 
																AND TO_DATE('2013-11-01 00:00:00','YYYY-MM-DD HH24:MI:SS') */
														
				
			))
				
				
				) as 																																		ACTUAL_DELIVERY,
				
		(sh.servprov_gid) as 																													SERVICE_PROVIDER,
		loc_tsp.LOCATION_NAME as 																												SERVICE_PROVIDER_NAME,
		TO_char(sh.start_time,'DD-MM-YYYY HH24:MI:SS')																									SH_START_TIME,
		TO_char(sh.END_TIME,'DD-MM-YYYY HH24:MI:SS')																									SH_END_TIME,
		'-' AS																																	NEW_PICKUP,
		'-' AS 																																	NEW_DELIVERY,
		(
		select listagg(SH_CAT.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SH_CAT.SHIPMENT_GID)
		from SHIPMENT_REFNUM SH_CAT
		
		where SH_CAT.SHIPMENT_GID = SH.SHIPMENT_GID 
		AND SH_CAT.SHIPMENT_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_CATEGORY'
		
		
		) AS 																																			CATEGORY,
		(
		select listagg(SH_CAT.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SH_CAT.SHIPMENT_GID)
		from SHIPMENT_REFNUM SH_CAT
		
		where SH_CAT.SHIPMENT_GID = SH.SHIPMENT_GID 
		AND SH_CAT.SHIPMENT_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_TYPE'
		
		
		) AS 																																			MATERIAL,

		
		'N/A' AS																																SPECIAL_ORDER,
		
		'N/A' AS 																																EXPRESS,
		'N/A' AS 																																INSERT_USER,
		'N/A' AS 																																OR_po_num,
		'N/A' AS																																OR_DN_NUM,
		'"'||(select listagg(SHR_PO.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_PO.SHIPMENT_GID)
		from SHIPMENT_REFNUM SHR_PO 
		where SHR_PO.SHIPMENT_GID = sh.SHIPMENT_GID AND SHR_PO.SHIPMENT_REFNUM_QUAL_GID = 'ULE.PO'
		)||'"' as 																																sh_PO,
		'"'||(select listagg(SHR_DN.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_DN.SHIPMENT_GID)
		from SHIPMENT_REFNUM SHR_DN
		where SHR_DN.SHIPMENT_GID = sh.SHIPMENT_GID AND SHR_DN.SHIPMENT_REFNUM_QUAL_GID = 'ULE.DN'
		)||'"' as 																																SH_DN,
		SS.STOP_NUM AS 																																	STOP_NUM,
		ss.stop_type as																																	STOP_TYPE,
		SS.LOCATION_GID AS																																APP_LOCATION,
		
		
		(CASE WHEN ss.stop_type ='D' THEN 
		(
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.DEST_LOCATION_GID),'DD-MM-YYYY HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN ss.stop_type ='P' THEN (
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.SOURCE_LOCATION_GID),'DD-MM-YYYY HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		ELSE NULL
		END
		) AS 																																			APP_START,
		
		(CASE WHEN ss.stop_type ='D' THEN 
		(
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.DEST_LOCATION_GID),'DD-MM-YYYY HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN ss.stop_type ='P' THEN (
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.SOURCE_LOCATION_GID),'DD-MM-YYYY HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		ELSE NULL
		END
		) AS 																																			APP_END,
		
		
		
		
		'-' AS																																			COMMENTS,
		'-' AS																																			ADDITIONAL_COMMENTS
	
	
	
	
FROM
		SHIPMENT SH
				LEFT OUTER JOIN SHIPMENT_STOP SS ON	(SS.SHIPMENT_GID = SH.SHIPMENT_GID)
				LEFT OUTER JOIN SHIPMENT_STOP_D SSD ON (SSD.SHIPMENT_GID = SS.SHIPMENT_GID AND SSD.STOP_NUM = SS.STOP_NUM)
				LEFT OUTER JOIN S_SHIP_UNIT SSU ON (SSD.S_SHIP_UNIT_GID = SSU.S_SHIP_UNIT_GID)
				LEFT OUTER JOIN S_SHIP_UNIT_LINE SSUL ON (SSU.S_SHIP_UNIT_GID = SSUL.S_SHIP_UNIT_GID)
				LEFT OUTER JOIN ship_unit su ON (su.SHIP_UNIT_GID = SSU.SHIP_UNIT_GID)
				LEFT OUTER JOIN SHIP_UNIT_EQUIP_REF_UNIT_JOIN SUERUJ_PALLET on (su.SHIP_UNIT_GID = SUERUJ_PALLET.SHIP_UNIT_GID),
				
		LOCATION LOC_SOURCE,
		LOCATION LOC_DEST,
		location loc_tsp


WHERE 1=1	
	AND SH.DOMAIN_NAME = 'ULE/PR'
	AND	SH.SHIPMENT_TYPE_GID = 'APPOINTMENT'
	
	AND	LOC_SOURCE.LOCATION_GID = SH.SOURCE_LOCATION_GID
	AND	LOC_DEST.LOCATION_GID = SH.DEST_LOCATION_GID
	
	AND	loc_tsp.location_gid = sh.servprov_gid
	
	/* and	sh.shipment_gid in ('ULE/PR.100187592') */

	AND (SELECT SHS_STATUS_CANC.STATUS_VALUE_GID
	FROM SHIPMENT SH_STATUS_CANC
	LEFT OUTER JOIN SHIPMENT_STATUS SHS_STATUS_CANC ON (SH_STATUS_CANC.SHIPMENT_GID = SHS_STATUS_CANC.SHIPMENT_GID 
	AND SHS_STATUS_CANC.STATUS_TYPE_GID = 'ULE/PR.TRANSPORT CANCELLATION')
	WHERE SH_STATUS_CANC.SHIPMENT_GID = SH.SHIPMENT_GID
	)='ULE/PR.NOT CANCELLED'
	AND	sh.start_time >= trunc(SYSDATE) - 5

)
order by 1,2