SELECT * FROM
(SELECT DISTINCT ORLS.SOURCE_LOCATION_GID AS																														SOURCE_LOC_ID,
		loc_source.location_name as																														Source_name,
		LOC_SOURCE.CITY AS 																																SOURCE_CITY,
		LOC_SOURCE.COUNTRY_CODE3_GID AS 																												SOURCE_country,
		ORLS.DEST_LOCATION_GID	AS																														DEST_LOC_ID,
		loc_dest.location_name as																														Dest_name,
		LOC_DEST.CITY AS 																																DESTINATION_CITY,
		LOC_DEST.COUNTRY_CODE3_GID AS 																													DEST_country,			
		(
		select listagg(orls_CAT.order_release_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orls_CAT.order_release_GID)
		from order_release_REFNUM orls_CAT
		
		where orls_CAT.order_release_GID = orls.order_release_GID 
		AND orls_CAT.order_release_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_CATEGORY'
		) AS 																																			CATEGORY,
		
		(
		select listagg(orls_CAT.order_release_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orls_CAT.order_release_GID)
		from order_release_REFNUM orls_CAT
		
		where orls_CAT.order_release_GID = orls.order_release_GID 
		AND orls_CAT.order_release_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_TYPE'

		) AS 																																			MATERIAL,
		(select NVL(SR_REGION.SHIPMENT_REFNUM_VALUE,'N/A') AS REGION
		from SHIPMENT_REFNUM SR_REGION 
		where SR_REGION.SHIPMENT_GID = sh.SHIPMENT_GID AND SR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION'
		)																																				REGION,
		(select listagg(SHR_RA.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_RA.SHIPMENT_GID)																										
		from SHIPMENT_REFNUM SHR_RA 
		where (SHR_RA.SHIPMENT_GID = sh.SHIPMENT_GID AND SHR_RA.SHIPMENT_REFNUM_QUAL_GID='ULE/PR.ULE_OR_REL_ATR')
		) as 																																			RELEASE_ATTR,
		ORLS.ORDER_RELEASE_GID	AS																														OR_ID,	
		SH.SHIPMENT_GID AS																																SH_ID,
		'"'||(
		select listagg(orlsr_po.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orlsr_po.ORDER_RELEASE_GID)
		from ORDER_RELEASE_REFNUM orlsr_po 
		
		where orls.ORDER_RELEASE_GID = orlsr_po.ORDER_RELEASE_GID 
				AND orlsr_po.ORDER_RELEASE_REFNUM_QUAL_GID IN
				('PO','ULE.ULE_PO_NUMBER','ULE.ULE_SAP_PO_NUMBER','CUST_PO','ULE.ULE_FINANCE_PO_NUMBER')
		
		
		)||'"' AS 																																		OR_PO_NUM,
		'"'||(
		select listagg(orlsr_DN_ULE.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orlsr_DN_ULE.ORDER_RELEASE_GID)
		from ORDER_RELEASE_REFNUM orlsr_DN_ULE 
		
		where orls.ORDER_RELEASE_GID = orlsr_DN_ULE.ORDER_RELEASE_GID 
				AND orlsr_DN_ULE.ORDER_RELEASE_REFNUM_QUAL_GID IN ('ULE.ULE_DN_NUMBER','UL_SAP_DN')
		
		
		)||'"' AS 																																		OR_DN_NUM,
		LTRIM(TO_CHAR(ORLS.TOTAL_SHIP_UNIT_COUNT,'999999999','NLS_NUMERIC_CHARACTERS = '', ''')) AS														NUM_OF_PALLETS,
		(
		select listagg(orlsr_EXP.ORDER_RELEASE_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY orlsr_EXP.ORDER_RELEASE_GID)
		from ORDER_RELEASE_REFNUM orlsr_EXP
		
		where orls.ORDER_RELEASE_GID = orlsr_EXP.ORDER_RELEASE_GID 
				AND orlsr_EXP.ORDER_RELEASE_REFNUM_QUAL_GID IN ('ULE.ULE_EXPRESS_BY_CUSTOMER')

		) AS 																																			EXPRESS,
		to_char(ORLS.insert_date,'DD-MM-YYYY HH24:MI:SS') AS 																							or_INSERT_date,
		to_char(ORLS.early_pickup_date,'DD-MM-YYYY HH24:MI:SS') AS 																						early_pickup_date,
		to_char(ORLS.late_delivery_date,'DD-MM-YYYY HH24:MI:SS') AS 																					late_delivery_date,
		TO_char(sh.start_time,'DD-MM-YYYY HH24:MI:SS')																									SH_START_TIME,
		TO_char(sh.END_TIME,'DD-MM-YYYY HH24:MI:SS')																									SH_END_TIME,
		(
		
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,ORLS.SOURCE_LOCATION_GID),'DD-MM-YYYY HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID

				AND	LR_LOAD_T.LOCATION_GID = ORLS.SOURCE_LOCATION_GID

		) AS 																																			APP_PICKUP,
		(
		
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,ORLS.DEST_LOCATION_GID),'DD-MM-YYYY HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID

				AND	LR_LOAD_T.LOCATION_GID = ORLS.DEST_LOCATION_GID

		) AS 																																			APP_DESTINATION,
		(sh.servprov_gid) as 																															SERVICE_PROVIDER,
		loc_tsp.LOCATION_NAME as 																														SERVPROV_NAME,
		(
		select listagg(SH_STATUS.STATUS_VALUE_GID,'|') WITHIN GROUP (ORDER BY SH_STATUS.SHIPMENT_GID)
		from SHIPMENT_STATUS SH_STATUS
		
		where SH.SHIPMENT_GID = SH_STATUS.SHIPMENT_GID 
				AND SH_STATUS.STATUS_TYPE_GID IN ('ULE/PR.SECURE RESOURCES')
		
		
		) AS 																																			SECURE_RESOURCES_STATUS

	
FROM
	SHIPMENT_STOP SS,
	SHIPMENT SH,
	SHIPMENT_STOP_D SSD,
	S_SHIP_UNIT SSU,
	S_SHIP_UNIT_LINE SSUL,
	ORDER_RELEASE ORLS,
	LOCATION LOC_SOURCE,
	LOCATION LOC_DEST,
	location loc_tsp


WHERE 1=1
	AND SH.DOMAIN_NAME = 'ULE/PR'
	AND	SH.SHIPMENT_TYPE_GID = 'TRANSPORT'
	
	AND	SS.SHIPMENT_GID = SH.SHIPMENT_GID
	AND SSD.SHIPMENT_GID = SS.SHIPMENT_GID
	AND SSD.STOP_NUM = SS.STOP_NUM
	AND SSD.S_SHIP_UNIT_GID = SSU.S_SHIP_UNIT_GID
	AND SSU.S_SHIP_UNIT_GID = SSUL.S_SHIP_UNIT_GID
	AND SSUL.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID

	
	AND	LOC_SOURCE.LOCATION_GID = ORLS.SOURCE_LOCATION_GID
	AND	LOC_DEST.LOCATION_GID = ORLS.DEST_LOCATION_GID
	
	AND	loc_tsp.location_gid = sh.servprov_gid
	
	

	AND (SELECT SHS_STATUS_CANC.STATUS_VALUE_GID
	FROM SHIPMENT SH_STATUS_CANC
	LEFT OUTER JOIN SHIPMENT_STATUS SHS_STATUS_CANC ON (SH_STATUS_CANC.SHIPMENT_GID = SHS_STATUS_CANC.SHIPMENT_GID 
	AND SHS_STATUS_CANC.STATUS_TYPE_GID = 'ULE/PR.TRANSPORT CANCELLATION')
	WHERE SH_STATUS_CANC.SHIPMENT_GID = SH.SHIPMENT_GID
	)='ULE/PR.NOT CANCELLED'
	AND	ORLS.INSERT_DATE >= trunc(SYSDATE) - 7
	
		AND ORLS.SOURCE_LOCATION_GID = nvl(:SOURCE_LOC,ORLS.SOURCE_LOCATION_GID)
		AND ORLS.DEST_LOCATION_GID = nvl(:DEST_LOC,ORLS.DEST_LOCATION_GID)
		

UNION ALL
(
SELECT SH.SOURCE_LOCATION_GID AS																														SOURCE_LOC_ID,
		loc_source.location_name as																														Source_name,
		LOC_SOURCE.CITY AS 																																SOURCE_CITY,
		LOC_SOURCE.COUNTRY_CODE3_GID AS 																												SOURCE_country,
		SH.DEST_LOCATION_GID AS																															DEST_LOC_ID,
		loc_dest.location_name as																														Dest_name,
		LOC_DEST.CITY AS 																																DESTINATION_CITY,
		LOC_DEST.COUNTRY_CODE3_GID AS 																													DEST_country,	
		(
		select listagg(SH_CAT.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SH_CAT.SHIPMENT_GID)
		from SHIPMENT_REFNUM SH_CAT
		
		where SH_CAT.SHIPMENT_GID = SH.SHIPMENT_GID 
		AND SH_CAT.SHIPMENT_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_CATEGORY'
		
		
		) AS 																																			CATEGORY,
		(
		select listagg(SH_CAT.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SH_CAT.SHIPMENT_GID)
		from SHIPMENT_REFNUM SH_CAT
		
		where SH_CAT.SHIPMENT_GID = SH.SHIPMENT_GID 
		AND SH_CAT.SHIPMENT_REFNUM_QUAL_GID ='ULE.ULE_MATERIAL_TYPE'
		) AS 																																			MATERIAL,
		(select NVL(SR_REGION.SHIPMENT_REFNUM_VALUE,'N/A') AS REGION
		from SHIPMENT_REFNUM SR_REGION 
		where SR_REGION.SHIPMENT_GID = sh.SHIPMENT_GID AND SR_REGION.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_FUNCTIONAL_REGION'
		)																																				REGION,
		(select listagg(SHR_RA.SHIPMENT_REFNUM_VALUE,'|') WITHIN GROUP (ORDER BY SHR_RA.SHIPMENT_GID)																										
		from SHIPMENT_REFNUM SHR_RA 
		where (SHR_RA.SHIPMENT_GID = sh.SHIPMENT_GID AND SHR_RA.SHIPMENT_REFNUM_QUAL_GID='ULE/PR.ULE_OR_REL_ATR')
		) as 																																			RELEASE_ATTR,
		'ORDERLESS' AS 																																	OR_ID,
		SH.SHIPMENT_GID	AS																																SH_ID,
		'N/A' AS 																																		OR_po_num,
		'N/A' AS																																		OR_DN_NUM,		
		LTRIM(TO_CHAR(SH.TOTAL_SHIP_UNIT_COUNT,'999999999','NLS_NUMERIC_CHARACTERS = '', ''')) AS														NUM_OF_PALLETS,
		'N/A' AS 																																		EXPRESS,
		'N/A' AS 																																		or_INSERT_date,
		'N/A' AS 																																		early_pickup_date,
		'N/A' AS 																																		late_delivery_date,
		TO_char(sh.start_time,'DD-MM-YYYY HH24:MI:SS')																									SH_START_TIME,
		TO_char(sh.END_TIME,'DD-MM-YYYY HH24:MI:SS')																									SH_END_TIME,
		( 
		
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.SOURCE_LOCATION_GID),'DD-MM-YYYY HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID

				AND	LR_LOAD_T.LOCATION_GID = SH.SOURCE_LOCATION_GID


		) AS 																																			APP_PICKUP,
		(
		
		SELECT listagg(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.DEST_LOCATION_GID),'DD-MM-YYYY HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID

				AND	LR_LOAD_T.LOCATION_GID = SH.DEST_LOCATION_GID


		) AS 																																			APP_DESTINATION,
		
		(sh.servprov_gid) as 																															SERVICE_PROVIDER,
		loc_tsp.LOCATION_NAME as 																														SERVICE_PROVIDER_NAME,
		(
		select listagg(SH_STATUS.STATUS_VALUE_GID,'|') WITHIN GROUP (ORDER BY SH_STATUS.SHIPMENT_GID)
		from SHIPMENT_STATUS SH_STATUS
		
		where SH.SHIPMENT_GID = SH_STATUS.SHIPMENT_GID 
				AND SH_STATUS.STATUS_TYPE_GID IN ('ULE/PR.SECURE RESOURCES')
		
		
		) AS 																																			STATUS

FROM
		SHIPMENT SH,
		LOCATION LOC_SOURCE,
		LOCATION LOC_DEST,
		location loc_tsp


WHERE 1=1	
	AND SH.DOMAIN_NAME = 'ULE/PR'
	AND	SH.SHIPMENT_TYPE_GID = 'APPOINTMENT'
	
	AND	LOC_SOURCE.LOCATION_GID = SH.SOURCE_LOCATION_GID
	AND	LOC_DEST.LOCATION_GID = SH.DEST_LOCATION_GID
	
	AND	loc_tsp.location_gid = sh.servprov_gid
	


	AND (SELECT SHS_STATUS_CANC.STATUS_VALUE_GID
	FROM SHIPMENT SH_STATUS_CANC
	LEFT OUTER JOIN SHIPMENT_STATUS SHS_STATUS_CANC ON (SH_STATUS_CANC.SHIPMENT_GID = SHS_STATUS_CANC.SHIPMENT_GID 
	AND SHS_STATUS_CANC.STATUS_TYPE_GID = 'ULE/PR.TRANSPORT CANCELLATION')
	WHERE SH_STATUS_CANC.SHIPMENT_GID = SH.SHIPMENT_GID
	)='ULE/PR.NOT CANCELLED'
	AND	SH.INSERT_DATE >= trunc(SYSDATE) - 7
	
	AND SH.SOURCE_LOCATION_GID = nvl(:SOURCE_LOC,SH.SOURCE_LOCATION_GID)
		AND SH.DEST_LOCATION_GID = nvl(:DEST_LOC,SH.DEST_LOCATION_GID)
		
		
)) TEMP
WHERE 1=1

	and 
	(TEMP.SOURCE_LOC_ID IN('ULE.V207495','ULE.V1032218','ULE.V214488','ULE.V1091008','ULE.V214431','ULE.V205292','ULE.V50281484','ULE.V205314','ULE.V205289','ULE.V50287367','ULE.V1119606','ULE.V207492','ULE.V207493','ULE.V376605','ULE.V218340','ULE.V1023359','ULE.V189455','ULE.V162314','ULE.V207483','ULE.V207493','ULE.V205315','ULE.V214452','ULE.V50051190','ULE.V205304','ULE.V214530','ULE.V214514','ULE.V214430','ULE.V214521','ULE.V233189 ','ULE.V214526','ULE.V214527','ULE.V214528','ULE.V1046356','ULE.V231617','ULE.V316531','ULE.V225416 ','ULE.V1113994','ULE.V215299','ULE.V200711','ULE.V200719','ULE.V205283','ULE.V205309','ULE.V1098219','ULE.V225910','ULE.V208866','ULE.V50424902','ULE.V50282133','ULE.V218348 ','ULE.v218346 ','ULE.V50414733 ','ULE.V218347','ULE.V1025942','ULE.V218331','ULE.V162316','ULE.V218350','ULE.V225407','ULE.V1013868','ULE.V1066121','ULE.V36881','ULE.C294074','ULE.V205278','ULE.V205287')
	OR TEMP.DEST_LOC_ID IN ('ULE.V207495','ULE.V1032218','ULE.V214488','ULE.V1091008','ULE.V214431','ULE.V205292','ULE.V50281484','ULE.V205314','ULE.V205289','ULE.V50287367','ULE.V1119606','ULE.V207492','ULE.V207493','ULE.V376605','ULE.V218340','ULE.V1023359','ULE.V189455','ULE.V162314','ULE.V207483','ULE.V207493','ULE.V205315','ULE.V214452','ULE.V50051190','ULE.V205304','ULE.V214530','ULE.V214514','ULE.V214430','ULE.V214521','ULE.V233189 ','ULE.V214526','ULE.V214527','ULE.V214528','ULE.V1046356','ULE.V231617','ULE.V316531','ULE.V225416 ','ULE.V1113994','ULE.V215299','ULE.V200711','ULE.V200719','ULE.V205283','ULE.V205309','ULE.V1098219','ULE.V225910','ULE.V208866','ULE.V50424902','ULE.V50282133','ULE.V218348 ','ULE.v218346 ','ULE.V50414733 ','ULE.V218347','ULE.V1025942','ULE.V218331','ULE.V162316','ULE.V218350','ULE.V225407','ULE.V1013868','ULE.V1066121','ULE.V36881','ULE.C294074','ULE.V205278','ULE.V205287'))
		