 SELECT DISTINCT SH.SHIPMENT_GID AS																														SH_ID,
		ORLS.ORDER_RELEASE_GID	AS																														OR_ID,
	
		ORLS.SOURCE_LOCATION_GID AS																														SOURCE_LOC_ID,
		LOC_SOURCE.CITY AS 																																SOURCE_CITY,
		
		ORLS.DEST_LOCATION_GID	AS																														DEST_LOC_ID,
		LOC_DEST.CITY AS 																																DESTINATION_CITY,
		(SH.SERVPROV_GID) AS 																															SERVICE_PROVIDER,
		(SELECT LOC_TSP.LOCATION_NAME
		FROM SHIPMENT SH_SERVPROV
		LEFT OUTER JOIN LOCATION LOC_TSP ON (LOC_TSP.LOCATION_GID = SH_SERVPROV.SERVPROV_GID)
		WHERE
			SH_SERVPROV.SHIPMENT_GID = SH.SHIPMENT_GID
		)AS 																																			SERVICE_PROVIDER_NAME,
		SU.TRANSPORT_HANDLING_UNIT_GID AS 																												TRANSPORT_HANDLING_UNIT,
		TO_CHAR(SU.SHIP_UNIT_COUNT,'9,999,999.99') AS 																									NUMBER_OF_PALLETS,

		SS.STOP_NUM AS 																																	STOP_NUM,
		SS.STOP_TYPE AS																																	STOP_TYPE,
		SS.LOCATION_GID AS																																APP_LOCATION,
		(CASE WHEN SS.STOP_TYPE ='D' THEN 
		(
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,ORLS.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_TYPE ='P' THEN (
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,ORLS.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				AND APP_LOAD_T.INSERT_DATE = (SELECT DISTINCT 
        MAX(APP_LOAD_T_TEMP.INSERT_DATE)
        FROM APPOINTMENT APP_LOAD_T_TEMP
        WHERE APP_LOAD_T_TEMP.OBJECT_GID = APP_LOAD_T.OBJECT_GID
		AND	APP_LOAD_T_TEMP.STOP_NUM = APP_LOAD_T.STOP_NUM)
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		ELSE NULL
		END
		) AS 																																			APP_START,
		
		(CASE WHEN SS.STOP_TYPE ='D' THEN 
		(
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_END_TIME,ORLS.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_TYPE ='P' THEN (
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_END_TIME,ORLS.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				AND APP_LOAD_T.INSERT_DATE = (SELECT DISTINCT 
        MAX(APP_LOAD_T_TEMP.INSERT_DATE)
        FROM APPOINTMENT APP_LOAD_T_TEMP
        WHERE APP_LOAD_T_TEMP.OBJECT_GID = APP_LOAD_T.OBJECT_GID
		AND	APP_LOAD_T_TEMP.STOP_NUM = APP_LOAD_T.STOP_NUM)
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		ELSE NULL
		END
		) AS 																																			APP_END
FROM
	SHIPMENT_STOP SS,
	SHIPMENT SH,
	-- SHIPMENT_STOP_D SSD,
	-- S_SHIP_UNIT SSU,
	-- S_SHIP_UNIT_LINE SSUL,
	ORDER_RELEASE ORLS,
	LOCATION LOC_SOURCE,
	LOCATION LOC_DEST,
	order_movement om
	/* SHIP_UNIT_EQUIP_REF_UNIT_JOIN SUERUJ_PALLET, */
	,SHIP_UNIT SU

WHERE 1=1
	AND SH.DOMAIN_NAME IN ('ULE/PR','SERVPROV','ULE','UGO')
	AND NOT EXISTS
	(SELECT 1
	 FROM shipment_refnum sh_ref_1
	 WHERE sh_ref_1.Shipment_Refnum_Qual_Gid = 'ULE.ULE_SHIPMENT_STREAM'
		   AND sh_ref_1.Shipment_Refnum_Value = 'SECONDARY'
		   AND sh_ref_1.SHIPMENT_GID = SH.SHIPMENT_GID)
	AND	SH.SHIPMENT_TYPE_GID IN ('TRANSPORT')
	AND OM.SHIPMENT_GID = SH.SHIPMENT_GID
	AND OM.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
	AND	SS.SHIPMENT_GID = SH.SHIPMENT_GID
	-- AND SSD.SHIPMENT_GID = SS.SHIPMENT_GID
	-- AND SSD.STOP_NUM = SS.STOP_NUM
	-- AND SSD.S_SHIP_UNIT_GID = SSU.S_SHIP_UNIT_GID
	-- AND SSU.S_SHIP_UNIT_GID = SSUL.S_SHIP_UNIT_GID
	AND SU.ORDER_RELEASE_GID = ORLS.ORDER_RELEASE_GID
	
	/* AND	SU.SHIP_UNIT_GID = SUERUJ_PALLET.SHIP_UNIT_GID */
	-- AND	SU.SHIP_UNIT_GID = SSU.SHIP_UNIT_GID
	
	AND	LOC_SOURCE.LOCATION_GID = ORLS.SOURCE_LOCATION_GID
	AND	LOC_DEST.LOCATION_GID = ORLS.DEST_LOCATION_GID
	

	
	AND SS.LOCATION_GID = NVL(:APP_LOC,SS.LOCATION_GID)
	
	AND NOT EXISTS(SELECT 1
	FROM shipment_refnum
	WHERE shipment_gid = Sh.shipment_gid
	AND shipment_refnum_qual_gid = 'ULE.ULE_SHIPMENT_STREAM'
	AND shipment_refnum_value = 'SECONDARY')
	
	AND	SH.START_TIME >= TRUNC(SYSDATE) - 14
	AND	SH.START_TIME <= TRUNC(SYSDATE) + 5

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	
UNION ALL
(
SELECT SH.SHIPMENT_GID	AS																														SH_ID,
		'ORDERLESS' AS 																															OR_ID,
		SH.SOURCE_LOCATION_GID AS																												SOURCE_LOC_ID,
		LOC_SOURCE.CITY AS 																														SOURCE_CITY,
		
		SH.DEST_LOCATION_GID AS																													DEST_LOC_ID,
		LOC_DEST.CITY AS 																														DESTINATION_CITY,
		
		(SH.SERVPROV_GID) AS 																													SERVICE_PROVIDER,
		
		(SELECT LOC_TSP.LOCATION_NAME
		FROM SHIPMENT SH_SERVPROV
		LEFT OUTER JOIN LOCATION LOC_TSP ON (LOC_TSP.LOCATION_GID = SH_SERVPROV.SERVPROV_GID)
		WHERE
			SH_SERVPROV.SHIPMENT_GID = SH.SHIPMENT_GID
		)AS 																																	SERVICE_PROVIDER_NAME,
		
		
		
		'N/A' AS 																										TRANSPORT_HANDLING_UNIT,
		TO_CHAR(SH.TOTAL_SHIP_UNIT_COUNT,'9,999,999.99') AS 																							NUMBER_OF_PALLETS,
		
		
		SS.STOP_NUM AS 																															STOP_NUM,
		SS.STOP_TYPE AS																																	STOP_TYPE,
		SS.LOCATION_GID AS																														APP_LOCATION,
		(CASE WHEN SS.STOP_TYPE ='D' THEN 
		(
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_TYPE ='P' THEN (
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				AND APP_LOAD_T.INSERT_DATE = (SELECT DISTINCT 
        MAX(APP_LOAD_T_TEMP.INSERT_DATE)
        FROM APPOINTMENT APP_LOAD_T_TEMP
        WHERE APP_LOAD_T_TEMP.OBJECT_GID = APP_LOAD_T.OBJECT_GID
		AND	APP_LOAD_T_TEMP.STOP_NUM = APP_LOAD_T.STOP_NUM)
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_NUM ='1' THEN (
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				AND APP_LOAD_T.INSERT_DATE = (SELECT DISTINCT 
        MAX(APP_LOAD_T_TEMP.INSERT_DATE)
        FROM APPOINTMENT APP_LOAD_T_TEMP
        WHERE APP_LOAD_T_TEMP.OBJECT_GID = APP_LOAD_T.OBJECT_GID
		AND	APP_LOAD_T_TEMP.STOP_NUM = APP_LOAD_T.STOP_NUM)
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_NUM ='2' THEN 
		(
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_START_TIME,SH.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		ELSE NULL
		END
		) AS 																																			APP_START,
		
		(CASE WHEN SS.STOP_TYPE ='D' THEN 
		(
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_END_TIME,SH.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_TYPE ='P' THEN (
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_END_TIME,SH.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				AND APP_LOAD_T.INSERT_DATE = (SELECT DISTINCT 
        MAX(APP_LOAD_T_TEMP.INSERT_DATE)
        FROM APPOINTMENT APP_LOAD_T_TEMP
        WHERE APP_LOAD_T_TEMP.OBJECT_GID = APP_LOAD_T.OBJECT_GID
		AND	APP_LOAD_T_TEMP.STOP_NUM = APP_LOAD_T.STOP_NUM)
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_NUM ='1' THEN (
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_END_TIME,SH.SOURCE_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				AND APP_LOAD_T.INSERT_DATE = (SELECT DISTINCT 
        MAX(APP_LOAD_T_TEMP.INSERT_DATE)
        FROM APPOINTMENT APP_LOAD_T_TEMP
        WHERE APP_LOAD_T_TEMP.OBJECT_GID = APP_LOAD_T.OBJECT_GID
		AND	APP_LOAD_T_TEMP.STOP_NUM = APP_LOAD_T.STOP_NUM)
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		WHEN SS.STOP_NUM ='2' THEN 
		(
		SELECT LISTAGG(TO_CHAR(UTC.GET_LOCAL_DATE(APP_LOAD_T.APPOINTMENT_END_TIME,SH.DEST_LOCATION_GID),'YYYY-MM-DD HH24:MI'),'|') 
		WITHIN GROUP(ORDER BY SH_APP_LOAD_T.SHIPMENT_GID)
		FROM SHIPMENT SH_APP_LOAD_T
				LEFT OUTER JOIN APPOINTMENT APP_LOAD_T ON (APP_LOAD_T.OBJECT_GID = SH_APP_LOAD_T.SHIPMENT_GID)
				LEFT OUTER JOIN LOCATION_RESOURCE LR_LOAD_T ON (LR_LOAD_T.LOCATION_RESOURCE_GID = APP_LOAD_T.LOCATION_RESOURCE_GID)
		WHERE 1=1
				AND	SH_APP_LOAD_T.SHIPMENT_GID = SH.SHIPMENT_GID
				AND	APP_LOAD_T.STOP_NUM  = SS.STOP_NUM
				/* AND	(ORLS.SOURCE_LOCATION_GID = LR_LOAD_T.LOCATION_GID OR LR_LOAD_T.LOCATION_GID IS NULL) */
		)
		ELSE NULL
		END
		) AS 																																			APP_END

FROM
		SHIPMENT SH,
		SHIPMENT_STOP SS,
				-- LEFT OUTER JOIN SHIPMENT_STOP_D SSD ON (SSD.SHIPMENT_GID = SS.SHIPMENT_GID AND SSD.STOP_NUM = SS.STOP_NUM)
				-- LEFT OUTER JOIN S_SHIP_UNIT SSU ON (SSD.S_SHIP_UNIT_GID = SSU.S_SHIP_UNIT_GID)
				-- LEFT OUTER JOIN S_SHIP_UNIT_LINE SSUL ON (SSU.S_SHIP_UNIT_GID = SSUL.S_SHIP_UNIT_GID)
				-- LEFT OUTER JOIN SHIP_UNIT SU ON (SU.SHIP_UNIT_GID = SSU.SHIP_UNIT_GID),
				/* LEFT OUTER JOIN SHIP_UNIT_EQUIP_REF_UNIT_JOIN SUERUJ_PALLET ON (SU.SHIP_UNIT_GID = SUERUJ_PALLET.SHIP_UNIT_GID), */
				
		LOCATION LOC_SOURCE,
		LOCATION LOC_DEST

WHERE 1=1	
	AND SH.DOMAIN_NAME IN ('ULE/PR','SERVPROV','ULE','UGO')
	AND SS.SHIPMENT_GID = SH.SHIPMENT_GID
	AND NOT EXISTS
	(SELECT 1
	 FROM shipment_refnum sh_ref_1
	 WHERE sh_ref_1.Shipment_Refnum_Qual_Gid = 'ULE.ULE_SHIPMENT_STREAM'
		   AND sh_ref_1.Shipment_Refnum_Value = 'SECONDARY'
		   AND sh_ref_1.SHIPMENT_GID = SH.SHIPMENT_GID)
	AND	SH.SHIPMENT_TYPE_GID IN ('APPOINTMENT')
	
	AND NOT EXISTS(SELECT 1
	FROM shipment_refnum
	WHERE shipment_gid = Sh.shipment_gid
	AND shipment_refnum_qual_gid = 'ULE.ULE_SHIPMENT_STREAM'
	AND shipment_refnum_value = 'SECONDARY')
	
	AND	LOC_SOURCE.LOCATION_GID = SH.SOURCE_LOCATION_GID
	AND	LOC_DEST.LOCATION_GID = SH.DEST_LOCATION_GID
	

	
	AND SS.LOCATION_GID = NVL(:APP_LOC,SS.LOCATION_GID)
	
	
	AND	SH.START_TIME >= TRUNC(SYSDATE) - 14
	AND	SH.START_TIME <= TRUNC(SYSDATE) + 5
	
)