SELECT SH.SHIPMENT_GID
,SH.SOURCE_LOCATION_GID
,SH.DEST_LOCATION_GID
,(SELECT LOC.COUNTRY_CODE3_GID
FROM LOCATION LOC
WHERE LOC.LOCATION_GID = SH.SOURCE_LOCATION_GID

)																SH_SOURCE_COUNTRY
,(SELECT LOC.COUNTRY_CODE3_GID
FROM LOCATION LOC
WHERE LOC.LOCATION_GID = SH.DEST_LOCATION_GID

)																SH_DEST_COUNTRY
,SH.SERVPROV_GID												
,(SELECT LOC.LOCATION_NAME
FROM LOCATION LOC
WHERE LOC.LOCATION_GID = SH.SERVPROV_GID

)																SERVPROV_NAME
,(SELECT LOC_REF.LOCATION_REFNUM_VALUE
FROM LOCATION_REFNUM LOC_REF
WHERE LOC_REF.LOCATION_GID = SH.SERVPROV_GID
AND LOC_REF.LOCATION_REFNUM_QUAL_GID = 'ULE.ULE_RESPONSIBLE_REGION'

)																RESPONSIBLE_REGION
,(SELECT SH_REF.SHIPMENT_REFNUM_VALUE
FROM SHIPMENT_REFNUM SH_REF
WHERE SH_REF.SHIPMENT_REFNUM_QUAL_GID = 'ULE.ULE_SHIPMENT_STREAM'
AND SH.SHIPMENT_GID = SH_REF.SHIPMENT_GID
)																STREAM
,to_char(sh.start_time,'YYYY-MM-DD')				START_TIME
,to_char(sh.END_time,'YYYY-MM-DD')					END_TIME
,(select(SUM(CASE
				WHEN (alloc_d.COST_GID = 'EUR' or alloc_d.COST_GID is null) THEN alloc_d.COST
				when alloc_d.COST_GID <> 'EUR' then alloc_d.COST * 
				unilever.ebs_procedures_ule.GET_QUARTERLY_EX_RATE(NVL(to_date(SH.START_TIME,'DD.MM.YYYY'),SYSDATE),alloc_d.COST_GID,'EUR')
				END)
			)
			from shipment_cost alloc_d
			where alloc_d.shipment_gid = sh.shipment_gid
			)																												TOTAL_COST


FROM
SHIPMENT SH
,SHIPMENT_STATUS SS

WHERE
SH.SHIPMENT_GID = SS.SHIPMENT_GID
AND SS.STATUS_TYPE_GID = 'ULE/PR.SHIPMENT_COST'
AND SS.STATUS_VALUE_GID <> 'ULE/PR.SC_NO CHANGES ALLOWED'
AND 
(EXISTS 
(SELECT 1
FROM LOCATION LOC
WHERE LOC.LOCATION_GID = SH.SOURCE_LOCATION_GID
AND LOC.COUNTRY_CODE3_GID = 'GRC'
)
OR EXISTS
(SELECT 1
FROM LOCATION LOC
WHERE LOC.LOCATION_GID = SH.DEST_LOCATION_GID
AND LOC.COUNTRY_CODE3_GID = 'GRC'
)
)

AND TRUNC(SH.INSERT_DATE) >= TO_DATE('2016-01-01','YYYY-MM-DD')